import type { Service } from '@/types'

export const SERVICES: Service[] = [
  {
    slug: 'regular-cleaning',
    name: 'Regular House Cleaning',
    shortDescription: 'Weekly or fortnightly cleaning to keep your home consistently fresh.',
    description: 'Our regular cleaning service is designed to fit around your life. Choose weekly or fortnightly visits, and our vetted cleaners will maintain a consistently clean and healthy home for you.',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Dusting surfaces, shelves, and skirting boards',
      'Cleaning kitchen benchtops and appliance exteriors',
      'Cleaning and sanitising bathrooms and toilets',
      'Emptying bins throughout the home',
      'Making beds and tidying rooms',
      'Spot-cleaning windows and mirrors',
    ],
    fromPrice: 120,
    metaDescription: 'Regular house cleaning in Auckland from $120. Weekly or fortnightly visits by vetted, insured cleaners. Eco-friendly products. Book a free quote today.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'window-cleaning'],
  },
  {
    slug: 'deep-cleaning',
    name: 'Deep Cleaning',
    shortDescription: 'A top-to-bottom refresh that reaches every corner.',
    description: 'Our deep clean goes far beyond a regular tidy. We tackle built-up grime, hidden dust, and neglected corners — ideal as a one-off seasonal clean or before/after a big event.',
    heroImage: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=800&q=80',
    includes: [
      'Everything in our regular clean',
      'Inside oven and microwave cleaning',
      'Inside fridge cleaning',
      'Deep scrubbing of tile grout',
      'Cleaning inside cabinets and drawers',
      'Washing interior windows and tracks',
      'Wiping down all light switches and door handles',
      'Behind and under furniture vacuuming',
    ],
    fromPrice: 280,
    metaDescription: 'Deep cleaning in Auckland from $280. Top-to-bottom clean including oven, fridge, grout, and hidden areas. Fully insured. Get a free quote today.',
    relatedSlugs: ['regular-cleaning', 'end-of-tenancy', 'post-construction'],
  },
  {
    slug: 'end-of-tenancy',
    name: 'End of Tenancy Cleaning',
    shortDescription: 'Move-out ready — get your bond back with confidence.',
    description: 'Our end of tenancy clean is comprehensive and meets the expectations of Auckland property managers. We help tenants get their full bond back and landlords prepare for new occupants.',
    heroImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    includes: [
      'Full deep clean of all rooms',
      'Oven, stovetop, and range hood cleaning',
      'Fridge and dishwasher cleaning',
      'Bathroom and toilet descaling',
      'All windows, tracks, and sills',
      'Carpet vacuuming (steam clean available as add-on)',
      'Walls spot-cleaned',
      'Garage and outdoor areas swept',
    ],
    fromPrice: 350,
    metaDescription: 'End of tenancy cleaning in Auckland from $350. Bond-back guaranteed clean. Thorough, fast, and fully insured. Get a free quote from Sano Cleaning.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'post-construction'],
  },
  {
    slug: 'commercial-cleaning',
    name: 'Commercial & Office Cleaning',
    shortDescription: 'Keep your workplace spotless and your team productive.',
    description: 'A clean workplace makes a difference. Our commercial cleaning team handles offices, retail spaces, and small businesses across Auckland — after-hours or early morning to minimise disruption.',
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Desk and workstation wiping',
      'Kitchen and break room cleaning',
      'Bathroom and toilet sanitising',
      'Bin emptying and bag replacement',
      'Glass partition and window cleaning',
      'Reception and entrance area cleaning',
    ],
    fromPrice: 200,
    metaDescription: 'Commercial cleaning in Auckland from $200. Office, retail, and business cleaning after-hours. Vetted cleaners, flexible scheduling. Free quote from Sano.',
    relatedSlugs: ['regular-cleaning', 'window-cleaning', 'carpet-upholstery'],
  },
  {
    slug: 'carpet-upholstery',
    name: 'Carpet & Upholstery Cleaning',
    shortDescription: 'Revive your carpets and soft furnishings with a professional clean.',
    description: 'Carpets and upholstery trap dust, allergens, and odours over time. Our professional equipment extracts deep-set dirt and leaves fabrics looking and smelling fresh.',
    heroImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80',
    includes: [
      'Pre-treatment of stains and high-traffic areas',
      'Hot water extraction (steam cleaning)',
      'Deodorising treatment',
      'Sofa and armchair deep clean',
      'Mattress cleaning available on request',
      'Quick-dry process — dry in 2–4 hours',
    ],
    fromPrice: 150,
    metaDescription: 'Carpet and upholstery cleaning in Auckland from $150. Steam cleaning, stain removal, and deodorising. Dry in 2–4 hours. Free quote from Sano Cleaning.',
    relatedSlugs: ['regular-cleaning', 'deep-cleaning', 'end-of-tenancy'],
  },
  {
    slug: 'window-cleaning',
    name: 'Window Cleaning',
    shortDescription: 'Crystal-clear windows inside and out.',
    description: 'Streak-free windows make a huge difference to any home or business. Our window cleaning team handles residential and commercial properties across Auckland, including high windows.',
    heroImage: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&q=80',
    includes: [
      'Interior and exterior window cleaning',
      'Window frame and sill wiping',
      'Sliding door tracks cleaned',
      'Screen removal and cleaning',
      'Streak-free finish guaranteed',
      'High-reach windows (up to 3 storeys)',
    ],
    fromPrice: 100,
    metaDescription: 'Window cleaning in Auckland from $100. Interior and exterior, streak-free guaranteed. Residential and commercial. Get a free quote from Sano Cleaning.',
    relatedSlugs: ['regular-cleaning', 'commercial-cleaning', 'deep-cleaning'],
  },
  {
    slug: 'post-construction',
    name: 'Post-Construction Cleaning',
    shortDescription: "Builder's dust and debris cleared — ready to move in.",
    description: 'After a build or renovation, dust and debris are everywhere. Our post-construction cleaning team removes all traces of building work so your space is spotless and move-in ready.',
    heroImage: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=80',
    includes: [
      'Removal of construction dust from all surfaces',
      'Cleaning inside cabinets and new fitments',
      'Washing all windows, frames, and sills',
      'Vacuuming and mopping all floors',
      'Cleaning bathrooms and kitchen thoroughly',
      'Removing stickers and labels from fixtures',
      'Final inspection and touch-up',
    ],
    fromPrice: 400,
    metaDescription: "Post-construction cleaning in Auckland from $400. Builder's dust, debris, and residue removed. Move-in ready finish. Free quote from Sano Cleaning.",
    relatedSlugs: ['deep-cleaning', 'end-of-tenancy', 'window-cleaning'],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): Service[] {
  return slugs.map((slug) => getServiceBySlug(slug)).filter((s): s is Service => s !== undefined)
}
