import type { Service } from '@/types'

export const SERVICES: Service[] = [
  {
    slug: 'regular-cleaning',
    name: 'Regular House Cleaning',
    shortDescription: 'Keep your home consistently clean, tidy, and easy to live in. We take care of the day-to-day cleaning so things stay under control without you having to think about it.',
    description: 'We handle the day-to-day cleaning so your space stays fresh, tidy, and easy to live in. Each clean is done with care and attention to detail, not rushed.\n\nIdeal for weekly or fortnightly upkeep.',
    heroImage: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Dusting surfaces, shelves, and skirting boards',
      'Cleaning kitchen benchtops and appliance exteriors',
      'Cleaning and sanitising bathrooms and toilets',
      'Emptying bins throughout the home',
      'Making beds and tidying rooms',
      'Spot-cleaning windows and mirrors',
    ],
    metaDescription: 'Regular house cleaning in Auckland. Weekly or fortnightly visits by vetted, insured cleaners. Eco-friendly products. Get in touch for a tailored quote.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'window-cleaning'],
  },
  {
    slug: 'deep-cleaning',
    name: 'Deep Cleaning',
    shortDescription: 'A more thorough clean for when your space needs extra attention. We focus on the areas that build up over time and are often missed in day to day cleaning.',
    description: 'Our deep cleaning service goes beyond the regular routine, focusing on the areas that build up over time and are often missed in day to day cleaning. It\'s ideal for first time cleans, seasonal resets, moving in or out, or when things have simply got on top of you.\n\nWe take the time to get into the details. That means behind and under furniture where accessible, inside appliances like ovens and fridges, skirting boards, vents, light switches, and those harder to reach or easy to overlook areas.\n\nEvery deep clean is tailored to your space. We\'ll prioritise what matters most and make sure everything is brought back to a standard you can feel.',
    heroImage: '/images/deep-cleaning.jpg',
    cardImage: '/images/deep-cleaning.jpg',
    includes: [
      'Everything in our regular clean',
      'Inside oven and microwave cleaning',
      'Inside fridge cleaning',
      'Deep scrubbing of tile grout',
      'Cleaning inside cabinets and drawers',
      'Washing interior windows and tracks',
      'Wiping down all light switches and door handles',
      'Behind and under furniture vacuuming',
    ],
    metaDescription: 'Deep cleaning in Auckland. Top-to-bottom clean including oven, fridge, grout, and hidden areas. Fully insured. Get in touch for a tailored quote.',
    relatedSlugs: ['regular-cleaning', 'end-of-tenancy', 'post-construction'],
  },
  {
    slug: 'end-of-tenancy',
    name: 'End of Tenancy Cleaning',
    shortDescription: 'A thorough clean to leave the space in the right condition before moving out. We handle kitchens, bathrooms, and all the finishing details properly.',
    description: 'We take care of the full clean so you can focus on the move. Kitchens, bathrooms, living areas, and all the finishing details are handled properly.\n\nDesigned to help meet landlord and property manager expectations.',
    heroImage: '/images/end-of-tenancy.jpg',
    cardImage: '/images/end-of-tenancy.jpg',
    includes: [
      'Full deep clean of all rooms',
      'Oven, stovetop, and range hood cleaning',
      'Fridge and dishwasher cleaning',
      'Bathroom and toilet descaling',
      'All windows, tracks, and sills',
      'Carpet vacuuming (steam clean available as add-on)',
      'Walls spot-cleaned',
      'Garage and outdoor areas swept',
    ],
    metaDescription: 'End of tenancy cleaning in Auckland. Bond-back guaranteed clean. Thorough, fast, and fully insured. Get in touch for a tailored quote.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'post-construction'],
  },
  {
    slug: 'commercial-cleaning',
    name: 'Commercial & Office Cleaning',
    shortDescription: 'Reliable cleaning that keeps your workspace clean, consistent, and presentable. We work around your schedule to minimise disruption.',
    description: 'We work around your business to keep things clean, presentable, and easy to maintain for staff and clients.\n\nFlexible scheduling to suit your operations.',
    heroImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Desk and workstation wiping',
      'Kitchen and break room cleaning',
      'Bathroom and toilet sanitising',
      'Bin emptying and bag replacement',
      'Glass partition and window cleaning',
      'Reception and entrance area cleaning',
    ],
    metaDescription: 'Commercial cleaning in Auckland. Office, retail, and business cleaning after-hours. Vetted cleaners, flexible scheduling. Get in touch for a tailored quote.',
    relatedSlugs: ['regular-cleaning', 'window-cleaning', 'carpet-upholstery'],
  },
  {
    slug: 'carpet-upholstery',
    name: 'Carpet & Upholstery Cleaning',
    shortDescription: 'Removes built-up dirt, stains, and odours to refresh carpets and furniture. Ideal for high-traffic areas or general upkeep.',
    description: 'We remove built-up dirt, stains, and odours, leaving surfaces looking cleaner and feeling refreshed.\n\nGreat for high-traffic areas or general maintenance.',
    heroImage: '/images/carpet-upholstery.jpg',
    cardImage: '/images/carpet-upholstery.jpg',
    includes: [
      'Pre-treatment of stains and high-traffic areas',
      'Hot water extraction (steam cleaning)',
      'Deodorising treatment',
      'Sofa and armchair deep clean',
      'Mattress cleaning available on request',
      'Quick-dry process — dry in 2–4 hours',
    ],
    metaDescription: 'Carpet and upholstery cleaning in Auckland. Steam cleaning, stain removal, and deodorising. Dry in 2–4 hours. Get in touch for a tailored quote.',
    relatedSlugs: ['regular-cleaning', 'deep-cleaning', 'end-of-tenancy'],
  },
  {
    slug: 'window-cleaning',
    name: 'Window Cleaning',
    shortDescription: 'Clean, streak-free windows that lift the overall feel of your space. We take care of glass, frames, and sills for a proper finish.',
    description: 'We clean glass, frames, and sills to leave windows streak-free and properly finished.\n\nMakes a noticeable difference to the overall space.',
    heroImage: '/images/window-cleaning.jpg',
    cardImage: '/images/window-cleaning.jpg',
    includes: [
      'Interior and exterior window cleaning',
      'Window frame and sill wiping',
      'Sliding door tracks cleaned',
      'Screen removal and cleaning',
      'Streak-free finish guaranteed',
      'High-reach windows (up to 3 storeys)',
    ],
    metaDescription: 'Window cleaning in Auckland. Interior and exterior, streak-free guaranteed. Residential and commercial. Get in touch for a tailored quote.',
    relatedSlugs: ['regular-cleaning', 'commercial-cleaning', 'deep-cleaning'],
  },
  {
    slug: 'post-construction',
    name: 'Post-Construction Cleaning',
    shortDescription: 'We clear dust, debris, and residue after building or renovation work. The space is left clean, safe, and ready to use.',
    description: 'We clear dust, debris, and residue left behind after construction or renovation, so the space is clean, safe, and ready.\n\nIdeal before handover or moving in.',
    heroImage: '/images/post-construction.jpg',
    cardImage: '/images/post-construction.jpg',
    includes: [
      'Removal of construction dust from all surfaces',
      'Cleaning inside cabinets and new fitments',
      'Washing all windows, frames, and sills',
      'Vacuuming and mopping all floors',
      'Cleaning bathrooms and kitchen thoroughly',
      'Removing stickers and labels from fixtures',
      'Final inspection and touch-up',
    ],
    metaDescription: "Post-construction cleaning in Auckland. Builder's dust, debris, and residue removed. Move-in ready finish. Get in touch for a tailored quote.",
    relatedSlugs: ['deep-cleaning', 'end-of-tenancy', 'window-cleaning'],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): Service[] {
  return slugs.map((slug) => getServiceBySlug(slug)).filter((s): s is Service => s !== undefined)
}
