import type { Service } from '@/types'

export const SERVICES: Service[] = [
  {
    slug: 'regular-cleaning',
    name: 'Regular House Cleaning',
    shortDescription: 'A consistent home clean from a team you don\'t have to brief every week. Weekly or fortnightly visits, the same standard each time.',
    description: 'We handle the day-to-day cleaning so your home stays where you want it without you having to think about it. The same team comes back week after week, briefed on what matters to you, with the standard checked by us.\n\nIdeal for weekly or fortnightly upkeep.',
    heroImage: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Dusting surfaces, shelves, and skirting boards',
      'Cleaning kitchen benchtops and appliance exteriors',
      'Cleaning and sanitising bathrooms and toilets',
      'Emptying bins throughout the home',
      'Making beds and tidying rooms',
      'Spot-cleaning windows and mirrors',
    ],
    metaDescription: 'Regular house cleaning in Auckland. Weekly or fortnightly visits by a consistent team, vetted and insured. The same standard every time. Free quote.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'window-cleaning'],
  },
  {
    slug: 'deep-cleaning',
    name: 'Deep Cleaning',
    shortDescription: 'A proper reset for spaces that need more than a regular clean. Ovens, fridges, behind furniture, skirting boards, vents, and the harder-to-reach corners.',
    description: 'Our deep cleaning service goes beyond the regular routine. We work into the areas that build up over time and get missed in day-to-day cleaning. Ideal for first-time cleans, seasonal resets, moving in or out, or when things have got on top of you.\n\nWe take the time to get into the details: behind and under furniture where accessible, inside appliances like ovens and fridges, skirting boards, vents, light switches, and the harder-to-reach corners.\n\nEvery deep clean is tailored to your space. We prioritise what matters most and bring everything back to a standard you can feel.',
    heroImage: '/images/deep-cleaning.jpg',
    cardImage: '/images/deep-cleaning.jpg',
    includes: [
      'Everything in our regular clean',
      'Inside oven and microwave cleaning',
      'Inside fridge cleaning',
      'Deep scrubbing of tile grout',
      'Cleaning inside cabinets and drawers',
      'Washing interior windows and tracks',
      'Wiping down all light switches and door handles',
      'Behind and under furniture vacuuming',
    ],
    metaDescription: 'Deep cleaning in Auckland. A proper reset: ovens, fridges, skirting, grout, and the corners a regular clean misses. Fully insured. Free quote.',
    relatedSlugs: ['regular-cleaning', 'end-of-tenancy', 'post-construction'],
  },
  {
    slug: 'end-of-tenancy',
    name: 'End of Tenancy Cleaning',
    shortDescription: 'A bond-ready clean to hand over with confidence. We focus on what landlords and property managers look for: kitchens, bathrooms, sills, tracks, and overlooked corners.',
    description: 'We clean the property to a bond-ready standard, designed to maximise your chance of bond recovery. Final decisions sit with the landlord or agency, but we stand behind the quality of our cleaning work and we\'ll come back to fix anything we\'ve missed where reasonable.',
    heroImage: '/images/end-of-tenancy.jpg',
    cardImage: '/images/end-of-tenancy.jpg',
    includes: [
      'Full deep clean of all rooms',
      'Oven, stovetop, and range hood cleaning',
      'Fridge and dishwasher cleaning',
      'Bathroom and toilet descaling',
      'All windows, tracks, and sills',
      'Carpet vacuuming (steam clean available as add-on)',
      'Walls spot-cleaned',
      'Garage and outdoor areas swept',
    ],
    metaDescription: 'End of tenancy cleaning in Auckland. A bond-ready clean designed to maximise your chance of bond recovery. Thorough and fully insured. Free quote.',
    relatedSlugs: ['deep-cleaning', 'carpet-upholstery', 'post-construction'],
  },
  {
    slug: 'commercial-cleaning',
    name: 'Commercial & Office Cleaning',
    shortDescription: 'Reliable commercial cleaning you don\'t have to chase. A consistent team, a schedule that fits your operations, and a direct line if something needs sorting.',
    description: 'We work around your business to keep things clean, presentable, and easy to maintain for staff and clients. Your space gets a consistent team, with the standard checked by us, so you\'re not the one flagging things.\n\nFlexible scheduling to suit your operations.',
    heroImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1600&q=80',
    cardImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80',
    includes: [
      'Vacuuming and mopping all floors',
      'Desk and workstation wiping',
      'Kitchen and break room cleaning',
      'Bathroom and toilet sanitising',
      'Bin emptying and bag replacement',
      'Glass partition and window cleaning',
      'Reception and entrance area cleaning',
    ],
    metaDescription: 'Commercial cleaning in Auckland. Reliable, consistent service that doesn\'t need chasing. A direct line if something needs sorting. Free quote.',
    relatedSlugs: ['regular-cleaning', 'window-cleaning', 'carpet-upholstery'],
  },
  {
    slug: 'carpet-upholstery',
    name: 'Carpet & Upholstery Cleaning',
    shortDescription: 'Cleaner carpets and fresher rooms. Built-up dirt, pet odours, and stains worked through with proper extraction and care for the material.',
    description: 'We work through built-up dirt with proper extraction, treat stains and odours with attention, and choose products suited to the material so colours and fabrics aren\'t compromised. Some marks come fully out, some don\'t, and we\'ll tell you up front what to expect.\n\nGreat for high-traffic areas, pet households, or general maintenance.',
    heroImage: '/images/carpet-upholstery.jpg',
    cardImage: '/images/carpet-upholstery.jpg',
    includes: [
      'Pre-treatment of stains and high-traffic areas',
      'Hot water extraction (steam cleaning)',
      'Deodorising treatment',
      'Sofa and armchair deep clean',
      'Mattress cleaning available on request',
      'Quick-dry process — dry in 2–4 hours',
    ],
    metaDescription: 'Carpet and upholstery cleaning in Auckland. Built-up dirt, pet odours, and stains worked through with proper extraction. Dry in 2 to 4 hours. Free quote.',
    relatedSlugs: ['regular-cleaning', 'deep-cleaning', 'end-of-tenancy'],
  },
  {
    slug: 'window-cleaning',
    name: 'Window Cleaning',
    shortDescription: 'Streak-free glass, frames and sills included. Interior and exterior, residential and commercial.',
    description: 'We clean each window with care: streak-free glass, frames wiped down, sills and tracks cleared of built-up dirt and debris.\n\nInterior and exterior, residential and commercial. The finish is consistent across the whole property.',
    heroImage: '/images/window-cleaning.jpg',
    cardImage: '/images/window-cleaning.jpg',
    includes: [
      'Interior and exterior window cleaning',
      'Window frame and sill wiping',
      'Sliding door tracks cleaned',
      'Screen removal and cleaning',
      'Streak-free finish guaranteed',
      'High-reach windows (up to 3 storeys)',
    ],
    metaDescription: 'Window cleaning in Auckland. Streak-free glass, frames, and sills included. Interior and exterior, residential and commercial. Free quote.',
    relatedSlugs: ['regular-cleaning', 'commercial-cleaning', 'deep-cleaning'],
  },
  {
    slug: 'post-construction',
    name: 'Post-Construction Cleaning',
    shortDescription: 'A handover-ready finish after building or renovation. Builder\'s dust, residue, and finishing-trade debris cleared so the space is ready to use.',
    description: 'We clear builder\'s dust from every surface, including sills, tracks, fittings, inside cabinets and drawers, light switches, and vents. We also remove residue, stickers, and finishing-trade debris that\'s been left behind.\n\nThe space is left clean, safe, and ready to hand over or move into.',
    heroImage: '/images/post-construction.jpg',
    cardImage: '/images/post-construction.jpg',
    includes: [
      'Removal of construction dust from all surfaces',
      'Cleaning inside cabinets and new fitments',
      'Washing all windows, frames, and sills',
      'Vacuuming and mopping all floors',
      'Cleaning bathrooms and kitchen thoroughly',
      'Removing stickers and labels from fixtures',
      'Final inspection and touch-up',
    ],
    metaDescription: "Post-construction cleaning in Auckland. Builder's dust, residue, and finishing-trade debris cleared. A handover-ready finish. Free quote.",
    relatedSlugs: ['deep-cleaning', 'end-of-tenancy', 'window-cleaning'],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return SERVICES.find((s) => s.slug === slug)
}

export function getRelatedServices(slugs: string[]): Service[] {
  return slugs.map((slug) => getServiceBySlug(slug)).filter((s): s is Service => s !== undefined)
}
