// Sano 125-Point Property Reset Checklist
//
// DRAFT CONTENT — Phase B scaffold only.
// Authored from scratch for Phase B visual review. Final item text, item
// ordering and item counts MUST come from Sano's own source DOCX
// ("Sano Property Reset Checklist") before this file is integrated into
// /services/end-of-tenancy. The `pointCountLabel` is editorial and stays
// "125-Point" even while drafted items are below 125.
//
// Originality boundary: this file MUST NOT derive items, room names,
// ordering, or wording from the Enhanced Cleaning reference documents
// at F:\Sano\20-Content\Sano Cleaning Checklist\. Source content only
// from Sano's own DOCX.
//
// Category structure: 10 categories with the approved Phase B v4
// item-count distribution to total exactly 125 items:
//   Living Areas 15 · Dining Areas 10 · Bedrooms 15 · Office/Study 10 ·
//   Kitchen 20 · Bathrooms 17 · Laundry 10 · Windows 10 · Floors 10 ·
//   Final Inspection 8

import type { Checklist } from '@/types/checklist'

export const SANO_125_POINT_PROPERTY_RESET: Checklist = {
  slug: 'sano-125-point-property-reset',
  name: 'Sano 125-Point Property Reset Checklist',
  shortName: 'Property Reset',
  pointCountLabel: '125-Point',
  isDraft: true,
  rooms: [
    {
      slug: 'living-areas',
      name: 'Living Areas',
      icon: 'Sofa',
      items: [
        { text: 'Cobwebs cleared throughout' },
        { text: 'Surfaces dusted' },
        { text: 'Switches and power-point faces wiped' },
        { text: 'Door handles wiped' },
        { text: 'Doors wiped both sides' },
        { text: 'Door frames detailed' },
        { text: 'Skirting boards cleaned by hand' },
        { text: 'Internal windows cleaned' },
        { text: 'Window sills wiped' },
        { text: 'Window tracks cleaned' },
        { text: 'Sliding door glass cleaned' },
        { text: 'Sliding door tracks cleaned' },
        { text: 'Carpets vacuumed including edges' },
        { text: 'Hard floors mopped' },
        { text: 'Ceiling fans dusted where reachable' },
      ],
    },
    {
      slug: 'dining-areas',
      name: 'Dining Areas',
      icon: 'UtensilsCrossed',
      items: [
        { text: 'Cobwebs cleared' },
        { text: 'Surfaces dusted' },
        { text: 'Switches and power-point faces wiped' },
        { text: 'Door handles wiped' },
        { text: 'Skirting boards cleaned' },
        { text: 'Window sills and tracks cleaned' },
        { text: 'Internal windows cleaned' },
        { text: 'Pendant lights dusted' },
        { text: 'Floors vacuumed including edges' },
        { text: 'Hard floors mopped' },
      ],
    },
    {
      slug: 'bedrooms',
      name: 'Bedrooms',
      icon: 'BedDouble',
      items: [
        { text: 'Cobwebs cleared' },
        { text: 'Light fittings dusted' },
        { text: 'Wardrobes cleaned inside and out' },
        { text: 'Wardrobe shelves wiped' },
        { text: 'Wardrobe rails wiped' },
        { text: 'Switches and power-point faces wiped' },
        { text: 'Door handles wiped' },
        { text: 'Doors wiped both sides' },
        { text: 'Door frames detailed' },
        { text: 'Skirting boards cleaned by hand' },
        { text: 'Window sills and tracks cleaned' },
        { text: 'Internal windows cleaned' },
        { text: 'Mirrors cleaned' },
        { text: 'Carpets vacuumed including edges' },
        { text: 'Hard floors mopped' },
      ],
    },
    {
      slug: 'office-study',
      name: 'Office / Study',
      icon: 'Briefcase',
      items: [
        { text: 'Cobwebs cleared' },
        { text: 'Surfaces dusted' },
        { text: 'Shelves wiped' },
        { text: 'Switches and power-point faces wiped' },
        { text: 'Door handles wiped' },
        { text: 'Door frames detailed' },
        { text: 'Skirting boards cleaned' },
        { text: 'Window sills and tracks cleaned' },
        { text: 'Internal windows cleaned' },
        { text: 'Floors vacuumed and mopped' },
      ],
    },
    {
      slug: 'kitchen',
      name: 'Kitchen',
      icon: 'ChefHat',
      items: [
        { text: 'Inside oven cleaned' },
        { text: 'Oven racks and door glass cleaned' },
        { text: 'Stovetop and knobs cleaned' },
        { text: 'Splashback cleaned' },
        { text: 'Rangehood interior and filters degreased' },
        { text: 'Inside microwave cleaned' },
        { text: 'Inside fridge cleaned', note: 'To be emptied and disconnected first.' },
        { text: 'Fridge exterior and seals wiped' },
        { text: 'Dishwasher exterior wiped' },
        { text: 'Inside cabinets and drawers cleaned' },
        { text: 'Cabinet fronts and handles wiped' },
        { text: 'Bench tops wiped down' },
        { text: 'Sink and tapware de-scaled' },
        { text: 'Pantry shelves wiped', note: 'When empty.' },
        { text: 'Cupboard undersides cleaned' },
        { text: 'Light fittings dusted' },
        { text: 'Switches and power-point faces wiped' },
        { text: 'Skirting boards cleaned' },
        { text: 'Floors vacuumed' },
        { text: 'Floors mopped including edges' },
      ],
    },
    {
      slug: 'bathrooms',
      name: 'Bathrooms',
      icon: 'Bath',
      items: [
        { text: 'Shower screens de-scaled' },
        { text: 'Shower frames and seals wiped' },
        { text: 'Shower walls and base scrubbed' },
        { text: 'Bath cleaned inside and out' },
        { text: 'Tile grout treated for build-up' },
        { text: 'Toilet cleaned and sanitised' },
        { text: 'Toilet base, behind and pan area detailed' },
        { text: 'Vanity and basin polished' },
        { text: 'Tapware polished' },
        { text: 'Mirrors cleaned' },
        { text: 'Inside cabinets cleaned' },
        { text: 'Cabinet fronts wiped' },
        { text: 'Extractor fan vent cover cleaned' },
        { text: 'Towel rails wiped' },
        { text: 'Light switches wiped' },
        { text: 'Skirting boards wiped' },
        { text: 'Floors mopped including edges' },
      ],
    },
    {
      slug: 'laundry',
      name: 'Laundry',
      icon: 'WashingMachine',
      items: [
        { text: 'Tub and tapware polished' },
        { text: 'Inside cabinets cleaned' },
        { text: 'Cabinet fronts wiped' },
        { text: 'Washer interior and seal cleaned' },
        { text: 'Washer exterior wiped' },
        { text: 'Dryer lint trap cleared' },
        { text: 'Dryer exterior wiped' },
        { text: 'Switches and door handles wiped' },
        { text: 'Skirting boards wiped' },
        { text: 'Floors mopped including edges' },
      ],
    },
    {
      slug: 'windows',
      name: 'Windows',
      icon: 'PanelTop',
      items: [
        { text: 'Interior glass cleaned in all rooms' },
        { text: 'Sills wiped in all rooms' },
        { text: 'Window tracks cleaned in all rooms' },
        { text: 'Window frames wiped in all rooms' },
        { text: 'Sliding door glass cleaned (internal)' },
        { text: 'Sliding door tracks cleaned' },
        { text: 'Glass door panels polished' },
        { text: 'Mirrors throughout polished' },
        { text: 'Internal partition glass cleaned' },
        { text: 'Ground-floor exterior windows cleaned', note: 'Where included in agreed scope.' },
      ],
    },
    {
      slug: 'floors',
      name: 'Floors',
      icon: 'PaintRoller',
      items: [
        { text: 'Carpets vacuumed in all rooms' },
        { text: 'Carpet edges vacuumed' },
        { text: 'Hard floors swept' },
        { text: 'Hard floors mopped' },
        { text: 'Floor edges and corners detailed' },
        { text: 'Skirting boards cleaned along all floors' },
        { text: 'Stair treads vacuumed' },
        { text: 'Stair risers wiped' },
        { text: 'Landing floors vacuumed and mopped' },
        { text: 'Floor vents wiped where reachable' },
      ],
    },
    {
      slug: 'final-inspection',
      name: 'Final Inspection',
      icon: 'BadgeCheck',
      items: [
        { text: 'High-touch points re-checked throughout' },
        { text: 'Mirrors and glass re-checked' },
        { text: 'Entry door and frame detailed' },
        { text: 'Letterbox and door number wiped' },
        { text: 'Cobwebs re-checked at entry' },
        { text: 'Final detail walk-through completed' },
        { text: 'Photo evidence prepared', note: 'On request.' },
        { text: 'Property ready for handover sign-off' },
      ],
    },
  ],
}
