// Sano 125-Point Property Reset Checklist
//
// DRAFT CONTENT — Phase B preview.
// Item wording supplied verbatim by the user on 2026-05-20 for visual
// review on the preview route. This file MUST NOT be integrated into
// /services/end-of-tenancy until the wording is operationally and
// legally reviewed (see report attached to the commit that landed this
// content). `isDraft: true` is the gating signal.

import type { Checklist } from '@/types/checklist'

export const SANO_125_POINT_PROPERTY_RESET: Checklist = {
  slug: 'sano-125-point-property-reset',
  name: 'Sano 125-Point Property Reset Checklist',
  shortName: 'Property Reset',
  pointCountLabel: '125-Point',
  isDraft: true,
  rooms: [
    {
      slug: 'living-areas',
      name: 'Living Areas',
      icon: 'Sofa',
      items: [
        { text: 'Cobwebs cleared from reachable ceilings and corners' },
        { text: 'Cornices and ceiling edges dusted where reachable' },
        { text: 'Light fitting exteriors wiped' },
        { text: 'Clean light switches and power points' },
        { text: 'Clean doors (front and back)' },
        { text: 'Clean door frames' },
        { text: 'Clean door handles and locks' },
        { text: 'Clean skirting boards' },
        { text: 'Dust and wipe all surfaces' },
        { text: 'Clean internal windows' },
        { text: 'Clean window frames and sills' },
        { text: 'Clean sliding door glass' },
        { text: 'Clean sliding door tracks' },
        { text: 'Vacuum floors (edges and corners)' },
        { text: 'Hard floors mopped' },
      ],
    },
    {
      slug: 'dining-areas',
      name: 'Dining Areas',
      icon: 'UtensilsCrossed',
      items: [
        { text: 'Remove cobwebs' },
        { text: 'Dust cornices and edges' },
        { text: 'Clean light switches and power points' },
        { text: 'Clean doors and frames' },
        { text: 'Clean skirting boards' },
        { text: 'Dust and wipe surfaces' },
        { text: 'Clean internal glass' },
        { text: 'Clean window frames and sills' },
        { text: 'Vacuum floors thoroughly' },
        { text: 'Hard floors mopped' },
        { text: 'Spot clean walls' },
        { text: 'Vent covers wiped where safely reachable' },
      ],
    },
    {
      slug: 'bedrooms',
      name: 'Bedrooms',
      icon: 'BedDouble',
      items: [
        { text: 'Remove cobwebs' },
        { text: 'Dust cornices and edges' },
        { text: 'Clean light switches and power points' },
        { text: 'Clean doors and frames' },
        { text: 'Clean skirting boards' },
        { text: 'Dust and wipe all surfaces' },
        { text: 'Clean inside wardrobes' },
        { text: 'Clean wardrobe shelves' },
        { text: 'Clean wardrobe drawers' },
        { text: 'Clean mirrors' },
        { text: 'Clean internal windows' },
        { text: 'Clean window frames and sills' },
        { text: 'Vacuum floors thoroughly' },
        { text: 'Hard floors mopped where applicable' },
        { text: 'Spot clean walls' },
      ],
    },
    {
      slug: 'office-study',
      name: 'Office / Study',
      icon: 'Briefcase',
      items: [
        { text: 'Remove cobwebs' },
        { text: 'Dust cornices and edges' },
        { text: 'Clean light switches and power points' },
        { text: 'Clean doors and frames' },
        { text: 'Clean skirting boards' },
        { text: 'Dust and wipe all surfaces' },
        { text: 'Clean cupboards and drawers' },
        { text: 'Clean shelves' },
        { text: 'Clean internal glass and mirrors' },
        { text: 'Vacuum floors' },
        { text: 'Hard floors mopped' },
        { text: 'Vent covers wiped where safely reachable' },
      ],
    },
    {
      slug: 'kitchen',
      name: 'Kitchen',
      icon: 'ChefHat',
      items: [
        { text: 'Clean inside cupboards' },
        { text: 'Clean cupboard doors (external)' },
        { text: 'Clean drawers (internal and external)' },
        { text: 'Clean benchtops' },
        { text: 'Clean splashback' },
        { text: 'Clean sink and basin' },
        { text: 'Clean taps and polish fittings' },
        { text: 'Clean stovetop surface' },
        { text: 'Clean burners and knobs' },
        { text: 'Clean rangehood exterior' },
        { text: 'Clean rangehood filters' },
        { text: 'Kickboards wiped' },
        { text: 'Cupboard handles wiped' },
        { text: 'Appliance surrounds wiped' },
        { text: 'Clean microwave (internal and external)' },
        { text: 'Clean dishwasher (internal)' },
        { text: 'Clean dishwasher exterior' },
        { text: 'Fridge exterior wiped' },
        { text: 'Grease build-up reduced' },
        { text: 'Hard floors mopped' },
      ],
    },
    {
      slug: 'bathrooms',
      name: 'Bathrooms',
      icon: 'Bath',
      items: [
        { text: 'Clean toilet pan' },
        { text: 'Clean toilet seat and lid' },
        { text: 'Clean toilet base and exterior' },
        { text: 'Clean shower tiles' },
        { text: 'Clean grout lines' },
        { text: 'Clean shower glass' },
        { text: 'Clean shower tracks' },
        { text: 'Soap scum reduced' },
        { text: 'Visible surface mould treated where practical' },
        { text: 'Clean bath' },
        { text: 'Clean vanity' },
        { text: 'Clean basin' },
        { text: 'Clean taps and polish fittings' },
        { text: 'Clean mirrors' },
        { text: 'Clean cupboards and drawers' },
        { text: 'Exhaust fan covers wiped where safely reachable' },
        { text: 'Hard floors mopped' },
        { text: 'Spot clean walls' },
      ],
    },
    {
      slug: 'laundry',
      name: 'Laundry',
      icon: 'WashingMachine',
      items: [
        { text: 'Clean laundry sink' },
        { text: 'Clean taps and fittings' },
        { text: 'Clean cupboards (internal and external)' },
        { text: 'Clean drawers' },
        { text: 'Clean benchtops' },
        { text: 'Clean splashback' },
        { text: 'Clean light switches and power points' },
        { text: 'Clean doors and frames' },
        { text: 'Remove lint and dust buildup' },
        { text: 'Clean skirting boards' },
        { text: 'Hard floors mopped' },
        { text: 'Vent covers wiped where safely reachable' },
      ],
    },
    {
      slug: 'windows',
      name: 'Windows',
      icon: 'PanelTop',
      items: [
        { text: 'Clean internal window glass' },
        { text: 'Interior window glass detailed' },
        { text: 'Clean window frames' },
        { text: 'Clean window sills' },
        { text: 'Clean window tracks' },
        { text: 'Dirt build-up reduced on frames' },
        { text: 'Internal sliding door glass cleaned' },
        { text: 'Internal sliding door tracks cleaned' },
        { text: 'Clean flyscreens (dust/wipe)' },
        { text: 'Spot clean surrounding areas' },
      ],
    },
    {
      slug: 'floors',
      name: 'Floors',
      icon: 'PaintRoller',
      items: [
        { text: 'Vacuum all carpeted areas' },
        { text: 'Edge vacuum along skirting boards' },
        { text: 'Vacuum corners and hard-to-reach areas' },
        { text: 'All hard floors mopped' },
        { text: 'Detail mop edges' },
        { text: 'Remove minor floor marks where possible' },
      ],
    },
    {
      slug: 'final-inspection',
      name: 'Final Inspection',
      icon: 'BadgeCheck',
      items: [
        { text: 'Full property walkthrough' },
        { text: 'Check all rooms completed' },
        { text: 'Final missed areas checked' },
        { text: 'Visible rubbish bagged for bins' },
        { text: 'Final presentation check for handover' },
      ],
    },
  ],
}
