// Sano 100-Point Home Clean Checklist
//
// DRAFT CONTENT — Phase B preview.
// Item wording supplied verbatim by the user on 2026-05-20 for visual
// review on the preview route. This file MUST NOT be integrated into
// /services/regular-cleaning until the wording is operationally and
// legally reviewed (see report attached to the commit that landed this
// content). `isDraft: true` is the gating signal.

import type { Checklist } from '@/types/checklist'

export const SANO_100_POINT_HOME_CLEAN: Checklist = {
  slug: 'sano-100-point-home-clean',
  name: 'Sano 100-Point Home Clean Checklist',
  shortName: 'Home Clean Standard',
  pointCountLabel: '100-Point',
  isDraft: true,
  rooms: [
    {
      slug: 'bedrooms',
      name: 'Bedrooms',
      icon: 'BedDouble',
      items: [
        { text: 'Furniture dusted' },
        { text: 'Ceiling fans dusted' },
        { text: 'Window sills dusted' },
        { text: 'Lamps dusted' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Bedside tables cleaned' },
        { text: 'Mirrors cleaned' },
        { text: 'Wall hangings dusted' },
        { text: 'General straighten-up' },
        { text: 'Skirting boards dusted' },
        { text: 'Doors spot cleaned' },
        { text: 'Door frames dusted' },
        { text: 'Cobwebs removed' },
        { text: 'Walls spot cleaned' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'bathrooms',
      name: 'Bathrooms',
      icon: 'Bath',
      items: [
        { text: 'Mirrors cleaned' },
        { text: 'Sinks cleaned' },
        { text: 'Vanity cleaned' },
        { text: 'Cupboard faces cleaned' },
        { text: 'Skirtings dusted' },
        { text: 'Toilet cleaned inside and out' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Shower and bathtub cleaned' },
        { text: 'Towel rack dusted' },
        { text: 'Doors spot cleaned' },
        { text: 'Door frames dusted' },
        { text: 'Soap dispensers & toothbrush holders cleaned' },
        { text: 'Window sills dusted' },
        { text: 'Cobwebs removed' },
        { text: 'Garbage disposed' },
        { text: 'Walls spot cleaned' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'kitchen',
      name: 'Kitchen',
      icon: 'ChefHat',
      items: [
        { text: 'Fridge exterior spot cleaned' },
        { text: 'Range hood cleaned & polished' },
        { text: 'Splashback cleaned' },
        { text: 'Cooktop cleaned & polished' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Oven exterior cleaned' },
        { text: 'Dishwasher exterior cleaned' },
        { text: 'Microwave cleaned inside and out' },
        { text: 'Sink cleaned & polished' },
        { text: 'Sink window cleaned inside' },
        { text: 'Light fixtures dusted' },
        { text: 'Walls spot cleaned' },
        { text: 'Skirting boards cleaned' },
        { text: 'Benchtops cleaned' },
        { text: 'Cupboard faces cleaned' },
        { text: 'Garbage disposed' },
        { text: 'Cobwebs removed' },
        { text: 'Doors spot cleaned' },
        { text: 'Door frames dusted' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'dining-room',
      name: 'Dining Room',
      icon: 'UtensilsCrossed',
      items: [
        { text: 'Furniture dusted' },
        { text: 'Wall hangings dusted' },
        { text: 'Light fixtures dusted' },
        { text: 'Window sills dusted' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Dining table cleaned' },
        { text: 'Skirting boards dusted' },
        { text: 'Doors spot cleaned' },
        { text: 'Door frames dusted' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'living-areas',
      name: 'Living Areas',
      icon: 'Sofa',
      items: [
        { text: 'General straighten up' },
        { text: 'Mirrors cleaned' },
        { text: 'Light fixtures dusted' },
        { text: 'Coffee tables cleaned' },
        { text: 'Wall hangings dusted' },
        { text: 'Furniture dusted' },
        { text: 'Walls spot cleaned' },
        { text: 'Skirting boards dusted' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Couch vacuumed' },
        { text: 'Doors spot cleaned' },
        { text: 'Door frames dusted' },
        { text: 'Ceiling fans dusted' },
        { text: 'Window sills dusted' },
        { text: 'Cobwebs removed' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'office-study',
      name: 'Office / Study',
      icon: 'Briefcase',
      items: [
        { text: 'Desks cleaned' },
        { text: 'Furniture dusted' },
        { text: 'Wall hangings dusted' },
        { text: 'Skirting boards dusted' },
        { text: 'Door handles & key touchpoints disinfected' },
        { text: 'Cobwebs removed' },
        { text: 'Ceiling fans dusted' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'laundry',
      name: 'Laundry',
      icon: 'WashingMachine',
      items: [
        { text: 'Appliance exteriors cleaned' },
        { text: 'Bench cleaned' },
        { text: 'Cupboard faces cleaned' },
        { text: 'Sink cleaned' },
        { text: 'Walls spot cleaned' },
        { text: 'Door handles & key touch points disinfected' },
        { text: 'Skirting boards dusted' },
        { text: 'Doors spot cleaned' },
        { text: 'Cobwebs removed' },
        { text: 'Door frames dusted' },
        { text: 'Floors vacuumed/mopped' },
      ],
    },
    {
      slug: 'other',
      name: 'Other',
      icon: 'Sparkles',
      items: [
        { text: 'Light dusting throughout home' },
        { text: 'All floors vacuumed/mopped' },
        { text: 'Mould removal in wet areas (excluding inside silicone)' },
      ],
    },
  ],
}
