// Executive Summary — green opener + 4–5 tailored body paragraphs on
// the left, full-height commercial-interior image on the right.
// Right-column image runs from just under the header to the footer
// line, matching the cover-page proportion / treatment.
//
// Phase 3 — content is now generated by buildExecutiveSummary() so
// each proposal reads as a tailored document (site-aware paragraphs
// instead of a single operator-written blurb). The legacy
// payload.executiveSummary string is kept as a fallback only when
// the builder would otherwise have produced nothing useful.

import { ProposalLayout } from './ProposalLayout'
import type { ProposalTemplatePayload } from '@/lib/proposals/buildProposalPayload'
import { buildExecutiveSummary } from '@/lib/proposals/content-builders'

// Locked side image for this page only. Drop the file into
// public/images/ — keep the path stable.
const SIDE_IMAGE = '/images/executive-summary.jpg'

export function ExecutiveSummaryPage({
  payload,
  pageNumber,
  totalPages,
}: {
  payload: ProposalTemplatePayload
  pageNumber: number
  totalPages: number
}) {
  const { opener, body } = buildExecutiveSummary(payload)

  return (
    <ProposalLayout
      headerTitle="Executive summary"
      pageNumber={pageNumber}
      totalPages={totalPages}
      contact={payload.contact}
    >
      <div className="proposal-content proposal-content--exec">
        <div className="proposal-exec-grid">
          <div className="proposal-exec-grid__copy">
            <p className="proposal-exec-opener">{opener}</p>
            {body.map((para, i) => (
              <p
                key={i}
                className="proposal-lead"
                style={i === body.length - 1 ? { marginBottom: 0 } : undefined}
              >
                {para}
              </p>
            ))}
          </div>
          <div
            className="proposal-exec-grid__image"
            style={{ backgroundImage: `url(${SIDE_IMAGE})` }}
            aria-hidden
          />
        </div>
      </div>
    </ProposalLayout>
  )
}
