// Pricing Summary — centered bordered card showing the hero monthly
// fee + GST/per-month suffixes, followed by a calm pricing-basis
// paragraph, a "What's included" checklist, and a closing note on
// invoicing terms.
//
// Phase 3.1 — copy is generated by buildPricingSummaryText(payload).
// Price + suffixes remain settings-driven and are NOT recalculated
// here — content only.

import { ProposalLayout } from './ProposalLayout'
import type { ProposalTemplatePayload } from '@/lib/proposals/buildProposalPayload'
import { buildPricingSummaryText } from '@/lib/proposals/content-builders'

export function PricingSummaryPage({
  payload,
  pageNumber,
  totalPages,
}: {
  payload: ProposalTemplatePayload
  pageNumber: number
  totalPages: number
}) {
  const { intro, inclusionsNote, positioningNote, included, closingNote } = buildPricingSummaryText(payload)

  // One-off quotes price a single visit, so the hero can't say
  // "Monthly service fee ... per month". The GST suffix still applies;
  // only the recurrence wording is suppressed.
  const oneOff = payload.siteContext.isOneOff
  const feeLabel = oneOff ? 'Total service fee' : 'Monthly service fee'
  const feeSuffix = oneOff ? '' : payload.monthlyFeeSuffix
  const feeNote = oneOff
    ? 'Based on the agreed scope for this clean.'
    : 'Based on agreed scope and service frequency.'

  return (
    <ProposalLayout
      headerTitle="Pricing summary"
      pageNumber={pageNumber}
      totalPages={totalPages}
      contact={payload.contact}
    >
      <div className="proposal-content">
        <div className="proposal-pricing-wrap">
          <div className="proposal-pricing-card">
            <div className="proposal-pricing-card__label">{feeLabel}</div>
            <div className="proposal-pricing-card__amount">{payload.monthlyServiceFee}</div>
            {payload.gstSuffix && (
              <div className="proposal-pricing-card__suffix">
                {payload.gstSuffix}
                {feeSuffix ? ` · ${feeSuffix}` : ''}
              </div>
            )}
            <div className="proposal-pricing-card__note">
              {feeNote}
            </div>
          </div>
        </div>

        <p className="proposal-pricing-basis">{intro}</p>
        <p className="proposal-pricing-basis">{inclusionsNote}</p>

        <div className="proposal-pricing-included">
          <div className="proposal-pricing-included__head">What&rsquo;s included</div>
          <ul className="proposal-pricing-included__list">
            {included.map((item, i) => (
              <li key={i} className="proposal-pricing-included__item">
                <svg className="proposal-pricing-included__check" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden>
                  <path d="M4.5 12.5l4.5 4.5L20 6.5" />
                </svg>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <p className="proposal-pricing-support proposal-pricing-support--accent">
          {positioningNote}
        </p>

        <p className="proposal-pricing-support">{closingNote}</p>
      </div>
    </ProposalLayout>
  )
}
