// Pricing Summary — centered bordered card showing the hero monthly
// fee + GST/per-month suffixes, followed by a short pricing-basis
// paragraph, a "What's included" checklist, and a closing note on
// invoicing terms.
//
// Phase 3 — the copy (intro paragraph, bullet list, closing note) is
// generated by buildPricingSummaryText(payload) so each proposal
// reads as a tailored document. The price figure + suffixes remain
// settings-driven and are NOT recalculated here — content only.

import { ProposalLayout } from './ProposalLayout'
import type { ProposalTemplatePayload } from '@/lib/proposals/buildProposalPayload'
import { buildPricingSummaryText } from '@/lib/proposals/content-builders'

export function PricingSummaryPage({
  payload,
  pageNumber,
  totalPages,
}: {
  payload: ProposalTemplatePayload
  pageNumber: number
  totalPages: number
}) {
  const { intro, included, closingNote } = buildPricingSummaryText(payload)

  return (
    <ProposalLayout
      headerTitle="Pricing summary"
      pageNumber={pageNumber}
      totalPages={totalPages}
      contact={payload.contact}
    >
      <div className="proposal-content">
        <div className="proposal-pricing-wrap">
          <div className="proposal-pricing-card">
            <div className="proposal-pricing-card__label">Monthly service fee</div>
            <div className="proposal-pricing-card__amount">{payload.monthlyServiceFee}</div>
            {payload.gstSuffix && (
              <div className="proposal-pricing-card__suffix">
                {payload.gstSuffix}
                {payload.monthlyFeeSuffix ? ` · ${payload.monthlyFeeSuffix}` : ''}
              </div>
            )}
            <div className="proposal-pricing-card__note">
              Based on agreed scope and service frequency.
            </div>
          </div>
        </div>

        <p className="proposal-pricing-basis">{intro}</p>

        <div className="proposal-pricing-included">
          <div className="proposal-pricing-included__head">What&rsquo;s included</div>
          <ul className="proposal-pricing-included__list">
            {included.map((item, i) => (
              <li key={i} className="proposal-pricing-included__item">
                <svg className="proposal-pricing-included__check" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden>
                  <path d="M4.5 12.5l4.5 4.5L20 6.5" />
                </svg>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <p className="proposal-pricing-support">
          {closingNote}
        </p>

        {payload.pricingNote && payload.pricingNote.trim() !== closingNote.trim() && (
          <p className="proposal-pricing-support">{payload.pricingNote}</p>
        )}
      </div>
    </ProposalLayout>
  )
}
