-- Sales leads seed — Auckland commercial research, 2026-07-05.
-- 58 leads: 15 law, 15 accounting, 14 architecture/engineering, 14 professional offices.
-- Ranks: A = named ops decision-maker + published direct channel (15),
--        B = named decision-maker, general channel (21), C = company only (22).
-- Every contact detail came from the company's own website or an industry
-- directory (NZIA/ACE/NZ Law Society/Meritas) — nothing invented. Where a
-- decision-maker's direct email is published, it is used as the send address.
-- Run AFTER 2026-07-05-sales-campaigns.sql. Run once (plain INSERTs).

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── LAW (15) ─────────────────────────────────────────────────────────────────
('Hesketh Henry','law','https://www.heskethhenry.co.nz','90-100','Level 14, HSBC Tower, 188 Quay Street, Auckland 1010','Kerry Browne','General Manager','kerry.browne@heskethhenry.co.nz','+64 9 375 8747','https://nz.linkedin.com/company/hesketh-henry','Research 2026-07-05','A','new','Single-office AKL firm est. 1865 - no national FM lock-in. GM owns finance/IT/HR/admin; direct email + DDI published on firm profile page. General: lawyers@heskethhenry.co.nz / +64 9 375 8700.'),
('Martelli McKegg','law','https://www.martellimckegg.co.nz','30-50','Level 20, HSBC Tower, 188 Quay Street, Auckland 1010','Franchelle Taylor','Practice Manager','franchelle.taylor@martellimckegg.co.nz','+64 9 300 7610','https://nz.linkedin.com/company/martelli-mckegg','Research 2026-07-05','A','new','Practice Manager (also board member) owns admin/finance/HR; direct email + DDI published. Same tower as Lowndes Jordan (L15) and McVeagh Fleming (L9) - one building, three targets. General: info@ / +64 9 379 7333.'),
('Jackson Russell','law','https://jacksonrussell.co.nz','20-50','Level 13, 41 Shortland Street, Auckland 1010','Evelina Novoselova','Business Services Manager','evelina.novoselova@jacksonrussell.co.nz','+64 9 300 6941','https://nz.linkedin.com/company/jackson-russell','Research 2026-07-05','A','new','175+ year old CBD firm, 8 partners. Business Services Manager explicitly handles supplier relationships - ideal cleaning-contract owner; direct email, DDI and mobile published. Same tower as Haigh Lyon (L19) - pair the outreach.'),
('McVeagh Fleming','law','https://www.mcveaghfleming.co.nz','100-150','Level 9, HSBC Tower, 188 Quay Street, Auckland 1010 (also Albany + Manukau)','Susan King','General Manager','sking@mcveaghfleming.co.nz','+64 9 306 6721','https://www.linkedin.com/company/mcveagh-fleming','Research 2026-07-05','A','new','THREE Auckland offices (CBD, Albany, Manukau) = multi-site opportunity; 140+ staff per own site. Inaugural GM runs day-to-day ops; direct email, DDI + mobile published.'),
('Brookfields Lawyers','law','https://brookfields.co.nz','40-50','Level 9, Tower One, 205 Queen Street, Auckland 1010','Debbie Lewis','Office Manager','lewis@brookfields.co.nz','+64 9 979 2148','https://nz.linkedin.com/company/brookfields-lawyers','Research 2026-07-05','A','new','~41 people on team page. Office Manager = natural cleaning buyer; direct email, DDI + mobile published on firm site. General: law@ / +64 9 379 9350.'),
('Glaister Keegan','law','https://www.glaisterkeegan.co.nz','70-80','Norfolk House, 18 High Street, Auckland 1010','Georgia Preston-Jones','Practice Manager','georgia.preston-jones@glaister.co.nz','+64 9 356 8227','https://nz.linkedin.com/company/glaister-keegan','Research 2026-07-05','A','new','HOT TIMING: formed Dec 2024 from Glaister Ennor + Keegan Alexander merger (14 partners, ~80 staff) - recently consolidated premises, supplier arrangements likely in flux. Practice Manager remit explicitly includes facilities.'),
('Queen City Law','law','https://www.queencitylaw.co.nz','20-30','Level 8, 19 Victoria Street West, Auckland Central 1010','Aimee Young','General Manager','aimee@qcl.co.nz','+64 9 970 8825','https://nz.linkedin.com/company/queen-city-law','Research 2026-07-05','A','new','24 people on team page. GM manages office systems/environment per her own bio; direct email + DDI published. General: law@ / +64 9 970 8810.'),
('Lowndes Jordan','law','https://www.lojo.co.nz','20-30','Level 15, HSBC Tower, 188 Quay Street, Auckland 1010','David White','General Manager','dhw@lojo.co.nz','+64 9 280 0349','https://nz.linkedin.com/company/lowndes-jordan','Research 2026-07-05','A','new','Niche commercial firm; GM is ex-COO of Southern Cross Travel Insurance; direct email, DDI + mobile published. Third target in the 188 Quay St tower.'),
('Smith and Partners Lawyers','law','https://www.smithpartners.co.nz','30-50','293 Lincoln Road, Henderson, Auckland 0610','Racheal Adlam','General Manager - Finance & Operations','racheal.adlam@smithpartners.co.nz','+64 9 837 6895','https://nz.linkedin.com/company/smithandpartnerslawyers','Research 2026-07-05','A','new','West Auckland flagship local firm, same Lincoln Rd site since 1992, 36 team profiles. GM Finance & Ops direct email + DDI published. Good West Auckland anchor-client fit. Near ICIB Henderson office.'),
('Simpson Western','law','https://www.simpsonwestern.co.nz','40-50','Level 4, Takapuna Finance Centre, 159 Hurstmere Road, Takapuna 0622','Lisa Bycroft','Practice Manager','hello@simpsonwestern.co.nz','+64 9 489 0732','https://www.linkedin.com/company/simpson-western','Research 2026-07-05','A','new','40-strong team, Takapuna since 1985. Practice Manager listed with published direct line (no email published - phone is her DDI). SAME BUILDING as Andersen NZ Takapuna office. North Shore cluster with Turner Hopkins + Davenports.'),
('Turner Hopkins','law','https://www.turnerhopkins.co.nz','30-40','Level 1, 1/7 The Strand, Takapuna, Auckland 0622','Helen White','General Manager','law@turnerhopkins.co.nz','+64 9 486 2169','https://nz.linkedin.com/company/turner-hopkins','Research 2026-07-05','B','new','100+ year old Takapuna firm, ~31 on team page. GM Helen White AND Office Manager Sue Williams-Warren both listed on people page - two named ops owners, general channels only.'),
('Haigh Lyon Lawyers','law','https://haighlyon.co.nz','30-40','Level 19, 41 Shortland Street, Auckland 1010','Robyn Purcell','Practice Manager','lawyers@haighlyon.co.nz','+64 9 306 0600','https://www.linkedin.com/company/haigh-lyon','Research 2026-07-05','B','new','~34 people; Practice Manager + Office Manager (Megan Grant) + Finance Manager all named on site, no direct contacts. Six floors above Jackson Russell at 41 Shortland St - pair the outreach.'),
('Wilson Harle','law','https://www.wilsonharle.com','20-30','64 Fort Street, Auckland 1010',NULL,NULL,'firm@wilsonharle.com','+64 9 915 5700','https://nz.linkedin.com/company/wilson-harle','Research 2026-07-05','C','new','Specialist litigation boutique, 19 lawyers on people page (support staff unlisted). No ops role named publicly.'),
('Davenports Law','law','https://www.davenportslaw.co.nz','25-35','Building 2, Level 1, 331 Rosedale Road, Albany, Auckland 0632',NULL,NULL,'reception@davenportslaw.co.nz','+64 9 915 4380','https://nz.linkedin.com/company/davenports-law','Research 2026-07-05','C','new','Albany trust/commercial firm, 25 on team page. MD Tammy McLeod is a lawyer not ops. Completes North Shore run with Simpson Western + Turner Hopkins.'),
('Wynyard Wood','law','https://www.wynyardwood.co.nz','10-30','Level 1, Wynyard Wood House, 60 Highbrook Drive, East Tamaki, Auckland 2013',NULL,NULL,'manager@wynyardwood.co.nz','+64 9 969 0126','https://nz.linkedin.com/company/wynyard-wood','Research 2026-07-05','C','new','130+ year old firm in its own named building at Highbrook Business Park. Published contact email is literally manager@ - lands with the right person by default. Smallest lead on list (4 partners). Same street as RSM + BDO East Tamaki.'),
-- ── ACCOUNTING (15) ──────────────────────────────────────────────────────────
('UHY Haines Norton (Auckland)','accounting','https://www.uhyhn.co.nz','50-100','22 Catherine Street, Henderson, Auckland 0612 (HQ; also CBD + Kumeu)','Yvonne Wood','Practice Manager & Operations','ywood@uhyhn.co.nz','+64 9 839 2185','https://nz.linkedin.com/company/uhy-haines-norton-advisers-limited','Research 2026-07-05','A','new','Practice Manager runs day-to-day operations; her own email + DDI published on Our People page. THREE Auckland sites (Henderson HQ, CBD Smith & Caughey Bldg, Kumeu) = multi-site potential. West Auckland HQ.'),
('PKF Withers Tsang','accounting','https://pkfwt.co.nz','20-50','Level 18, SAP Tower, 151 Queen Street, Auckland 1010','Nicki Richards','Chief Operations Officer','reception@pkfwt.co.nz','+64 9 376 8860','https://nz.linkedin.com/company/pkf-withers-tsang','Research 2026-07-05','B','new','COO publicly listed on Meet Us page - clear single ops owner for one CBD tower floor. Property-investor-focused CA firm.'),
('Walker Wayland Auckland','accounting','https://wwauckland.co.nz','20-50','Level 14, 88 Shortland Street, Auckland CBD 1010','Ariki Tane','Office Manager','admin@wwauckland.co.nz','+64 9 968 4440','https://www.linkedin.com/company/walker-wayland-auckland-limited','Research 2026-07-05','B','new','Office Manager named on team page; Kate Dudley (Director) also listed as Director of Practice Administration - two named ops owners, one CBD floor.'),
('BDO Auckland (East Tamaki + Takapuna)','accounting','https://www.bdo.nz','100+','Level 1, 60 Highbrook Drive, East Tamaki; Level 10, BDO Tower, 19 Como Street, Takapuna',NULL,NULL,NULL,'+64 9 379 2950','https://nz.linkedin.com/company/bdo-new-zealand','Research 2026-07-05','C','new','Over target band nationally, but East Tamaki/Takapuna satellite offices may buy locally rather than via national FM. No general email (web form). Approach individual offices by phone.'),
('Grant Thornton New Zealand','accounting','https://www.grantthornton.co.nz','100-150','Level 4, Grant Thornton House, 152 Fanshawe Street, Auckland 1010',NULL,NULL,NULL,'+64 9 308 2570','https://nz.linkedin.com/company/grant-thornton-new-zealand-limited','Research 2026-07-05','C','new','National head office, single naming-rights floor. Contact form only; no ops decision-maker published.'),
('Baker Tilly Staples Rodway Auckland','accounting','https://bakertillysr.nz','100-150','Level 12, ANZ Centre, 23-29 Albert Street, Auckland CBD',NULL,NULL,'auckland@bakertillysr.nz','+64 9 309 0463','https://www.linkedin.com/company/bakertillysr','Research 2026-07-05','C','new','TIMING: recently relocated to ANZ Centre (fresh fit-out worth protecting) and third-party listings suggest a GM seat was recently recruited - call reception, ask who owns facilities.'),
('RSM New Zealand','accounting','https://www.rsm.global/newzealand','100-150','Level 2, 62 Highbrook Drive, East Tamaki (main); Albany; Level 19, 125 Queen St',NULL,NULL,NULL,'+64 9 367 1656','https://www.linkedin.com/company/rsm-nz','Research 2026-07-05','C','new','UNIQUE ANGLE: all three NZ offices are in Auckland - one local vendor could cover the entire national firm. Partner emails only on site.'),
('William Buck New Zealand','accounting','https://williambuck.com/nz','50-100','Level 4, 21 Queen Street, Auckland 1010',NULL,NULL,'info@williambuck.co.nz','+64 9 366 5000','https://nz.linkedin.com/company/william-buck-new-zealand','Research 2026-07-05','C','new','Foot of Queen St; NZ ops contact not published. Same building as Generate (21 Queen St) - one visit, two targets.'),
('Nexia New Zealand (Auckland)','accounting','https://www.nexia.co.nz','50-100','Level 1, 5 William Laurie Place, Albany 0632 + Level 3, 27 Gillies Ave, Newmarket',NULL,NULL,'albany@nexiaauckland.co.nz','+64 9 414 5444','https://nz.linkedin.com/company/nexia-new-zealand','Research 2026-07-05','C','new','Two AKL offices sharing one phone - single vendor pitch covers both. Newmarket office email: newmarket@nexiaauckland.co.nz. Newmarket office shares 27 Gillies Ave with Alpha Recruitment.'),
('Moore Markhams Auckland','accounting','https://www.markhams.co.nz','50-100','Level 1, 103 Carlton Gore Road, Newmarket, Auckland 1023',NULL,NULL,NULL,'+64 9 309 6011','https://nz.linkedin.com/company/mooremarkhams','Research 2026-07-05','C','new','~80 staff + 10 partners on a single Newmarket floor - sizeable single-site opportunity in the Newmarket cluster (GRA, Nexia). Contact form only.'),
('Gilligan Sheppard','accounting','https://gilligansheppard.co.nz','20-50','4th Floor, Smith & Caughey Building, 253 Queen Street, Auckland 1010',NULL,NULL,'gilshep@gilshep.co.nz','+64 9 309 5191','https://nz.linkedin.com/company/gilligan-sheppard','Research 2026-07-05','C','new','Accounting + advisory + investment firm. SAME BUILDING as UHY CBD office - one visit, two targets.'),
('Gilligan Rowe & Associates (GRA)','accounting','https://www.gra.co.nz','20-50','Level 6, 135 Broadway, Newmarket, Auckland',NULL,NULL,'info@gra.co.nz','+64 9 522 7955','https://nz.linkedin.com/company/gilligan-rowe-&-assoicates-ltd','Research 2026-07-05','C','new','Property-investor accounting specialist running frequent on-site client seminars - presentable premises matter to them. Same Broadway building as Chow:Hill AKL studio.'),
('DFK Oswin Griffiths Carlton','accounting','https://www.dfkogc.com','20-50','Level 4, 52 Symonds Street, Auckland 1010',NULL,NULL,'newbusiness@dfkogc.com','+64 9 379 3890','https://nz.linkedin.com/company/dfk-oswin-griffiths-carlton','Research 2026-07-05','C','new','Single floor top of Symonds St; international-client focus (DFK network) so front-of-house presentation matters. Published email is a monitored new-business inbox.'),
('Andersen in New Zealand','accounting','https://nz.andersen.com','20-50','470 Parnell Road, Parnell 1052 + Level 3, 159 Hurstmere Road, Takapuna',NULL,NULL,'support@nz.andersen.com','+64 9 309 7851','https://nz.linkedin.com/company/andersen-in-new-zealand','Research 2026-07-05','C','new','Rebranded from Bellingham Wallace to Andersen Global member March 2025 - brand-conscious growth phase. Two AKL offices; Takapuna office same building as Simpson Western.'),
('Johnston Associates (JACAL)','accounting','https://www.jacal.co.nz','20-40','Level 1, One Jervois Road, Ponsonby, Auckland 1011',NULL,NULL,'comms@jacal.co.nz','+64 9 361 6701','https://nz.linkedin.com/company/johnston-associates-chartered-accountants-limited','Research 2026-07-05','C','new','Four-partner practice HQ in Ponsonby, ~28 AKL staff. Near Special Group (Ponsonby Rd).'),
-- ── ARCHITECTURE / ENGINEERING (14) ─────────────────────────────────────────
('Jasmax','architecture','https://jasmax.com','100-150','2 Marston Street, Parnell, Auckland 1052','Phillipa Nihotte','Associate Principal - Professional Practice Manager','studio@jasmax.com','+64 9 366 9626','https://nz.linkedin.com/company/jasmax','Research 2026-07-05','A','new','Largest NZ architecture practice; single Parnell campus-style studio (~130 people). NZIA directory also publishes direct email Amy.Buller@jasmax.com (Associate Principal - People & Culture Lead).'),
('Warren and Mahoney (Auckland)','architecture','https://warrenandmahoney.com','100-150','Mason Bros. Building, 139 Pakenham Street West, Wynyard Quarter, Auckland 1010','Tamara Tongatule','Auckland Studio Manager','auckland@warrenandmahoney.com','+64 9 309 4894','https://www.linkedin.com/company/warrenandmahoney','Research 2026-07-05','B','new','Award-winning own fitout in Mason Bros. heritage warehouse - presentation-critical space. New AKL Studio Principal appointed (leadership refresh underway).'),
('Architectus New Zealand','architecture','https://architectus.co.nz','50-100','Level 2, 3-13 Shortland Street, Auckland 1010','Joy Partridge','Principal Practice Manager, Auckland','auckland@architectus.co.nz','+64 9 307 5970','https://nz.linkedin.com/company/architectus','Research 2026-07-05','B','new','CBD studio on Shortland St; named Principal Practice Manager is the exact buyer role for facilities/cleaning decisions.'),
('Ignite Architects','architecture','https://www.ignitearchitects.com','50-100','1 Pakenham Street East, Viaduct Harbour, Auckland 1010','Rene Pasche','Director of Operations','office@ignitearchitects.com','+64 9 356 4791','https://nz.linkedin.com/company/ignitearchitects','Research 2026-07-05','B','new','AKL HQ in Viaduct Harbour; principals'' direct emails published on contact page - unusually reachable firm. Director of Operations is the natural cleaning-contract owner.'),
('Peddlethorp','architecture','https://peddlethorp.co.nz','20-50','Level 2, Northern Steamship Building, 122 Quay Street, Auckland 1010','Stephanie Devaney','Accounts + HR','reception@peddlethorp.co.nz','+64 9 379 9405','https://nz.linkedin.com/company/peddlethorp','Research 2026-07-05','B','new','Auckland-only studio (~35 people) in heritage Northern Steamship Building on Quay St - character premises needing careful presentation.'),
('Monk Mackenzie','architecture','https://www.monkmackenzie.com','20-50','Level 1, Quay Buildings, 106-108 Quay Street, Auckland 1010','Jo Lambert','Office Manager','enquiry@monkmackenzie.com','+64 9 600 3335','https://nz.linkedin.com/company/monk-mackenzie','Research 2026-07-05','B','new','Design-forward studio (AKL + NY), 24 team members; own Quay St fitout publicly celebrated - visibly cares how the space presents. Named Office Manager on studio page.'),
('Context Architects','architecture','https://context.nz','50-100','Level 1, 326 New North Road, Kingsland, Auckland 1021',NULL,NULL,'hello@context.nz','+64 9 358 0140','https://nz.linkedin.com/company/contextnz','Research 2026-07-05','C','new','Kingsland standalone studio (own premises, off-street parking) - buys own cleaning. Team page lists leadership only (MD Stephen Voyle).'),
('Cheshire Architects','architecture','https://cheshirearchitects.com','20-50','Level 1, 26 Hobson Street, Auckland CBD 1010',NULL,NULL,'mail@cheshirearchitects.com','+64 9 358 2770','https://nz.linkedin.com/company/cheshire-architects-ltd','Research 2026-07-05','C','new','High-profile design studio (Britomart precinct, The Hotel Britomart) in character warehouse space, 25-35 staff. Exactly the studio-presentation buyer profile.'),
('Chow:Hill Architects (Auckland)','architecture','https://www.chowhill.co.nz','20-50','Level 3, 135 Broadway, Newmarket, Auckland 1149','Kalpana Reddy','Chief Executive Officer (Hamilton-based)','office@chowhill.co.nz','+64 9 522 6460','https://nz.linkedin.com/company/chow-hill-architects','Research 2026-07-05','B','new','AKL studio is a single Newmarket floor (same Broadway building as GRA). CEO named on own site but Hamilton-based - route via office@ for the AKL floor.'),
('Ashton Mitchell','architecture','https://www.ashtonmitchell.com','20-50','Level 3, Landmark House, 187 Queen Street, Auckland 1010','Helen Bennett','Office Administrator','info@ashtonmitchell.com','+64 9 366 1751','https://nz.linkedin.com/company/ashton-mitchell-architects','Research 2026-07-05','B','new','Auckland-only practice (est. 1993), 30 staff, single Queen St floor in heritage Landmark House. helen@ashtonmitchell.com appears in public directories (directory-published).'),
('Holmes (NZ)','engineering','https://holmesanz.com','50-100','GridAKL, Level 5, 12 Madden Street, Wynyard Quarter, Auckland 1010','Sam Cooper','Managing Principal NZ (Auckland-based)',NULL,'+64 9 965 4789','https://nz.linkedin.com/company/holmes-anz','Research 2026-07-05','B','new','Structural/civil/fire consultancy born in NZ (1956). CAUTION: office is a GridAKL precinct floor - verify tenant-arranged vs precinct-managed cleaning before outreach. Phone/web form only.'),
('Riley Consultants','engineering','https://www.riley.co.nz','50-100','4 Fred Thomas Drive, Takapuna, Auckland 0622',NULL,NULL,'riley@riley.co.nz','+64 9 489 7872','https://nz.linkedin.com/company/riley-consultants-ltd','Research 2026-07-05','C','new','NZ-owned geotech/civil/water consultancy, ~100 staff per own site; STANDALONE Takapuna office building - definitely buys own cleaning.'),
('eCubed Building Workshop','engineering','https://www.e3bw.co.nz','15-25','26 Fleet Street, Eden Terrace, Auckland 1021',NULL,NULL,'enquiries@e3bw.co.nz','+64 9 303 0007','https://nz.linkedin.com/company/ecubed-building-workshop-ltd','Research 2026-07-05','C','new','TIMING: recently moved to 26 Fleet St Eden Terrace - fresh-premises hook. Sustainability-led (ESD) firm, receptive to the healthy-spaces angle. Slightly under 20 staff (flagged).'),
('Airey Consultants','engineering','https://www.aireys.co.nz','20-50','Level 8, BDO Building, 19-21 Como Street, Takapuna, Auckland',NULL,NULL,NULL,'+64 9 486 4542','https://nz.linkedin.com/company/airey-consultants-ltd','Research 2026-07-05','C','new','Civil/structural/fire boutique (est. 1965), single Takapuna tower floor - same BDO Tower as BDO Takapuna. Phone/web form only.'),
-- ── PROFESSIONAL OFFICES (14) ────────────────────────────────────────────────
('Tribe Recruitment','recruitment','https://www.tribegroup.com','50-100','Shed 7, Upper Deck, City Works Depot, 90 Wellesley St West, Auckland 1010','Cathi Thomson','Head of Core Operations',NULL,'+64 22 071 5840','https://nz.linkedin.com/company/tribe-new-zealand-limited','Research 2026-07-05','A','new','100% NZ-owned; entire leadership''s direct mobiles published on own contact page (phone here is Cathi''s published mobile). CAUTION: City Works Depot precinct - verify tenant-arranged cleaning. Main: +64 9 870 5637.'),
('Beyond Recruitment','recruitment','https://www.beyondrecruitment.co.nz','50-100','Level 24, 120 Albert Street, Auckland CBD','Liza Viz','Chief Executive','info@beyond.co.nz','+64 9 309 3105','https://nz.linkedin.com/company/beyond-recruitment','Research 2026-07-05','B','new','Largest 100% Kiwi-owned recruitment agency; single leased CBD floor (L24) - straightforward nightly office-clean profile.'),
('Alpha Recruitment','recruitment','https://www.alphajobs.co.nz','50-100','Level 3, 27 Gillies Ave, Newmarket, Auckland','Joanna Rapley','Chief Operating Officer',NULL,'+64 9 524 2336','https://www.linkedin.com/company/alpha-recruitment','Research 2026-07-05','B','new','NZ-owned multi-brand group (Triangle, Staffwise, Farrow Jamieson) run from one Newmarket office - same building as Nexia Newmarket. Contact form only.'),
('Crockers Property Group','property','https://www.crockers.co.nz','100-150','525 Manukau Road, Epsom, Auckland','Elysia Martin','Group People & Culture Manager','elysia@crockers.co.nz','+64 9 623 5662','https://nz.linkedin.com/company/crockers','Research 2026-07-05','A','new','Largest single-office property management company in NZ (their words) - one big Epsom head office. Direct email + DDI published on own management-team page. Body-corp arm could open multi-site work. Main: 09 630 8890.'),
('Oyster Property Group','property','https://www.oystergroup.co.nz','50-100','Level 18, 55 Shortland Street, Auckland 1010','Rachel Barr','Chief Operating Officer (VERIFY - via The Org, not own site)','reception@oystergroup.co.nz','+64 9 632 1287','https://nz.linkedin.com/company/oyster-property-group','Research 2026-07-05','B','new','Commercial property fund manager with in-house property management (Millennium Centre, Central Park) - relationship could extend well beyond their own CBD floor.'),
('Rothbury Insurance Brokers','finance','https://www.rothbury.co.nz','100-150','Level 25, 188 Quay Street, Auckland CBD','Treena Rowley','EGM - Broking Services and Business Operations',NULL,'+64 9 358 4704','https://nz.linkedin.com/company/rothbury-insurance-brokers','Research 2026-07-05','B','new','Head office floor at 188 Quay St - FOURTH target in the HSBC Tower (with Hesketh Henry, Martelli McKegg, McVeagh Fleming, Lowndes Jordan). Rachel McKay is EGM People & Culture.'),
('ICIB Brokerweb','finance','https://www.icib.co.nz','100-150','Level 12, 66 Wyndham Street, Auckland 1010 + Level 2, 295 Lincoln Road, Henderson','Peter Holder','National Operations Manager','insurance@icib.co.nz','+64 9 377 4314','https://nz.linkedin.com/company/icib-brokerweb','Research 2026-07-05','B','new','Independent NZ-owned broker; two AKL sites (CBD + Henderson) - possible two-site package. Henderson office near Smith and Partners. Tracey Facer listed as Finance/office manager.'),
('Generate KiwiSaver','finance','https://www.generatewealth.co.nz','100-150','Level 9, 21 Queen Street, Auckland CBD','Rajat Gulati','Head of Operations','info@generatewealth.co.nz','0800 855 322','https://nz.linkedin.com/company/generate-kiwisaver-scheme','Research 2026-07-05','B','new','Fast-growing NZ-owned KiwiSaver manager, single CBD floor; THREE ops/people decision-makers on own team page (also Peter Grayson COO, Nicole Highmore Head of People). Same building as William Buck.'),
('Fisher Funds','finance','https://fisherfunds.co.nz','100-150','Crown Centre, 67-73 Hurstmere Road, Takapuna, Auckland','Chynel James','Chief Operating Officer',NULL,'+64 9 445 3377','https://nz.linkedin.com/company/fisher-funds','Research 2026-07-05','B','new','NZ''s second-largest KiwiSaver provider; Takapuna HQ is Sano home turf. CAUTION: larger corporate, may already have an FM arrangement - qualify early. Pauline Stockill is Chief People Officer.'),
('Special Group New Zealand','office','https://nz.specialgroup.com','50-100','202 Ponsonby Road, Ponsonby, Auckland 1011','Gavin Le Claire','Studio & Systems Manager','frontdesk@specialgroup.co.nz','+64 9 846 2402','https://nz.linkedin.com/company/special','Research 2026-07-05','B','new','Multi-award-winning independent creative agency in own character premises on Ponsonby Rd; Studio Manager is the natural contract owner. Amy McKay is Office Administrator. Near JACAL.'),
('Stanley St','office','https://www.stanleyst.nz','150+','Level 2, 18 Stanley Street, Parnell, Auckland 1010','Barbara Andrew','Head of Talent','barbara.andrew@stanleyst.nz','+64 9 358 5752','https://nz.linkedin.com/company/stanleyst','Research 2026-07-05','A','new','NZ''s largest independent agency, ~200 staff in large Parnell premises; direct named email published on own contact page. Near Jasmax (Parnell cluster).'),
('Tradify','office','https://www.tradifyhq.com','50-100','81 Union Street, Auckland CBD 1010',NULL,NULL,'support@tradifyhq.com','0800 003 189','https://nz.linkedin.com/company/tradify','Research 2026-07-05','C','new','Job-management SaaS for tradespeople. ANGLE: Tradify sells software to cleaning businesses - supplier-adjacent conversation starter.'),
('Tracksuit','office','https://www.gotracksuit.com','100-150','34-38 Drake Street, Freemans Bay, Auckland','Christine van Hoffen','Head of People',NULL,NULL,'https://nz.linkedin.com/company/gotracksuit','Research 2026-07-05','B','new','Brand-tracking scale-up, custom-fitted AKL HQ; recently advertised a People Experience Coordinator to manage day-to-day office operations - ACTIVE workplace-services buying signal. Form-only contact; find office email or use LinkedIn.'),
('Auror','office','https://www.auror.co','100-150','New central-Auckland HQ opened Dec 2025 (address not yet published)',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/auror','Research 2026-07-05','C','new','Retail crime intelligence scale-up; opened large new AKL HQ Dec 2025 - brand-new fit-out means a cleaning contract was recently let or is bedding in. Timing-based approach via web form.');
