-- ============================================================================
-- RETIRED (2026-07-24, Phase 4) — do NOT run.
-- ============================================================================
-- This file proposed a standalone `public.kiwisaver_optout` table keyed by
-- person_label to track the KS10 opt-out window. It was NEVER APPLIED to
-- production (verified: the table does not exist in the live database), and it
-- is superseded by the Phase 4 KiwiSaver status model, which stores the opt-out
-- state directly on the worker record:
--
--   • contractors.kiwisaver_status = 'auto_enrolled' | 'opted_out' | …
--   • contractors.kiwisaver_optout_filed  (boolean)
--   • contractors.start_date               (existing)
--
-- The KS10 window (day 14–56) is computed by `kiwiSaverOptOutStatus`
-- (src/lib/kiwisaver.ts) from those fields — no separate table. There is nothing
-- to migrate or drop; this file is retained only as a record that the approach
-- was retired. See docs/db/2026-07-24-phase4-kiwisaver-status.sql.
-- ============================================================================
