-- Sales leads seed #6 — Auckland cloud batch (4am run), 2026-07-06, deduped.
-- Consolidated from the cloud agent's two files after removing 18 rows that
-- duplicated seeds 1-5 (the cloud run started before seed #5 existed).
-- 26 unique leads: marinas/boatyards (3), franchise real-estate HQs (2),
-- schools/education (3), Waiheke/Kumeu venues (2), law 3rd sweep (5),
-- accounting (1), recruitment (1), tech/listed HQs (3), industrial-park
-- distribution (4), food/franchise HQs (2). Ranks: 3 A / 6 B / 17 C.
-- source = 'Research 2026-07-06 cloud'. Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
('Orams Marine Village','other','https://www.oramsmarine.co.nz','50-100','150-160 Beaumont Street, Westhaven, Auckland 1010','Richard Low','Operations Manager','richard@oramsmarine.co.nz','+64 21 035 0551',NULL,'Research 2026-07-06 cloud','A','new','Auckland''s premier superyacht refit and marina facility; Westhaven complex includes boatyard, engineering workshops, chandlery, offices, amenity areas. Operations Manager''s direct email and mobile published on own contact page. MD Craig Park (craig@oramsmarine.co.nz) also published. Specialist marine environment - trusted careful cleaning is a genuine differentiator. Same Westhaven precinct as RNZYS (seed 5).'),
('Gulf Harbour Marina','other','https://www.gulfharbourmarina.co.nz','20-50','Gulf Harbour, Whangaparaoa Peninsula, Auckland 0930','Lisa (surname not published)','Customer Services Manager','lisa@gulfharbourmarina.co.nz','+64 9 424 6200',NULL,'Research 2026-07-06 cloud','B','new','Marina with berths, clubrooms, cafe, amenity facilities. Customer Services Manager''s direct email published on own contact page. CAUTION: GM role recently advertised (2026) - management may be in transition. NOTE: the golf club (closed 2023) is a separate entity; this is the marina only. Whangaparaoa cluster with Wentworth College (seed 5).'),
('Half Moon Bay Marina','other','https://www.hmbmarina.co.nz','10-30','50 Argo Drive, Half Moon Bay, Auckland 2012',NULL,NULL,'customerservices@hmbmarina.co.nz','+64 9 534 3139',NULL,'Research 2026-07-06 cloud','C','new','East AKL marina + boatyard + chandlery + cafe. CAUTION: owned by Auckland Maritime Foundation (charitable trust, council-adjacent) - may involve existing FM or tender process. Same marina as Bucklands Beach Yacht Club (seed 5) - pair the visit.'),
('Harcourts Cooper & Co','property','https://www.cooperandco.co.nz','100-200','15 Mercari Way, Albany, Auckland 0632',NULL,NULL,'headoffice@cooperandco.co.nz',NULL,NULL,'Research 2026-07-06 cloud','C','new','North Shore Harcourts franchise group (separately owned from Harcourts NZ); Albany corporate HQ manages ~14 North Shore offices - multi-site upside. NZ COO Jo Clifford via press only (verify before use). Albany cluster with Kristin, Pinehurst, North Shore Golf Club.'),
('Ray White Damerell Group','property','https://www.damerell.co.nz','100-200','259 Ponsonby Road, Ponsonby, Auckland 1011','Gower Buchanan','Managing Director',NULL,'+64 9 376 2186',NULL,'Research 2026-07-06 cloud','B','new','Independent Ray White franchise group; MD confirmed on own About page. FIVE AKL offices (Ponsonby, Grey Lynn, Mt Albert, Birkenhead Point, Takapuna) - multi-site angle. Distinct from Ray White NZ corporate (seed 2). Ponsonby cluster.'),
('Dilworth School','other','https://www.dilworth.school.nz','100-200','2 Erin Street, Remuera, Auckland 1050','Ewen Anderson','Chief Executive','reception@dilworth.school.nz','+64 9 523 3179',NULL,'Research 2026-07-06 cloud','B','new','Boys'' boarding school (charitable trust est. 1906); Remuera main campus + Howick campus = two-site contract. CEO named on own website; general reception channel only. Dormitories + dining halls + teaching blocks = boarding-scale cleaning.'),
('ACG Schools (Auckland Support Office)','other','https://www.acgedu.com','100+','Level 2, 18 Normanby Road, Mt Eden, Auckland 1024',NULL,NULL,'info@acgedu.com','+64 9 306 0440',NULL,'Research 2026-07-06 cloud','C','new','Corporate support office for ACG Parnell / Sunderland / Strathallan - multi-campus potential across 3+ sites. CAUTION: Inspired Education group may centralise FM - verify at first contact. SAME BUILDING as Origin Fire (18 Normanby Rd, seed 3).'),
('Whitecliffe College','other','https://www.whitecliffe.ac.nz','50-100','67 Symonds Street, Auckland Central 1023',NULL,NULL,'admissions@whitecliffe.ac.nz','0800 800 300',NULL,'Research 2026-07-06 cloud','C','new','Private arts/design/fashion college in Symonds St heritage building: design studios, garment workshops, exhibition spaces - specialist cleaning for delicate materials. No named ops manager on own site. Symonds St cluster with Marshall Day + DFK OGC.'),
('Kumeu Valley Estate','other',NULL,'10-30','Waimauku, Auckland',NULL,NULL,NULL,'+64 9 411 7626',NULL,'Research 2026-07-06 cloud','C','new','Boutique exclusive venue (est. 2006); corporate functions + weddings to 150 guests. GM Annette Simpkins via ZoomInfo only - VERIFY before use. Phone from directories. West AKL venue cluster with The Hunting Lodge (seed 5).'),
('Tantalus Estate','other','https://www.tantalus.co.nz','20-50','70-80 Onetangi Road, Waiheke Island, Auckland',NULL,NULL,'events@tantalus.co.nz','+64 9 372 2625',NULL,'Research 2026-07-06 cloud','C','new','Premium Waiheke winery + craft brewery + restaurant (160 covers) + function venue; events@ is a direct functional inbox. Waiheke logistics complexity but premium brand + consistent event programme. COVERAGE CHECK before pursuing.'),
('Skellerup Holdings','office','https://www.skellerupgroup.com','100-150','Level 3, 205 Great South Road, Greenlane, Auckland 1051','Tim Runnalls','Chief Financial Officer','tim.runnalls@skellerupgroup.com','+64 9 523 8240',NULL,'Research 2026-07-06 cloud','B','new','NZX-listed industrial polymer group, AKL corporate HQ. CFO''s direct email published on own investor page - NOTE: financial buyer, not facilities; use as entry then re-route to office manager. May have national FM - verify. Greenlane cluster with Winger + Alexandra Park.'),
('Steindle Williams Legal','law','https://www.swlegal.co.nz','20-40','19 Mackelvie Street, Grey Lynn, Auckland 1021','Typhany Meredith','Practice Manager','typhany.meredith@swlegal.co.nz','+64 9 972 2628','https://nz.linkedin.com/company/steindle-williams-legal','Research 2026-07-06 cloud','A','new','Full-service boutique firm in OWN Grey Lynn premises - no building FM to displace. PM''s direct email + DDI both published on own people page. Same street as Deadly Ponies flagship (Mackelvie St). Grey Lynn cluster.'),
('Armstrong Murray','law','https://armstrongmurray.co.nz','20-50','11 Anzac Street, Takapuna, Auckland 0622','Desiree Mason','Practice Manager','law@armstrongmurray.co.nz','+64 9 489 9102',NULL,'Research 2026-07-06 cloud','B','new','North Shore commercial/property firm est. 1973; PM (40+ years with firm) confirmed on own people page, general inbox only. Takapuna cluster with Simpson Western, Turner Hopkins, NZDRC, Fisher Funds.'),
('Stace Hammond','law','https://www.stacehammond.co.nz','40-80','Level 15, 34 Shortland Street, Auckland 1010',NULL,NULL,NULL,NULL,NULL,'Research 2026-07-06 cloud','C','new','Commercial/litigation firm est. 1912 (AKL + Hamilton). Fee-earners only on people page - no named PM. Same building as Barfoot & Thompson Support Centre (34 Shortland St). CAUTION: tower tenancy may have building FM.'),
('Fortune Manning Lawyers','law','https://www.fortunemanning.co.nz','20-50','25 Teed Street, Newmarket, Auckland 1023',NULL,NULL,'enquiries@fortunemanning.co.nz','+64 9 915 2401',NULL,'Research 2026-07-06 cloud','C','new','Commercial law firm in Newmarket. No named practice manager on own site. Newmarket cluster with DFK ORB360, James & Wells, Moore Markhams, GRA.'),
('Neilsons Lawyers','law','https://www.neilsonslawyers.co.nz','10-20','Level 2, 345 Neilson Street, Penrose, Auckland 1061',NULL,NULL,'info@neilsonslawyers.co.nz','+64 9 634 7740',NULL,'Research 2026-07-06 cloud','C','new','General practice serving South/East AKL from Penrose since 1978. PM Eva Vanden Anker via ZoomInfo only - VERIFY. Penrose cluster with Carey Baptist College.'),
('DFK ORB360','accounting','https://dfkorb360.co.nz','20-50','2G/6 Kingdon Street, Newmarket, Auckland 1023',NULL,NULL,'help@orb360.co.nz','+64 9 377 4238',NULL,'Research 2026-07-06 cloud','C','new','Chartered accountants (DFK International member - DISTINCT from DFK Oswin Griffiths Carlton in seed 1). MD Jay Changlani named; no office manager published. Newmarket cluster.'),
('Madison Recruitment','office','https://madison.co.nz','50-100','Level 6, 51 Shortland Street, Auckland CBD 1010',NULL,NULL,NULL,'+64 9 303 4455','https://nz.linkedin.com/company/madison-recruitment','Research 2026-07-06 cloud','C','new','NZ-owned recruitment firm (Accordant Group); AKL head office at 51 Shortland St - SAME BUILDING as Property Council NZ (seed 3). Group GM Operations Kerrie Gregory on own team page (group-domain email; local buyer likely office coordinator).'),
('Vista Group International','office','https://www.vistagroup.co.nz','100-200','Shed 12, City Works Depot, 90 Wellesley Street West, Auckland 1010',NULL,NULL,'info@vistagroup.co.nz','+64 9 984 4570','https://nz.linkedin.com/company/vista-group-international','Research 2026-07-06 cloud','C','new','NZX-listed cinema-software group; premium City Works Depot heritage conversion - SAME PRECINCT as Tribe Recruitment (seed 1) + TBIG (seed 3). CAUTION: precinct/building FM possible - verify.'),
('Turners Automotive Group','office','https://www.turnersautogroup.co.nz','100+','Level 5, 70 Shortland Street, Auckland 1010',NULL,NULL,'info@turnersautogroup.co.nz',NULL,NULL,'Research 2026-07-06 cloud','C','new','NZX-listed auto services group (70+ sites); corporate HO floor at 70 Shortland St - SAME BUILDING as Shortland Chambers + BBD (seed 3). Head-office-floor-only angle; likely centralised FM - verify.'),
('Cottonsoft Limited','other','https://www.cottonsoft.co.nz','100-200','64 Highbrook Drive, East Tamaki, Auckland 2013','Rivka Thomas','Head of Operations',NULL,NULL,NULL,'Research 2026-07-06 cloud','B','new','NZ tissue/paper manufacturer; Highbrook HO + manufacturing. Head of Operations + HR Manager (Helen Hargreaves-Judd) both named on own Our People page, no direct channels. Office floors above manufacturing. Highbrook cluster with RSM + BDO East Tamaki + Wynyard Wood (60-64 Highbrook Dr!).'),
('NXP Limited','other',NULL,'50-100','49 Waiouru Road, Highbrook Business Park, East Tamaki, Auckland 2013',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/nxpnz','Research 2026-07-06 cloud','C','new','NZ-owned packaging/labelling distributor; Highbrook HO + DC. NOTE: confirm website (nxp.nz vs NXP Semiconductors brand clash). Highbrook cluster.'),
('United Industries','other',NULL,'50-100','293 Ti Rakau Drive, East Tamaki, Auckland 2013',NULL,NULL,NULL,'+64 9 274 0408',NULL,'Research 2026-07-06 cloud','C','new','NZ-owned industrial/engineering products distributor (est. 1991); East Tamaki HO. VERIFY website + email before outreach. East Tamaki cluster with BDO + Pakuranga Golf.'),
('The Drug Detection Agency (TDDA)','office','https://tdda.com','50-100','44 Constellation Drive, Rosedale, Auckland 0632',NULL,NULL,NULL,NULL,NULL,'Research 2026-07-06 cloud','C','new','NZ-owned workplace drug/alcohol testing agency (~97 staff, CEO Glenn Dobson); Rosedale HO. ANGLE: compliance environment demands impeccably clean professional premises - trusted-supplier pitch is a genuine differentiator. Rosedale cluster.'),
('Columbus Coffee NZ','other','https://www.columbuscoffee.co.nz','20-50','Level 2, 100 Mayoral Drive, Auckland CBD 1010','Jon Hassall','Chief Operating Officer','jon@columbuscoffee.co.nz',NULL,NULL,'Research 2026-07-06 cloud','A','new','NZ cafe franchise (75+ cafes); national franchise support office. COO''s direct email published on own contact page. Pitch the corporate office only - franchisees clean their own outlets. General: 0800 100 110.'),
('BurgerFuel Group','office','https://burgerfuelgroup.com','20-50','66 Surrey Crescent, Grey Lynn, Auckland 1021',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/burgerfuelgroup','Research 2026-07-06 cloud','C','new','NZX-listed burger franchise group (BurgerFuel/Shake Out/Winner Winner); small corporate HQ in Grey Lynn cluster with Steindle Williams + Motion Sickness + John Andrew.');
