-- Sales leads seed #5 — Auckland commercial research batch 5, researched 2026-07-05,
-- compiled 2026-07-06. 48 leads: 12 car groups/design showrooms, 12 wineries/
-- breweries/brand HQs, 12 private schools/tertiary, 12 members clubs/venues/arts.
-- Ranks: 17 A / 26 B / 5 C. Same rules as prior seeds: nothing invented; NULL
-- where nothing published; third-party staff-size estimates labelled.
-- NOTE: supersedes the overlapping rows in the cloud batch (PR #324) - those
-- duplicates are stripped from seed #6 before merge.
-- Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── CAR GROUPS + DESIGN SHOWROOMS (12) ──────────────────────────────────────
('Continental Cars (VW/Audi Newmarket)','other','https://www.continentalcars.co.nz','50-100','38-42 Great South Road, Newmarket, Auckland','Peter Metcalfe','Dealer Principal, Volkswagen',NULL,'09 526 6968','https://nz.linkedin.com/company/continental-cars-nz','Research 2026-07-05 r5','A','new','Multi-brand premium glass showroom campus. DDI + mobile 021 975 550 published; emails Cloudflare-obfuscated (null, not guessed). Alt: Scott Windelburn, GSM Audi, DDI 09 526 9058. Pitch showroom/customer-lounge presentation.'),
('Simon Lucas Mitsubishi','other','https://simonlucas.co.nz','20-40','183 Target Road, Wairau Valley, Auckland 0627 (+ Silverdale service centre)','Sean Parrey','General Manager',NULL,'09 443 9499','https://nz.linkedin.com/company/simon-lucas-mitsubishi','Research 2026-07-05 r5','A','new','Owner-operated (Simon Lucas, Dealer Principal, DDI 09 444 8144) - fast decisions. GM''s DDI published in clear. High-traffic Wairau Valley corner showroom.'),
('John Andrew Ford & Mazda','other','https://www.johnandrew.co.nz','50-100','36-38 Great North Road, Grey Lynn, Auckland 1021 (+ Penrose, Henderson)','Markus Tsoumas','Dealer Principal',NULL,'09 376 9829',NULL,'Research 2026-07-05 r5','A','new','Dual-brand showroom block on Great North Rd - near Giltrap campus. CAVEAT: Eagers Automotive NZ owned; large contracts may route via group procurement. DP''s DDI published.'),
('Armstrong''s Certified Used Newmarket','other','https://www.armstrongs.co.nz','20-50','82 Great South Road, Epsom, Auckland','Nick Marwah','General Manager (site)','nick.marwah@armstrongs.co.nz','021 029 55390','https://nz.linkedin.com/company/armstrongsconz','Research 2026-07-05 r5','A','new','Site GM with published direct email + mobile. CAVEAT: national group (25+ dealerships) - facilities may be bought at group level (Group Office Mt Wellington). Great South Rd motor mile.'),
('Jacobsen (Creative Surfaces)','other','https://jacobsen.co.nz','25-50','41D Morrin Road, Mt Wellington, Auckland 1072','Renee Jacobsen','Chief Executive Officer',NULL,'027 211 0049',NULL,'Research 2026-07-05 r5','A','new','Family-owned national flooring distributor since 1962; CEO''s direct mobile published on own team page. HO + trade showroom + warehouse one site. Alt: Steffan Visser, Customer Services Manager AKL. General 0800 800 460 / customer.services@jacobsen.co.nz.'),
('Plumbline (Auckland showroom)','other','https://plumbline.co.nz','10-20','23 Davis Crescent, Newmarket, Auckland','Shane Senne','Showroom Manager - Auckland','shane.senne@plumbline.co.nz','021 535 823','https://nz.linkedin.com/company/plumbline','Research 2026-07-05 r5','A','new','Premium bathroomware showroom (glass/tapware/stone) in Newmarket design precinct. Manager''s direct email + mobile from own showroom page. General: 09 526 0136 / auckland@plumbline.co.nz.'),
('Giltrap Group','other','https://www.giltrap.com','100+','Level 2, 119 Great North Road, Grey Lynn, Auckland 1021','Luke Senior','General Manager, Property',NULL,NULL,'https://nz.linkedin.com/company/giltrap-group','Research 2026-07-05 r5','B','new','TOP PRIORITY: NZ''s premier luxury dealer group (Audi/Porsche/Aston/Lamborghini/McLaren), flagship glass campus Grey Lynn. GM PROPERTY (facilities owner) + Blair Groube (GM Aftersales & Ops) named on own site, no direct contacts - via site form or LinkedIn.'),
('Auckland City BMW (ex Team McMillan)','other','https://www.aucklandcitybmw.com','20-50','7-15 Great South Road, Newmarket, Auckland 1051','Jonny Highton','Dealer Principal',NULL,'09 524 3300',NULL,'Research 2026-07-05 r5','B','new','HOOK: recent rebrand (Collins Asset Management buyout) + showroom makeover - new-fitout presentation standards to protect. Team-page emails bot-protected; phone gets DP''s address.'),
('Winger Group','other','https://winger.co.nz','100+','261-279 Great South Road, Greenlane, Auckland 1051 (+ Penrose service centre)','Andy Sinclair','Chief Executive Officer - Auckland region',NULL,NULL,'https://nz.linkedin.com/company/wingermotors','Research 2026-07-05 r5','B','new','Rebuilt Greenlane HQ + Penrose customer centre with on-site cafe. CEO name via trade press (Autofile; ex-Hyundai NZ CEO) - own team page bot-blocked. Greenlane motor mile.'),
('Dawson & Co','other','https://www.dawsonandco.nz','15-25','115 The Strand, Parnell, Auckland','Scott Fisk','Co-owner / General Manager','info@dawsonandco.nz','+64 9 476 1121','https://nz.linkedin.com/company/dawsonandco','Research 2026-07-05 r5','B','new','STRONG HOOK: Parnell flagship expanded 750sqm to 1,200sqm in 2026, operations consolidated there - freshly renovated luxury furniture floor. Family business, fast decisions. trade@dawsonandco.nz alt.'),
('Studio Italia','other','https://www.studioitalia.co.nz','5-15','25 Nugent Street, Grafton, Auckland','Kate Fisher','Operations and Logistics Manager','info@studioitalia.co.nz','09 523 2105',NULL,'Research 2026-07-05 r5','B','new','Italian furniture/kitchens showroom; high-spec displays = detail presentation cleaning. Ops manager named on own About page, general channels only. Nugent St design cluster (BBC + Woods same street).'),
('Matisse International','other','https://matisse.co.nz','10-20','130 St Georges Bay Road, Parnell, Auckland 1151','Alan Bertenshaw','Co-owner','design@matisse.co.nz','09 302 2284',NULL,'Research 2026-07-05 r5','B','new','HOOK: brand-new flagship showroom (Cassina + 15 luxury brands) - new premium fitout, high glass/stone. Owners named in press, not own site. Same street as Mansons + Marketing Association.'),
-- ── WINERIES / BREWERIES / BRAND HQs (12) ───────────────────────────────────
('Soljans Estate Winery','other','https://soljans.co.nz','20-50','366 State Highway 16, Kumeu 0892, Auckland','Tony Soljan','Managing Director & Head Winemaker','tony@soljans.co.nz','09 412 5858','https://nz.linkedin.com/company/soljans-estate-winery','Research 2026-07-05 r5','A','new','5th-generation family winery: cafe + tasting room + function rooms = daily FOH presentation + offices. Tyler Soljan (Sales Manager, tyler@soljans.co.nz) also published; functions@soljans.co.nz. Kumeu cluster.'),
('Kumeu River Wines','other','https://kumeuriver.co.nz','10-30','550 State Highway 16, Kumeu 0892, Auckland','Marijana Brajkovich','Family owner - hospitality, sales & marketing','marijana@kumeuriver.co.nz','+64 9 412 8415',NULL,'Research 2026-07-05 r5','A','new','World-renowned chardonnay producer - cellar door presentation is brand-critical. Direct email published on own Visit Us page. Kumeu cluster with Soljans + UHY Kumeu.'),
('Babich Wines','other','https://www.babichwines.com','20-50','15 Babich Road, Henderson Valley, Auckland 0614','David Babich','General Manager','info@babichwines.co.nz','+64 9 833 7859','https://nz.linkedin.com/company/babich-wines-ltd','Research 2026-07-05 r5','B','new','One of NZ''s largest family wineries; HO + winery + cellar door all on Henderson Valley site - squarely West Auckland. GM named on own People page, general channel only. Pitch offices + cellar door (production is industrial).'),
('Coopers Creek Vineyard','other','https://cooperscreek.co.nz','10-30','601 State Highway 16, Huapai, Auckland','Adam Joyce','CEO (Marlborough Wine Ltd group)','info@mwl.co.nz','+64 9 972 9498',NULL,'Research 2026-07-05 r5','B','new','Huapai site in the Kumeu corridor. Ownership recently under Marlborough Wine Ltd - verify cellar-door trading status + where office team sits before outreach.'),
('Sawmill Brewery / Smoko Room','other','https://www.sawmillbrewery.co.nz','20-50','1004 Leigh Road, Matakana, Auckland','Mike Sutherland & Kirsty McKay','Owners','smokoroom@sawmillbrewery.co.nz','09 422 6555',NULL,'Research 2026-07-05 r5','B','new','NZ''s first B Corp brewery + Smoko Room restaurant. COVERAGE CHECK: Matakana ~45-60min north - confirm serviceability first. B Corp values align with Sano positioning. FOH + offices fit; brewhouse industrial.'),
('Hallertau Brewery & Biergarten','other','https://hallertau.co.nz','20-50','1171 Coatesville-Riverhead Highway, Riverhead, Auckland 0892 (+ Clevedon venue)','Steve Plowman','Founder/Owner','reservations@hallertau.co.nz','09 412 5555',NULL,'Research 2026-07-05 r5','B','new','~250-seat restaurant + brewpub + biergarten, Riverhead (NW coverage); second venue Clevedon - one contract, two venues. Owner via trade press, not own site. FOH/venue/offices fit.'),
('The Hunting Lodge Winery','other','https://www.thehuntinglodge.com','20-50','305-307 Waikoukou Valley Road, Waimauku, Auckland 0882',NULL,NULL,'events@thehuntinglodge.com','09 964 0542',NULL,'Research 2026-07-05 r5','C','new','Restaurant + cellar door/Lawn Bar + Barn events venue (weddings/corporate) - constant presentation need, in Sano''s patch. Site references in-house events planner but publishes no names - call to get venue manager.'),
('Villa Maria (Indevin) - Mangere Estate','other','https://villamariawines.com','50-100','118 Montgomerie Road, Mangere, Auckland 2022',NULL,NULL,'villamaria.cellardoor@indevin.com',NULL,NULL,'Research 2026-07-05 r5','C','new','OWNERSHIP FLAG: Indevin-owned since 2021; AKL cellar door permanently closed. Remaining opportunity = head office + event spaces on 40ha Mangere estate. Contact form only. South AKL.'),
('Churly''s Brewpub & Eatery (Behemoth)','other','https://www.behemothhospitality.co.nz/brewpub','10-30','1A Charles Street, Mount Eden, Auckland',NULL,NULL,'team@churlys.co.nz','09 218 3521','https://www.linkedin.com/company/behemoth-brewing-company','Research 2026-07-05 r5','C','new','Central brewpub + eatery (functions, group bookings). Founder Andrew Childs in trade press but no ops contact on own site. FOH/dining fit; brewery floor industrial.'),
('Karen Walker Ltd (Head Office)','office','https://www.karenwalker.com','20-50','Head office, Victoria Street West area, Auckland (street address not published)','Anna (surname not published)','Sales enquiries contact (ops role unconfirmed)','karenwalker@karenwalker.com','+64 9 361 0780',NULL,'Research 2026-07-05 r5','B','new','NZ-owned fashion house: AKL head office + atelier (atelier@karenwalker.com) + 3 stores. Direct first-name emails published but no named ops manager - get office manager via HO line.'),
('Deadly Ponies','office','https://deadlyponies.com','20-50','Head office/workroom Auckland (address unpublished; flagship 70 Mackelvie St, Ponsonby)','Liam Bowden','Founder','hello@deadlyponies.com','+64 9 376 3469','https://nz.linkedin.com/company/deadly-ponies','Research 2026-07-05 r5','B','new','B Corp leathergoods brand - design-led, presentation-focused pitch lands. HO + workroom is target space; confirm address by phone. Founders named on own About page.'),
('Les Mills International (Global HO)','office','https://www.lesmills.com','100+','Level 2, 200 Victoria Street West, Auckland 1010 (per directories; not on own site)',NULL,NULL,'info@lesmills.com','+64 9 366 9900',NULL,'Research 2026-07-05 r5','C','new','Global head office of the NZ-owned fitness-programme licensing business (distinct from the gyms) - genuine office-cleaning scale. No named facilities contact on own web presence.'),
-- ── PRIVATE SCHOOLS + TERTIARY (12) ─────────────────────────────────────────
('King''s School','other','https://www.kings.school.nz','Roll ~650-700','258 Remuera Road, Remuera, Auckland 1050','Nicola Paoli','Head of Corporate Services','n.paoli@kings.school.nz','+64 9 520 7776',NULL,'Research 2026-07-05 r5','A','new','Direct DDI + personal email published on school''s own staff-contact page - rare among AKL privates. Corporate Services = cleaning-contract owner. Campus incl. swim school + after-school care (extended hours). May hold incumbent contract - note in outreach. General: 09 520 7770 / office@kings.school.nz.'),
('Auckland Institute of Studies (AIS)','other','https://www.ais.ac.nz','Multi-building campus + hostel','28a Linwood Avenue, Mt Albert, Auckland 1025','Philip McCracken','Chief Executive Officer','philipm@ais.ac.nz','+64 9 815 1717',NULL,'Research 2026-07-05 r5','A','new','Private tertiary; publishes individual staff emails on own site. On-site student accommodation = hostel cleaning + campus cleaning. Alt: President Dr Lehan Stemmet (lehans@ais.ac.nz).'),
('Wentworth College & Primary','other','https://wentworth.school.nz','Roll ~500, two sites','65 + 95 Gulf Harbour Drive, Whangaparaoa, Auckland','Bruce Tong','Executive Principal','btong@wentworth.school.nz','+64 9 424 3273',NULL,'Research 2026-07-05 r5','A','new','Small independent Y1-13 school - Executive Principal is the commercial sign-off; direct email on own team page. Alt: Hillary Mann, Assistant Head - Operations (HMann@wentworth.school.nz). One contract, two buildings.'),
('Kristin School','other','https://www.kristin.school.nz','Roll ~1600','360 Albany Highway, Albany, Auckland 0632','Nigel Wilkinson','Director of Business Services',NULL,'+64 9 415 9566','https://nz.linkedin.com/in/nigel-wilkinson-356999b','Research 2026-07-05 r5','B','new','EXACT BUYER: own-site bio explicitly covers property, grounds, food + facilities. One of NZ''s largest independents, single big campus. No direct channel - reception or LinkedIn. Albany cluster.'),
('Saint Kentigern (Trust Board)','other','https://www.saintkentigern.com','3000+ students, 3 campuses','130 Pakuranga Road, Pakuranga + 82 Shore Road, Remuera + Wilson Bay','Justin Browne','Property Manager, Trust Services',NULL,'+64 9 577 0749',NULL,'Research 2026-07-05 r5','B','new','Trust-level procurement: ONE property team buys for College + Boys'' + Girls'' + Preschool - single relationship, multi-campus. Also named: Alison Denne (Dir. Finance & Resources), Merle Boniface (Capital Planning - new Wilson Bay campus = development hook). In-house property team exists - may be partly in-house/incumbent.'),
('St Cuthbert''s College','other','https://stcuthberts.school.nz','Roll ~1450 + boarding','122 Market Road, Epsom, Auckland 1051','Glenn Corbett','Chief Operating Officer',NULL,'+64 9 520 4159','https://nz.linkedin.com/in/glenn-corbett-24664925','Research 2026-07-05 r5','B','new','TIMING: COO is a newly created role (advertised late 2025 as ''scope to innovate'') - ops structures being reshaped. Boarding house = 7-day cleaning. Epsom cluster.'),
('Diocesan School for Girls','other','https://www.diocesan.school.nz','Roll ~1700','Clyde Street, Epsom, Auckland 1051','Paul Sherris','Director of Finance and Operations',NULL,'+64 9 520 0221',NULL,'Research 2026-07-05 r5','B','new','His own-site welcome article explicitly names ''commercial contracts'' + ''property maintenance'' in his remit - the exact buyer. Aquatics Centre = wet-area specialist angle. In-house maintenance team exists - may be incumbent-held.'),
('King''s College','other','https://www.kingscollege.school.nz','Roll ~1100 + boarding houses','41 Golf Avenue, Otahuhu, Auckland 1062','Nick Davies','Chief Operating Officer',NULL,'+64 9 276 0600','https://nz.linkedin.com/in/njd82','Research 2026-07-05 r5','B','new','CAUTION: name via Tribe recruitment announcement + LinkedIn (school site confirms COO role, doesn''t name him). Board created COO role citing ''growing complexity of the business side'' - professionalising procurement. Boarding = 7-day.'),
('Pinehurst School','other','https://www.pinehurst.school.nz','Roll ~1000+','75 Bush Road, Albany, Auckland 0632','Jon Horne','Business Manager',NULL,'+64 9 414 0960',NULL,'Research 2026-07-05 r5','B','new','CA-qualified Business Manager (ex-GM/FD TEAR Fund) on SLT - commercially minded buyer. Via main office. Albany cluster with Kristin + Gaze Burt.'),
('Laidlaw College','other','https://www.laidlaw.ac.nz','Purpose-built campus (2024)','3 Smythe Road, Henderson, Auckland 0650','John Ferguson','Maintenance Manager, Facilities (ZoomInfo - VERIFY)',NULL,'+64 9 836 7800',NULL,'Research 2026-07-05 r5','B','new','STRONG HOOK: relocated to brand-new Henderson campus 2024 - services contracts recently set or settling. Contact name third-party (ZoomInfo) - verify by phone. Alt: Alastair Peak, Finance Ops Manager. West AKL cluster. henderson@laidlaw.ac.nz.'),
('Ficino School','other','https://ficino.school.nz','Roll ~150 + preschool','27 Esplanade Road, Mt Eden, Auckland 1024','Anne Lehrke','Business Manager (role own-site; name ZoomInfo - VERIFY)',NULL,'+64 9 623 3385',NULL,'Research 2026-07-05 r5','B','new','Own site confirms Business Manager is the gatekeeper role but doesn''t name her. Small site = smaller contract, fast decisions.'),
('Carey Baptist College','other','https://www.carey.ac.nz','Single Penrose campus','473 Great South Road, Penrose, Auckland',NULL,NULL,'enquiries@carey.ac.nz','0800 773 776','https://nz.linkedin.com/school/carey-baptist-college-nz/','Research 2026-07-05 r5','C','new','Facilities likely managed via Baptist Union precinct - no clear ops decision-maker published. Ask general enquiries for whoever manages campus facilities.'),
-- ── MEMBERS CLUBS / VENUES / RACING / ARTS (12) ─────────────────────────────
('Royal New Zealand Yacht Squadron','other','https://www.rnzys.org.nz','Two-level clubhouse, 7-day ops','181 Westhaven Drive, Westhaven Marina, Auckland 1011','Georgia Witt','General Manager',NULL,'+64 29 020 20457',NULL,'Research 2026-07-05 r5','A','new','TIMING: newly appointed GM (promoted from within) - natural supplier-review moment. Hospitality-grade clubhouse, heavy events. Direct mobile published in clear on own contact page (email obfuscated, not guessed). General 09 360 6800.'),
('Bucklands Beach Yacht Club','other','https://bbyc.org.nz','Full-service club + marina','Half Moon Bay Marina, Half Moon Bay, Auckland','Lyle Tresadern','Club Manager','manager@bbyc.org.nz','027 534 3046',NULL,'Research 2026-07-05 r5','A','new','Manager''s role email + mobile published on own contact page. Bar + function rooms + sailing academy. Alt: Jenny Robinson, Bar & Function Manager (bar@bbyc.org.nz). East AKL cluster.'),
('Auckland Thoroughbred Racing (Ellerslie)','other','https://www.ellerslieevents.co.nz','Major function venue + racecourse','100 Ascot Avenue, Remuera, Auckland 1050','Craig Fenwick','Executive General Manager - Hospitality',NULL,'09 522 3802',NULL,'Research 2026-07-05 r5','A','new','One of Auckland''s biggest non-council function venues; Ellerslie Events publishes full account-management team with DDIs (emails obfuscated). Also operates Pukekohe Park. General 09 524 4069.'),
('The Remuera Club','other','https://remueraclub.co.nz','Clubhouse + dining + functions','27-33 Ohinerau Street, Remuera, Auckland 1050','Anton Coetzee','General Manager','anton@remueraclub.org.nz','+64 9 524 4094',NULL,'Research 2026-07-05 r5','A','new','GM''s personal direct email + extension published on club''s own contact page - cleanest single decision-maker channel in this batch. Presentation-led members'' environment.'),
('Avondale Jockey Club','other','https://www.ajc.co.nz','Racecourse + markets + facility hire','22 Elm Street, Avondale, Auckland 1026','Manny Boyack','General Manager','mannyb@ajc.co.nz','027 537 2990',NULL,'Research 2026-07-05 r5','A','new','GM''s personal email + mobile published on own contact page. Venue-heavy site: Avondale Sunday Markets weekly + facility hire. Avondale cluster with Oculus. General 09 828 3309 / admin@ajc.co.nz.'),
('TAPAC (Auckland Performing Arts Centre)','other','https://www.tapac.org.nz','Theatre + studios, 7-day building','100 Motions Road, Western Springs, Auckland 1022','Jamie Mainds','Operations Manager',NULL,'09 845 0295',NULL,'Research 2026-07-05 r5','A','new','Trust-run performing arts centre; Ops Manager (ex Piccadilly Theatre London deputy GM) with direct email published on own contact page (firstname@tapac.org.nz pattern; obfuscated in fetch). 7-day venue = recurring need.'),
('The Northern Club','other','https://northernclub.co.nz','Heritage clubhouse + accommodation','19 Princes Street, Auckland 1010','Joanna Cooke','General Manager','generalmanager@northernclub.co.nz','+64 9 379 4755',NULL,'Research 2026-07-05 r5','B','new','Near-A: GM named in NZ Herald (May 2026), generalmanager@ role address published via reciprocal-club listings (own site blocks bots - eyeball before sending). Accommodation + heritage interiors = premium daily scope. Ops Manager Sarah Little per directories.'),
('Auckland Trotting Club (Alexandra Park)','other','https://www.alexandrapark.co.nz','300+ staff, major function centre','Cnr Greenlane West & Manukau Road, Greenlane, Auckland 1051','Brad Steele','Chief Executive (commences 3 Aug 2026)',NULL,'09 630 5660','https://nz.linkedin.com/company/alexandra-park','Research 2026-07-05 r5','B','new','TIMING: incoming CEO starts 3 August 2026 - fresh-broom supplier window. Tasman Room (900 theatre-style) + boardrooms + sports bar + weekly race nights. Side-door: Peter Green, GM Sponsorship (peter.green@alexandrapark.nz). administration@alexandrapark.nz.'),
('Auckland Theatre Company (ASB Waterfront Theatre)','other','https://www.atc.co.nz','Theatre + separate production base','138 Halsey Street, Wynyard Quarter (admin: 487 Dominion Rd, Mt Eden)','Sharon Byrne','Director, ASB Waterfront Theatre',NULL,'09 309 3395',NULL,'Research 2026-07-05 r5','B','new','ATC operates the theatre with own venue team (2 FOH managers, events manager - Amy Robertson is event-hire contact). Two premises = two cleaning scopes. No direct contacts published.'),
('Q Theatre','other','https://www.qtheatre.co.nz','Multi-venue building, Queen St','305 Queen Street, Auckland Central 1010','Karyn Metcalf','Head of Visitor Experience and Facilities',NULL,'09 309 9771',NULL,'Research 2026-07-05 r5','B','new','EXACT ROLE: facilities + FOH + hospitality sit under her per Q''s own staff page. Team channel ve@qtheatre.co.nz. Evenings/weekends operation. CE: Sally-Anne Kerr.'),
('Auckland Philharmonia','other','https://aucklandphil.nz','~25+ admin staff, own offices','Level 1, Auckland Town Hall, 301-303 Queen Street, Auckland 1010','Wendy Gardiner','Director of Operations',NULL,'09 638 6266',NULL,'Research 2026-07-05 r5','B','new','Named Director of Operations on own team page; several directors have published DDI extensions (hers obtainable on request). Target their own leased office space, not the council-run venue.'),
('Royal Akarana Yacht Club','other','https://rayc.co.nz','New purpose-built centre, 7-day venue','8-10 Tamaki Drive, Okahu Bay, Auckland 1071','Jamie Catchpole','Club Manager',NULL,'09 520 0203','https://nz.linkedin.com/company/royal-akarana-yacht-club','Research 2026-07-05 r5','B','new','New flagship Hyundai Marine Sports Centre + Akarana Event Centre (7 days from 7:30am, events@akarana.co.nz) - presentation is a live concern. Manager named on own team page (site blocks bots - no direct channel captured).');
