-- Sales leads seed #6 — Auckland cloud batch 2, 2026-07-06.
-- 25 leads across: law firms 3rd sweep (6), accounting firms (2),
-- professional services / recruitment (2), members clubs / arts venues (3),
-- listed-company / technology HQs (3), industrial-park distribution (4),
-- food / beverage / franchise HQs (2), private arts education (1),
-- employer association (1), commercial law (1).
-- Ranks: 3 A / 4 B / 18 C.
-- Note: law/accounting 3rd sweep and industrial-park verticals yield
-- fewer named ops contacts than first-sweep professional-services batches;
-- rank distribution reflects vertical reality.
-- Exclusions verified against seeds 1–5 (165 leads). No overlaps.
-- source = 'Research 2026-07-06 cloud'. Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── LAW FIRMS 3RD SWEEP (6) ────────────────────────────────────────────────
('Steindle Williams Legal','law','https://www.swlegal.co.nz','20-40','19 Mackelvie Street, Grey Lynn, Auckland 1021','Typhany Meredith','Practice Manager','typhany.meredith@swlegal.co.nz','+64 9 972 2628','https://nz.linkedin.com/company/steindle-williams-legal','Research 2026-07-06 cloud','A','new','Full-service boutique firm (commercial, property, litigation, private client, criminal law) in own Grey Lynn premises. Practice Manager Typhany Meredith''s direct email and DDI both published on own people profile page (swlegal.co.nz/our-people/typhany-meredith). Pitch angle: owner-occupied suburban premises, no building FM to displace. General: Grey Lynn cluster.'),
('Armstrong Murray','law','https://armstrongmurray.co.nz','20-50','11 Anzac Street, Takapuna, Auckland 0622','Desiree Mason','Practice Manager','law@armstrongmurray.co.nz','+64 9 489 9102',NULL,'Research 2026-07-06 cloud','B','new','North Shore commercial/property/private-client law firm est. 1973; Desiree Mason appointed Practice Manager in 1997 and has been with the firm 40+ years — confirmed on firm''s own people page (armstrongmurray.co.nz/people/desiree-mason/). No direct PM email published; law@ general inbox from own site. Takapuna cluster with Schnauer & Co (1 Shea Terrace, same suburb) and Prendos (4 Fred Thomas Dr, seed 2).'),
('Stace Hammond','law','https://www.stacehammond.co.nz','40-80','Level 15, 34 Shortland Street, Auckland 1010',NULL,NULL,NULL,NULL,NULL,'Research 2026-07-06 cloud','C','new','Commercial/litigation firm est. 1912; Auckland CBD and Hamilton offices. People archive page lists fee-earners only — no named practice or office manager on own site. Phone and email from own contact page (verify before outreach). CBD tower tenancy (34 Shortland St, PWC Tower). CAUTION: high-floor CBD tenancy may have building FM arrangement; confirm cleaning procurement at first contact.'),
('Fortune Manning Lawyers','law','https://www.fortunemanning.co.nz','20-50','25 Teed Street, Newmarket, Auckland 1023',NULL,NULL,'enquiries@fortunemanning.co.nz','+64 9 915 2401',NULL,'Research 2026-07-06 cloud','C','new','Commercially focused law firm in Newmarket (commercial, property, employment, dispute resolution). No named practice or office manager on own website; enquiries@ general inbox and phone from own contact page. Newmarket cluster with DFK ORB360 (6 Kingdon St) and James & Wells (123 Carlton Gore Rd, seed 2).'),
('Neilsons Lawyers','law','https://www.neilsonslawyers.co.nz','10-20','Level 2, 345 Neilson Street, Penrose, Auckland 1061',NULL,NULL,'info@neilsonslawyers.co.nz','+64 9 634 7740',NULL,'Research 2026-07-06 cloud','C','new','General practice law firm serving South and East Auckland from Penrose since 1978; freephone 0800 LAWFIRM also published. No named practice manager on own website (PM Eva Vanden Anker identified via ZoomInfo — third-party only, verify before use). Suburban Penrose location; smaller tenancy. Approach as a straightforward commercial enquiry via info@ or phone.'),
('Tompkins Wake','law','https://www.tompkinswake.com','20-50','Level 17, 88 Shortland Street, Auckland 1010',NULL,NULL,NULL,'+64 9 558 0699',NULL,'Research 2026-07-06 cloud','C','new','NZ law firm (Hamilton primary office, Auckland secondary); Auckland office at Level 17, Shortland & Fort Building. People page lists fee-earners only — no named Auckland office manager on own site. CAUTION: high-floor CBD tenancy may have building FM; verify cleaning procurement at first contact. Phone from own contact page.'),
-- ── ACCOUNTING FIRMS (2) ───────────────────────────────────────────────────
('DFK ORB360','accounting','https://dfkorb360.co.nz','20-50','2G/6 Kingdon Street, Newmarket, Auckland 1023',NULL,NULL,'help@orb360.co.nz','+64 9 377 4238',NULL,'Research 2026-07-06 cloud','C','new','Chartered accountants and business advisors (DFK International network member); Newmarket and Wellington offices. MD Jay Changlani named on own people page; no practice or office manager published — cleaning buyer is likely an office admin not listed. help@ from own contact page. Newmarket cluster with Fortune Manning and James & Wells (seed 2).'),
('Nexia Auckland','accounting','https://www.nexia.co.nz','100-130','Level 1, 5 William Laurie Place, Albany, Auckland 0632 (+ Newmarket office, address relocated 2026 — verify)',NULL,NULL,'albany@nexiaauckland.co.nz','+64 9 414 5444','https://nz.linkedin.com/company/nexia-new-zealand','Research 2026-07-06 cloud','C','new','Independently operated Nexia International member firm; 130 professionals across Auckland (Albany + Newmarket) and Christchurch and Hastings offices. Albany office email from own contact page; Newmarket office relocated to new premises in 2026 (confirm current address before outreach). Two Auckland sites = multi-site contract angle. NOTE: awarded Great Place to Work 2026 — culture-forward pitch is appropriate.'),
-- ── PROFESSIONAL SERVICES / RECRUITMENT (2) ────────────────────────────────
('Beyond Recruitment','office','https://www.beyondrecruitment.co.nz','50-100','Level 6, 120 Albert Street, Auckland CBD 1010','Grant Habgood','General Manager — National Client Solutions',NULL,NULL,'https://nz.linkedin.com/company/beyond-recruitment','Research 2026-07-06 cloud','B','new','100% Kiwi-owned multi-specialist recruitment agency (largest of its kind in NZ); CEO Liza Viz and GM Grant Habgood both profiled on own consultants page (beyondrecruitment.co.nz/consultants/grant-habgood). No direct email or DDI published for Grant. NOTE: address at 120 Albert St confirmed from third-party directory — verify current tenancy before outreach. Phone from own contact page (verify).'),
('Madison Recruitment','office','https://madison.co.nz','50-100','Level 6, 51 Shortland Street, Auckland CBD 1010',NULL,NULL,NULL,'+64 9 303 4455','https://nz.linkedin.com/company/madison-recruitment','Research 2026-07-06 cloud','C','new','NZ-owned multi-specialist recruitment firm (part of Accordant Group; Absolute IT and Madison brands); Auckland head office at 51 Shortland St. Group GM Operations Kerrie Gregory profiled on madison.co.nz/our-team/ but her email is at the parent group domain — cleaning buyer is likely the Auckland office coordinator/EA, not published on own site. General phone from own site.'),
-- ── MEMBERS CLUBS / ARTS VENUES (3) ────────────────────────────────────────
('Remuera Club','other','https://remueraclub.co.nz','20-50','27-33 Ohinerau Street, Remuera, Auckland 1050','Anton Coetzee','General Manager','anton@remueraclub.org.nz','+64 9 524 4094',NULL,'Research 2026-07-06 cloud','A','new','Private social-and-sports club in Remuera; facilities include bar, dining room, function rooms, tennis courts, squash courts, and bowling green — multiple cleaning zones requiring consistent high presentation. GM Anton Coetzee direct email published on own contact page (remueraclub.co.nz/contact/, copyright 2026). Remuera prestige cluster.'),
('Royal Akarana Yacht Club','other','https://rayc.co.nz','20-50','8-10 Tamaki Drive, Okahu Bay, Auckland 1071','Andrew Brookland','General Manager',NULL,'+64 9 524 9945',NULL,'Research 2026-07-06 cloud','B','new','Premier Auckland sailing club (Royal warrant) at the Akarana Marine Sports Centre on Okahu Bay; clubhouse with bar, dining, function rooms, boat storage, and marina berths. GM Andrew Brookland''s appointment confirmed on own club website (rayc.co.nz news post); no direct GM email or DDI published on contact page (general club phone only). Corporate event and function hire adds regular large-event cleaning demand. Waterfront venue — strong presentation pitch.'),
('Q Theatre','other','https://www.qtheatre.co.nz','20-50','305 Queen Street, Auckland Central 1010',NULL,NULL,'info@qtheatre.co.nz','+64 9 309 9771',NULL,'Research 2026-07-06 cloud','C','new','Independent professional theatre venue on Queen St (Rangatira and Herald Theatre spaces); owned by Q Theatre Trust. Own staff page lists departmental heads (Patron Services, Programming, Development) — no named facilities or ops manager published. General enquiry email from own contact page. CBD central. NOTE: trust ownership may involve council funding — governance likely straightforward on cleaning decisions.'),
-- ── LISTED COMPANY / TECHNOLOGY HQs (3) ───────────────────────────────────
('Vista Group International','office','https://www.vistagroup.co.nz','100-200','Shed 12, City Works Depot, 90 Wellesley Street West, Auckland Central 1010',NULL,NULL,'info@vistagroup.co.nz','+64 9 984 4570','https://nz.linkedin.com/company/vista-group-international','Research 2026-07-06 cloud','C','new','NZX-listed global cinema management software group (HQ Auckland, offices in UK, AU, US, NL); premium City Works Depot premises (heritage industrial-to-office conversion). No named facilities or ops contact on own site. info@ from own contact page. CAUTION: at this size may have building or national FM; angle is City Works Depot tenancy without in-house contract.'),
('Les Mills International','office','https://www.lesmills.com','100-200','Level 2, 200 Victoria Street West, Auckland 1010',NULL,NULL,'info@lesmills.com','+64 9 366 9900',NULL,'Research 2026-07-06 cloud','C','new','Auckland-founded global group-fitness brand (Les Mills programmes in 21,000+ gyms worldwide); Victoria St West corporate head office is the product and brand hub. No named office or facilities manager on own contact page. CAUTION: global scale may involve building FM for the AKL HQ tenancy — verify cleaning procurement before outreach.'),
('Turners Automotive Group','office','https://www.turnersautogroup.co.nz','100-500','Level 5, 70 Shortland Street, Auckland 1010',NULL,NULL,'info@turnersautogroup.co.nz',NULL,NULL,'Research 2026-07-06 cloud','C','new','NZX-listed diversified auto services group (auction, retail, finance, insurance, e-commerce; 70+ sites nationally); corporate head office at Level 5, 70 Shortland St. No named facilities or ops contact on own site. CAUTION: NZX-listed, 500+ staff nationally — likely centralised FM arrangement; head-office floor only angle. Verify independently owned cleaning arrangement before outreach.'),
-- ── INDUSTRIAL / DISTRIBUTION (4) ─────────────────────────────────────────
('Cottonsoft Limited','other','https://www.cottonsoft.co.nz','100-200','64 Highbrook Drive, East Tamaki, Auckland 2013','Rivka Thomas','Head of Operations',NULL,NULL,NULL,'Research 2026-07-06 cloud','B','new','NZ-owned tissue and paper products manufacturer (brands: Softy, Kittensoft, Cottonelle under licence); manufacturing and head office in the Highbrook Business Park. Head of Operations Rivka Thomas and HR Manager Helen Hargreaves-Judd both named on own Our People page (cottonsoft.co.nz/our-people); no direct email or DDI published for either. Large site: office floors above manufacturing = specialist cleaning opportunity. Highbrook cluster with NXP (49 Waiouru Rd) and United Industries.'),
('NXP Limited','other',NULL,'50-100','49 Waiouru Road, Highbrook Business Park, East Tamaki, Auckland 2013',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/nxpnz','Research 2026-07-06 cloud','C','new','NZ-owned packaging and labelling solutions distributor (assets acquired by private Kiwi investors 2018); Highbrook head office with distribution centre; also Wellington and Christchurch DC sites. No named ops or office contact on own site. NOTE: confirm website address before outreach (nxp.nz may conflict with NXP Semiconductors global brand). Highbrook cluster with Cottonsoft and United Industries. LinkedIn confirms distinct NZ company.'),
('United Industries','other',NULL,'50-100','293 Ti Rakau Drive, East Tamaki, Auckland 2013',NULL,NULL,NULL,'+64 9 274 0408',NULL,'Research 2026-07-06 cloud','C','new','NZ-owned industrial and commercial engineering products distributor (founded 1991); East Tamaki head office. No website confirmed from own source — phone from directory listing. No named ops contact. VERIFY website and contact email before outreach. East Tamaki industrial cluster with Cottonsoft and NXP.'),
('The Drug Detection Agency (TDDA)','office','https://tdda.com','50-100','44 Constellation Drive, Rosedale, Auckland 0632',NULL,NULL,NULL,NULL,NULL,'Research 2026-07-06 cloud','C','new','NZ-owned workplace drug and alcohol testing agency (~97 staff; CEO Glenn Dobson); Rosedale head office with national field team. No named office or operations manager on own contact page. NOTE: drug-testing compliance environment demands impeccably clean, professional office presentation — trusted supplier pitch is a genuine differentiator. Rosedale North Shore cluster.'),
-- ── FOOD / BEVERAGE / FRANCHISE HQs (2) ──────────────────────────────────
('Columbus Coffee NZ','other','https://www.columbuscoffee.co.nz','20-50','Level 2, 100 Mayoral Drive, Auckland CBD 1010','Jon Hassall','Chief Operating Officer','jon@columbuscoffee.co.nz',NULL,NULL,'Research 2026-07-06 cloud','A','new','NZ-founded premium café franchise chain (est. 1995; 75+ cafes nationally); national franchise support office at 100 Mayoral Drive. COO Jon Hassall''s direct email published on own contact page (columbuscoffee.co.nz/contact-us). CBD head office only — franchisees manage their own outlet cleaning. General: 0800 100 110. Pitch into the corporate office (not franchise network).'),
('BurgerFuel Group','office','https://burgerfuelgroup.com','20-50','66 Surrey Crescent, Grey Lynn, Auckland 1021',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/burgerfuelgroup','Research 2026-07-06 cloud','C','new','NZX-listed (BFW) NZ-founded burger franchise group (BurgerFuel, Shake Out, Winner Winner; 100+ outlets). Small corporate HQ in Grey Lynn. No named ops or office contact on own site. CAUTION: NZX-listed may have FM arrangement even at small HQ scale; verify before outreach. Grey Lynn cluster with Steindle Williams Legal (19 Mackelvie St) and Giltrap Group (119 Great North Rd, seed 5).'),
-- ── PRIVATE ARTS EDUCATION (1) ────────────────────────────────────────────
('Whitecliffe College','office','https://www.whitecliffe.ac.nz','50-100','67 Symonds Street, Auckland Central 1023',NULL,NULL,'admissions@whitecliffe.ac.nz','0800 800 300',NULL,'Research 2026-07-06 cloud','C','new','Private arts, design, and fashion college; Symonds Street heritage building campus in Auckland Central. No named ops or facilities manager on own site. General admissions email and 0800 number from own contact page. Campus includes design studios, garment workshops, exhibition spaces, teaching areas — specialist cleaning for delicate materials and art spaces. NOTE: approach via college administration; private tertiary institution purchases cleaning independently.'),
-- ── EMPLOYER ASSOCIATION HQ (1) ────────────────────────────────────────────
('EMA (Employers & Manufacturers Association)','other','https://www.ema.co.nz','50-100','145 Khyber Pass Road, Grafton, Auckland 1023',NULL,NULL,NULL,'+64 9 367 0900',NULL,'Research 2026-07-06 cloud','C','new','NZ''s largest employer advocacy body (est. 1886; 4,000+ member businesses); Grafton head office with conference facilities, training rooms, and offices. CEO John Fraser-MacKenzie (appointed June 2024, named in press). No named office or facilities manager on own site. Large standalone premises with ongoing conference and events cleaning demand. Also freephone 0800 300 362. Grafton cluster.');
