-- Sales leads seed #5 — Auckland cloud batch 1, 2026-07-06.
-- 20 leads across: private schools (4), members clubs / arts venues (3),
-- automotive group HQ (1), wineries / breweries with venue hire (4),
-- boutique venue (1), franchise real-estate HQs (2), marinas / boatyards (3),
-- listed company corporate HQ (1), independent school #5 (1).
-- Ranks: 1 A / 7 B / 12 C.
-- Note: schools, wineries, and marina verticals yield fewer named ops contacts
-- than professional-services sweeps; rank distribution reflects vertical reality.
-- Exclusions verified against seeds 1–4 (145 leads). No overlaps.
-- Bayleys Realty Group (30 Gaunt St) excluded — same address as Auckland Body
-- Corporate (Bayleys group) already captured in seed 3.
-- source = 'Research 2026-07-06 cloud'. Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── PRIVATE SCHOOLS (5) ────────────────────────────────────────────────────────
('Dilworth School','office','https://www.dilworth.school.nz','100-200','2 Erin Street, Remuera, Auckland 1050','Ewen Anderson','Chief Executive','reception@dilworth.school.nz','+64 9 523 3179',NULL,'Research 2026-07-06 cloud','B','new','Boys'' boarding school (charitable trust, est. 1906); Remuera main campus + Howick campus = two-site contract opportunity. CEO Ewen Anderson named on own website. General reception email only; no CEO direct email or DDI published. Large campus: dormitories, dining halls, teaching blocks, sports grounds.'),
('ACG Schools (Auckland Support Office)','office','https://www.acgedu.com','100-500','Level 2, 18 Normanby Road, Mt Eden, Auckland 1024',NULL,NULL,'info@acgedu.com','+64 9 306 0440',NULL,'Research 2026-07-06 cloud','C','new','Corporate support office for ACG''s Auckland schools: ACG Parnell, ACG Sunderland (Henderson), ACG Strathallan (Karaka) — multi-campus contract potential across 3+ sites. 625+ staff nationally, 4,700+ students. No named ops/facilities manager on own site; info@ general email from own contact page. 18 Normanby Rd = same building as Origin Fire Consultants (seed 3). CAUTION: large private-education group may have national FM arrangement; verify at first contact.'),
('Kristin School','office','https://www.kristin.school.nz','150-200','360 Albany Highway, Albany, Auckland 0632',NULL,NULL,'kristin@kristin.school.nz','+64 9 415 9566','https://nz.linkedin.com/company/kristin-school','Research 2026-07-06 cloud','C','new','Large independent co-ed school (Early Learning through Year 13, 2000+ students); purpose-built multi-building campus in Albany. Director of Business Services role exists in leadership structure (name not confirmed on own site). General enquiry email from own site. Albany cluster with North Shore Golf Club (seed 4), Pinehurst School, and Harcourts Cooper & Co (same suburb).'),
('Pinehurst School','office','https://www.pinehurst.school.nz','100-150','75 Bush Road, Albany, Auckland 0632',NULL,NULL,NULL,NULL,NULL,'Research 2026-07-06 cloud','C','new','Independent K-12 co-ed school in Albany; modern multi-building campus. No named ops person or direct contact channel confirmed on own website. Albany cluster with Kristin School (360 Albany Highway, same suburb). Approach via school reception at first contact.'),
('King''s College','office','https://www.kingscollege.school.nz','100-200','41 Golf Avenue, Otahuhu, Auckland 1062',NULL,NULL,'reception@kingscollege.school.nz','+64 9 276 0600',NULL,'Research 2026-07-06 cloud','C','new','Anglican boys'' boarding school est. 1896; extensive heritage campus in Otahuhu with chapel, dormitories, sports grounds, performing arts centre. COO attends Board but name not published on own website. General reception only. Large campus = significant cleaning contract. South Auckland location.'),
-- ── MEMBERS CLUBS / ARTS VENUES (3) ────────────────────────────────────────────
('The Northern Club','other','https://www.northernclub.co.nz','20-50','19 Princes Street, Auckland CBD 1010',NULL,NULL,'generalmanager@northernclub.co.nz','+64 9 379 4755',NULL,'Research 2026-07-06 cloud','C','new','Auckland''s oldest private members club (est. 1869; absorbed the Auckland Club 2010); historic CBD premises with formal dining rooms, bars, drawing room, billiards, accommodation. generalmanager@ email published on own contact page; GM name not confirmed on club''s own website. High-profile client-facing spaces demand impeccable presentation — strong pitch angle.'),
('Royal New Zealand Yacht Squadron','other','https://www.rnzys.org.nz','20-50','181 Westhaven Drive, Westhaven, Auckland 1010','Georgia Witt','General Manager','reception@rnzys.org.nz','+64 9 360 6800',NULL,'Research 2026-07-06 cloud','B','new','Premier NZ sailing club (Royal warrant, est. 1871); Westhaven clubhouse with bar, dining, function rooms, marina berths. GM Georgia Witt confirmed on own website (CMAE member). Reception email only — no GM direct email or DDI published. Venue hire for corporate events and weddings. Same Westhaven precinct as Orams Marine Village.'),
('Auckland Theatre Company','other','https://www.atc.co.nz','20-70','138 Halsey Street, Wynyard Quarter, Auckland 1010',NULL,NULL,NULL,'+64 9 309 3395',NULL,'Research 2026-07-06 cloud','C','new','NZ''s leading professional theatre company; primary base at ASB Waterfront Theatre (Wynyard Quarter) + second venue at Mt Eden War Memorial Hall (487 Dominion Road). Performing-arts spaces (stages, dressing rooms, audience areas, technical zones) require careful specialist cleaning. Two AKL sites. No named facilities/ops contact published on own site.'),
-- ── AUTOMOTIVE GROUP HQ (1) ────────────────────────────────────────────────────
('Giltrap Group','office','https://www.giltrap.co.nz','500-600','Level 2, 119 Great North Road, Grey Lynn, Auckland 1021','Steve Kenchington','Chief Executive',NULL,'+64 9 376 0911','https://nz.linkedin.com/company/giltrap-group','Research 2026-07-06 cloud','B','new','NZ''s largest privately owned automotive group (family-owned since 1965, ~30 premium brands, 29 dealerships nationally). CEO Steve Kenchington named in own press release (appointed Feb 2025). Corporate HQ at 119 Great North Rd. No CEO direct email published; phone only. CAUTION: at this scale may have centralised FM arrangement; angle is HQ floor + any Auckland showrooms without in-house contracts. Grey Lynn precinct.'),
-- ── WINERIES / BREWERIES WITH VENUE HIRE (4) + BOUTIQUE VENUE (1) ─────────────
('Soljans Estate Winery','other','https://www.soljans.co.nz','20-50','366 State Highway 16, Kumeu, Auckland 0891','Tony Soljan','Director','cellar@soljans.co.nz','+64 9 412 5858',NULL,'Research 2026-07-06 cloud','B','new','Family-owned boutique winery and restaurant est. 1937 (third-generation Soljan family, Kumeu). Dedicated function venue for private and corporate events (up to 150 guests), cellar door, brasserie. Director Tony Soljan is the family decision-maker (named on own website); no separate ops/events manager published. General cellar email from own site. Kumeu cluster with Coopers Creek and Kumeu River Wines.'),
('Kumeu River Wines','other','https://www.kumeuriver.co.nz','10-30','550 State Highway 16, Kumeu, Auckland 0891',NULL,NULL,'paul@kumeuriver.co.nz','+64 9 412 8415',NULL,'Research 2026-07-06 cloud','C','new','Family-owned Brajkovich family winery (est. 1944); boutique production facility and cellar door. paul@kumeuriver.co.nz from own website contact page (likely owner/winemaker — role is production, not facilities). Kumeu cluster with Soljans and Coopers Creek.'),
('Coopers Creek Vineyard','other','https://www.cooperscreek.co.nz','20-30','601 State Highway 16, Kumeu, Auckland 0891',NULL,NULL,'info@cooperscreek.co.nz','+64 9 412 8560',NULL,'Research 2026-07-06 cloud','C','new','Award-winning family winery (est. 1980); cellar door, vineyard restaurant, popular Summer Sundays outdoor concerts — regular large-crowd events create ongoing cleaning demand. General info@ email from own site. Kumeu cluster with Soljans and Kumeu River.'),
('Kumeu Valley Estate','other',NULL,'10-30','Waimauku, Auckland',NULL,NULL,NULL,'+64 9 411 7626',NULL,'Research 2026-07-06 cloud','C','new','Boutique exclusive venue (est. 2006); corporate functions and weddings, up to 150 guests, rural property setting near Kumeu/Riverhead/Muriwai. GM Annette Simpkins identified via ZoomInfo and review aggregators only — not confirmed on own website (third-party: verify before use). Phone from directory listings. West Auckland cluster with Soljans, Kumeu River, Coopers Creek.'),
('Tantalus Estate','other','https://www.tantalus.co.nz','20-50','70-80 Onetangi Road, Waiheke Island, Auckland',NULL,NULL,'events@tantalus.co.nz','+64 9 372 2625',NULL,'Research 2026-07-06 cloud','C','new','Premium Waiheke winery and craft brewery with restaurant (up to 160 covers) and function venue; events@ channel published on own site. No named events/ops manager listed. Waiheke Island location adds logistics complexity but premium brand and consistent event programme create real cleaning contract value. events@ is a direct functional inbox.'),
-- ── FRANCHISE REAL-ESTATE HQs (2) ─────────────────────────────────────────────
('Harcourts Cooper & Co','property','https://www.cooperandco.co.nz','100-200','15 Mercari Way, Albany, Auckland 0632',NULL,NULL,'headoffice@cooperandco.co.nz',NULL,NULL,'Research 2026-07-06 cloud','C','new','North Shore franchise group for Harcourts (separately owned from Harcourts NZ HQ); Albany corporate HQ manages ~14 North Shore offices. NZ COO Jo Clifford identified in press coverage only — not confirmed on own website (verify before use). General headoffice@ email from own site. Albany cluster with Kristin School, North Shore Golf Club (seed 4).'),
('Ray White Damerell Group','property','https://www.damerell.co.nz','100-200','259 Ponsonby Road, Ponsonby, Auckland 1011','Gower Buchanan','Managing Director',NULL,'+64 9 376 2186',NULL,'Research 2026-07-06 cloud','B','new','Independent Ray White franchise group; MD Gower Buchanan confirmed on own About page. Five AKL offices (Ponsonby, Grey Lynn, Mt Albert, Birkenhead Point, Takapuna) — multi-site angle. Head office at 259 Ponsonby Rd. No MD direct email published; general phone only. Same Ponsonby/Grey Lynn precinct as Giltrap Group (119 Great North Rd).'),
-- ── MARINAS / BOATYARDS (3) ───────────────────────────────────────────────────
('Orams Marine Village','other','https://www.oramsmarine.co.nz','50-100','150-160 Beaumont Street, Westhaven, Auckland 1010','Richard Low','Operations Manager','richard@oramsmarine.co.nz','+64 21 035 0551',NULL,'Research 2026-07-06 cloud','A','new','Auckland''s premier superyacht refit and marina facility; Westhaven complex includes boatyard, engineering workshops, chandlery, offices, amenity areas. Operations Manager Richard Low direct email and mobile published on own contact page (verify at first approach). MD Craig Park (craig@oramsmarine.co.nz) also published if re-routing needed. Specialist marine environment — careful trusted cleaning a genuine differentiator. Same Westhaven precinct as RNZYS.'),
('Gulf Harbour Marina','other','https://www.gulfharbourmarina.co.nz','20-50','Gulf Harbour, Whangaparaoa Peninsula, Auckland 0930','Lisa',NULL,'lisa@gulfharbourmarina.co.nz','+64 9 424 6200',NULL,'Research 2026-07-06 cloud','B','new','Marina on Whangaparaoa Peninsula with berths, clubrooms, café, and amenity facilities. Customer Services Manager ''Lisa'' (first name only) direct email published on own contact page. CAUTION: GM role was recently advertised (2026) — management may be in transition; confirm stability before outreach. NOTE: Gulf Harbour Golf Club (separate entity, same suburb) closed 2023 — this is the marina only.'),
('Half Moon Bay Marina','other','https://www.hmbmarina.co.nz','10-30','50 Argo Drive, Half Moon Bay, Auckland 2012',NULL,NULL,'customerservices@hmbmarina.co.nz','+64 9 534 3139',NULL,'Research 2026-07-06 cloud','C','new','East Auckland marina and boatyard with berths, boatyard, chandlery, and café (Half Moon Bay Landing). Owned by Auckland Maritime Foundation (charitable trust — council-adjacent). CAUTION: council-adjacent ownership may mean an existing FM or tender requirement; verify governance structure before outreach. General customerservices@ from own site.'),
-- ── LISTED COMPANY CORPORATE HQ (1) ────────────────────────────────────────────
('Skellerup Holdings','office','https://www.skellerupgroup.com','100-150','Level 3, 205 Great South Road, Greenlane, Auckland 1051','Tim Runnalls','Chief Financial Officer','tim.runnalls@skellerupgroup.com','+64 9 523 8240',NULL,'Research 2026-07-06 cloud','B','new','NZX-listed industrial rubber/polymer products group (global operations, AKL corporate HQ). CFO Tim Runnalls direct email published on own investor-relations page. NOTE: CFO is a financial buyer, not a facilities buyer; cleaning contract probably sits with the Office Manager or EA (not named on own site) — use Tim as initial entry, re-route to ops/admin once engaged. CAUTION: listed company at this size may have national FM arrangement; verify at first contact.');
