-- 2026-08-02 - Sano commercial leads, batch 9 (RE-VERIFIED ex-BC networking contacts)
--
-- 81 leads: 45 A / 28 B / 8 C.
-- Source: a ~10-year-old business-networking contact directory. 138 office-based Auckland
-- businesses were web-re-verified; 84 confirmed STILL TRADING (61%), 3 already in the DB dropped.
-- These are WARM re-engagement leads (prior relationship). Emails refreshed to current published
-- inboxes where the old personal address had died; left NULL where none was published (never guessed).
-- Several rebrands captured (e.g. Auldhouse -> Lumify Work, EAP Services -> Habit Health).
-- Each insert skips a company already present (case-insensitive). Run in Supabase SQL editor.

begin;

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Actions for Survival Limited', 'First Aid & Health/Safety Training (NZQA PTE)', 'https://actionsforsurvival.com/', 'Established 2004; nationwide PTE with Manukau training centre', 'Manukau, Auckland (training facility)', NULL, NULL, 'accounts@actionsforsurvival.com', '09 271 2402', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. NZQA-registered private training establishment delivering first-aid/H&S courses, with a physical training facility in Manukau, Auckland. Website is actionsforsurvival.com (matches old email domain, so the old email likely still valid). Training premises = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Actions for Survival Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Alliott NZ Limited', 'Chartered Accountants / Tax & Business Advisory', 'https://www.alliott.co.nz/', 'Top-30 NZ accounting firm; multi-partner team', '142 Broadway, Newmarket, Auckland 1023', NULL, NULL, 'enquiries@alliott.co.nz', '09 520 9200', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading from a Newmarket office. Full-service chartered accounting firm, Xero Platinum Partner, sole NZ member of Alliott Global Alliance. Old personal email (greg.m@) replaced with the current published general inbox enquiries@alliott.co.nz. Solid multi-staff office = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Alliott NZ Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Aspiring Language Institute', 'English language school (private, NZQA-registered)', 'https://aspiring.ac.nz', 'small (max ~60 students)', 'City Campus: 76-78 Symonds Street, Grafton, Auckland 1010 (UUNZ building); plus East Auckland campus at 17 Aviemore Drive, Highland Park', NULL, NULL, 'study-at@aspiring.ac.nz', '09 282 4622', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Real CBD premises (Symonds St, Grafton) plus a second East Auckland campus. Old personal email (janet@) not published anymore; current published inbox is study-at@aspiring.ac.nz. Good cleaning fit - classrooms/offices across two sites.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Aspiring Language Institute'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Auckland Business Chamber', 'Business membership org / HR / training', 'https://aucklandchamber.co.nz', NULL, 'Level 9, 90 Symonds Street, Grafton, Auckland 1010', NULL, NULL, 'info@akl.chamber.co.nz', '09 309 6100', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading. Rebranded from ''Auckland Chamber of Commerce'' to ''Auckland Business Chamber''. Real CBD office premises (Level 9, 90 Symonds St). Old jlawrence@ personal address replaced with the current published office inbox info@akl.chamber.co.nz. Strong cleaning fit (occupied office floor).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Auckland Business Chamber'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Axis Consultants (Surveyors, Planners, Engineers)', 'Land surveyors / planners / engineers (land development consultancy)', 'https://www.axis-consultants.co.nz', 'in-house team of surveyors, planners, engineers', '106 Mokoia Road, Birkenhead, Auckland', NULL, NULL, 'info@axis-consultants.co.nz', '09 480 2648', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, same info@ inbox still published (verified, not guessed). Real office in Birkenhead. Good cleaning fit - professional office premises.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Axis Consultants (Surveyors, Planners, Engineers)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Baigent Consulting Ltd', 'Accountants / business advisory', 'https://www.baigentconsult.co.nz', '~20 (per corporate listing)', '301 Botany Road, Manukau, Auckland 2013', NULL, NULL, NULL, '09 274 3075', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, same website and phone. Office at 301 Botany Road (serves Howick/Botany/Pakuranga). Could not confirm the ross@ personal email is still live and no generic office inbox was published, so left email blank rather than keep an unverified address. Solid office premises, good fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Baigent Consulting Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'BDS Chartered Accountants Ltd', 'Chartered accountants / tax consultants (Xero Gold partner)', 'https://www.bdsaccountants.co.nz', NULL, 'Level 12, 17 Albert Street, Auckland CBD 1010', NULL, NULL, NULL, '09 366 1822', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading (est. 1997), same phone. Note: primary site is now bdsaccountants.co.nz (taxmaster.co.nz was the old brand) so the old petert@taxmaster.co.nz is unreliable - contact page uses a form, no plain office inbox published, so email left blank. CBD office (Level 12, 17 Albert St), member of Heart of the City. Excellent cleaning fit - central office floor.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('BDS Chartered Accountants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Carpenter Pratt Chartered Accountants Ltd', 'Chartered accountants / tax / business advisory', 'https://www.cpca.co.nz', 'Two-director practice + support staff', '33 Coles Crescent, Papakura, Auckland 2110', 'David Pratt', 'Director', 'info@cpca.co.nz', '09 298 2511', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading from a physical Papakura office. Published office inbox info@cpca.co.nz preferred over the old david@ personal address. Directors Craig Carpenter and David Pratt. Good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Carpenter Pratt Chartered Accountants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'CBA Design Ltd', 'Architectural design & drafting', 'https://www.cba-design.co.nz', 'Small design team', 'Onehunga, Auckland', 'Andrew', 'Principal / designer', NULL, '09 622 0282', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading, Onehunga-based architectural design firm servicing greater Auckland (20+ years). Andrew and Sam named on reviews. Kept old_email as reference; could not confirm a current published office inbox on the site, so left email blank rather than guess. Phone confirmed current. Office premises = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('CBA Design Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Chris Horton Associates Ltd', 'Insolvency / restructuring / liquidation advisory (legal-adjacent)', 'https://www.chrishortonassociates.co.nz', 'Boutique specialist practice', 'Level 10, Dorchester Building, 34 Shortland Street, Auckland Central', 'Chris Horton', 'Principal', 'chorton@chal.co.nz', '0274 759 659', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading from a CBD office (Level 10, 34 Shortland St). Old email chorton@chal.co.nz is still the current published address (chal.co.nz domain confirmed live). Note: it''s an insolvency/restructuring firm, not general lawyers as the old record said. Phone is now a mobile (0274). CBD office = decent cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Chris Horton Associates Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Denise Maffey & Associates Ltd', 'Chartered accountants (small business)', 'https://www.maffey.co.nz', 'Small team (accountants + bookkeepers)', '72 Access Road, Kumeu 0810, Auckland', NULL, NULL, 'info@maffey.co.nz', '09 412 2535', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading with active website and NW Country business association listing. Real office premises in Kumeu (NW Auckland). Old info@ email still valid. Good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Denise Maffey & Associates Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Double R Industrial Training Ltd', 'Forklift / heavy vehicle training', 'https://doubler.co.nz', 'Small family business (since 1996)', 'Unit 3, 43 Allens Road, East Tamaki, Auckland', 'Dorothy Ruawhare', 'Director / Instructor', 'info@doubler.co.nz', '0800 455 387', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Active site and Yellow listing. Real training premises in East Tamaki with classroom/yard - decent cleaning fit. Old info@ email still valid. Old landline 09 273 8992 superseded by published 0800 number.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Double R Industrial Training Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Electrical Systems Ltd (ESL)', 'Electrical contracting / engineering', 'https://www.electricalsystems.co.nz', 'Multi-disciplinary team (established 1993)', 'Albany, Auckland (North Shore)', NULL, NULL, 'admin@electricalsystems.co.nz', '09 479 7990', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Established Auckland (+Wellington) electrical contractor based Albany North Shore. Old personal email ross@ replaced with published admin@ office inbox. Real office/premises - good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Electrical Systems Ltd (ESL)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Fat Parrot Architecture', 'Architecture practice (NZIA)', 'https://fatparrot.co.nz', '~13 staff (Auckland office)', 'Unit 7B, 331 Rosedale Road, Albany, Auckland', NULL, NULL, 'info@fatparrot.co.nz', '09 915 5345', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. NZIA practice, ~13 staff in Albany office (plus a Havelock North team). Old personal email john@ replaced with published info@ office inbox. Real staffed office - strong cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Fat Parrot Architecture'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'First Class Accounts North Shore', 'Accounting / bookkeeping (franchise office)', 'https://www.firstclassaccounts.co.nz/find-an-office/first-class-northshore-accountants (also fcanorthshore.co.nz)', 'Small (single-office franchise)', '47 Goodwood Drive, Windsor Park, North Shore, Auckland 0632', 'Nigel Hudson', 'Accountant / franchisee', 'nigel.hudson@firstclassaccounts.co.nz', '09 480 7140', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed still trading. Nigel Hudson still the named accountant; phone 09 480 7140 matches the old record exactly, so the old email is very likely still live. Real office premises on the North Shore. Listings obfuscate the email but firm/phone/name all verified current.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('First Class Accounts North Shore'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Food Safe Limited', 'Hospitality / food-safety & HACCP training (PTE), corporate office premises', 'https://www.foodsafe.net.nz', 'Small training provider', '37D Crummer Road, The Workshop, Ponsonby, Auckland 1021', NULL, NULL, 'info@foodsafe.net.nz', '09 281 4226 / 0800 003 097', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Still actively trading, rebranded onto foodsafe.net.nz (old foodsafe.co.nz domain superseded). Real office in Ponsonby. Could not confirm Suresh is still involved; use the office inbox info@foodsafe.net.nz. Old suresh@foodsafe.co.nz likely dead (domain changed).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Food Safe Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Forsyth & Associates Ltd', 'Accountants / taxation & business advisory, commercial office premises', 'https://forsyths.co.nz', 'Small accounting firm', 'Unit 5, 15 Accent Drive, East Tamaki, Auckland 2013 (PO Box 259175, Botany)', 'David Forsyth', 'Principal / director', 'david@forsyths.co.nz', '09 274 1150', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading at same East Tamaki premises; website forsyths.co.nz live, phone 09 274 1150 unchanged. Old email domain still active so david@forsyths.co.nz likely valid; verify before use.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Forsyth & Associates Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Frog Recruitment Ltd', 'Recruitment agency, CBD office premises', 'https://www.frogrecruitment.co.nz', 'Medium (part of people2people Group since 2019; multi-office)', 'Level 15, 51 Shortland Street, Auckland Central 1010', NULL, NULL, NULL, '09 362 0528', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Strongly trading — well-established agency, acquired into people2people Group 2019, multi-office. Real CBD office. Phone 09 362 0528 unchanged. Old contact Vikki W''s personal email not re-verified; use the contact form / office line. Good commercial-cleaning fit (office floor).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Frog Recruitment Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Golian Consultants Ltd', 'Licensed immigration advisers, office premises', 'https://golian.co.nz', 'Small-medium advisory firm', 'Level 1, 3 Campbell Road, Royal Oak, Auckland 1023', 'Harjeet Singh Golian', 'Director / Senior Licensed Immigration Adviser', 'harjeet@golian.co.nz', '09 624 1204', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading; golian.co.nz live, Harjeet Golian still director and licensed (IAA adviser #200800540). Real office in Royal Oak. Old email domain active so harjeet@golian.co.nz likely valid; an office/info inbox may also exist via their contact page.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Golian Consultants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Hunkin Engineering Ltd', 'Precision / general engineering, roller specialists — workshop premises', 'https://www.hunkineng.co.nz (also hunkineng.com)', 'Small-medium engineering workshop', '14 Mahunga Drive, Mangere Bridge, Auckland 2022', NULL, NULL, 'info@hunkineng.co.nz', '09 634 0160 / 0800 89 88 87', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading at Mangere Bridge; now a Haas machining house. Website and phone 09 634 0160 unchanged; generic info@hunkineng.co.nz inbox still current. Note: positioned as precision/roller engineering rather than marine now. Workshop premises.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Hunkin Engineering Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Kiwi Vision Consultants Ltd', 'Land surveyors / land development consultants', 'https://kiwivision.co.nz', '~12 staff', 'B2/59 Apollo Drive, Rosedale, Auckland 0632', NULL, NULL, 'info@kiwivision.co.nz', '09 915 4135', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Strongly confirmed: active surveying/planning/engineering firm, ~12 staff, North Shore office at Apollo Drive, Rosedale. Phone and email updated (old direct ''paul@'' replaced with current published office inbox info@kiwivision.co.nz; old 09 444 0762 line superseded by 09 915 4135). Good office cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Kiwi Vision Consultants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Lamb & Associates Ltd', 'Land surveyors / land development consultants', 'https://www.surveyor.co.nz', 'small established firm', '234 Bush Road, Albany, Auckland', 'Colin Beddow', 'Owner', 'lamb@surveyor.co.nz', '09 415 5919', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading since 1972, Albany office (234 Bush Rd) since 1997. Purchased 2018 by Colin & Carol Beddow. Website surveyor.co.nz active. Domain email retained as still-valid; phone confirmed unchanged. Real office premises = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Lamb & Associates Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Laurent Law', 'Law firm - immigration specialists', 'https://laurentlaw.co.nz', 'small specialist firm', '7A Maidstone Street, Grey Lynn, Auckland', 'Simon Laurent', 'Principal / Director', 'askus@laurentlaw.co.nz', '09 630 0411', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed active immigration law firm (est. 1996). Now at Grey Lynn (7A Maidstone St). Current published inbox is askus@laurentlaw.co.nz (replaces the old personal slaurent@ direct address). Phone unchanged. Real office = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Laurent Law'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Link2 Group', 'Recruitment, logistics, warehousing & apparel re-working', 'https://www.link2services.com', '250+ staff', 'East Tamaki, Auckland (1000sqm warehouse)', NULL, NULL, 'rahul@link2services.com', '09 272 4700', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed and rebranded: original ''Link2 and Apparel Solutions'' is now Link2 Group - Apparel Solutions became Link2 Solutions. Operates a 1000sqm East Tamaki warehouse plus recruitment arm (250+ staff). Domain email retained (same active domain). Large warehouse + office = strong cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Link2 Group'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Lumify Work New Zealand', 'IT / ICT training centre and conference venue', 'https://www.lumifywork.com/en-nz/', NULL, 'Ground Floor, 338 Ponsonby Road, Ponsonby, Auckland 1011', NULL, NULL, NULL, '09 360 0338', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] REBRANDED: Auldhouse was acquired and now trades as Lumify Work NZ (Lumify Group). Same Ponsonby Rd training campus. Old leighr@auldhouse.co.nz almost certainly dead post-rebrand and no direct office inbox published on the contact page (enquiry form only) - left email blank rather than guess. Strong fit: training centre with classrooms, conference/venue space.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Lumify Work New Zealand'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Matrix Recruitment', 'Recruitment agency (industrial/warehouse focus)', 'https://www.matrixrecruitment.co.nz', 'small specialist agency', 'Unit 8, 203 Kirkbride Road, Airport Oaks, Auckland', 'Ross Upton', 'Principal / main contact', 'ross@matrixrecruitment.co.nz', '09 254 4800', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed active. Ross Upton still the named contact; email ross@matrixrecruitment.co.nz verified on the current contact page (general inbox qualitypeople@matrixrecruitment.co.nz also live). Airport Oaks office. Phone confirmed. Good office cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Matrix Recruitment'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'McDonald Vague', 'Accounting — insolvency, restructuring & business advisory', 'https://www.mvp.co.nz', 'Medium (specialist insolvency firm, multiple practitioners)', 'Auckland CBD (plus Hamilton office)', NULL, NULL, NULL, '09 303 0506', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed strongly trading — active site, current people page, Auckland + Hamilton offices, 20+ yrs. Good cleaning fit (established CBD office). Could not confirm the old pfinnigan@ inbox is still valid; use the mvp.co.nz contact form / reception to reach an office manager. Ranked A.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('McDonald Vague'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'McKay Knarston Ltd', 'Design/Engineering — consulting land surveyors & land development (part of Babbage Consultants group)', 'https://www.mkk.co.nz', 'Small–medium (surveying practice, now within Babbage group)', 'Level 1, 25 Anzac Street, Takapuna, Auckland', 'Margaret Tresadern', 'PA / office contact (per public listings)', NULL, '09 489 4102', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — live site, current people page, Takapuna office. Now part of the Babbage Consultants group. Old keith@ email not confirmed still valid; reach via mkk.co.nz. Solid office premises in Takapuna. Ranked A.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('McKay Knarston Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'MHK Chartered Accountants Ltd', 'Accounting — chartered accountants, audit & tax', 'https://www.aucklandaccountant.net.nz', '11-50 employees', '36 Sale St, Auckland CBD 1010', 'Barbara Stronach', 'Practice Manager', NULL, '09 379 8011', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — CBD office at 36 Sale St, 11-50 staff, current employee directory. Named Practice Manager (Barbara Stronach) is the ideal cleaning contact. Note: an old MHK legal entity shows ''struck off'' in a business directory (routine entity restructure) but the practice is clearly still operating. Old ianm@ email not confirmed; reach via practice manager / aucklandaccountant.net.nz. Strong fit — ranked A.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('MHK Chartered Accountants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Next Level POS', 'Point of sale / EFTPOS / cash-handling systems', 'https://nextlevelpos.co.nz', NULL, '21 Woolaston Place, Flat Bush, Auckland 2016', NULL, NULL, 'admin@nextlevelpos.co.nz', '09 277 2207 (also 0800 444 770)', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] REBRANDED: pointofsale.net.nz now 301-redirects to nextlevelpos.co.nz; Facebook confirms ''Next Level POS. Previously Point of Sale NZ''. Same phone (09 277 2207) as old record. Commercial premises in Flat Bush. Old beth@ email likely dead - use admin@ office inbox.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Next Level POS'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'North Harbour Preschool', 'Education/Childcare — full-day early childhood centre (licensed for 40)', 'http://northharbourpreschool.co.nz', 'Licensed for 40 children; staffed centre', '12 Laurina Road, Sunnynook, Auckland 0620', NULL, 'Owner/operator (Hirst family)', NULL, '09 479 2922', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — live site, current CareforKids/MyECE listings, ~24 yrs operating, family-owned. Childcare centres are strong recurring commercial-cleaning prospects. Old slingshot email likely stale; reach via northharbourpreschool.co.nz or phone for the centre manager. Ranked A on fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('North Harbour Preschool'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'ProDesigners Architects Ltd', 'Architecture / architectural design practice', 'https://www.prodesigners.co.nz', '~18 architects/designers (across Pacific offices; Auckland is head office)', '4th Floor, Pakuranga Plaza Tower, 10 Aylesbury Street, Pakuranga, Auckland', NULL, NULL, 'prodesigners@prodesigners.co.nz', '09 576 1214', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed active - head office in Pakuranga Plaza Tower. Old email still published on current site/NZIA listing. Real office premises, good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('ProDesigners Architects Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Rentex Ltd', 'Residential property management', 'https://www.rentex.nz', 'Small team', '7 Douglas Alexander Parade, Albany, Auckland 0632', 'Chris Skewes', 'Owner / Principal', NULL, '0800 736 839 (formerly 09 451 9521)', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active 30+ yr Auckland property manager, office in Albany. Primary domain now rentex.nz (old rentex.net.nz still referenced). Karl Skewes is a team member. No current public office inbox confirmed - did not guess email. Real office, good fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Rentex Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Ross Holmes Lawyers (Ross Holmes Virtual Lawyers Ltd)', 'Law firm - trusts, estates, property, commercial', 'https://rossholmeslawyers.com', 'Small specialist firm', '2 Airborne Road, Albany, Auckland 0632', 'Ross Holmes', 'Principal / Barrister & Solicitor', 'rossholmes@rossholmes.co.nz', '09 415 0099', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active - specialist Albany law firm since 1985, current practising certificate to 2027. Now trades as ''Ross Holmes Virtual Lawyers Ltd'' (main site rossholmeslawyers.com); rossholmes.co.nz email still valid/published. Note ''Virtual'' branding suggests possibly reduced physical footprint - verify premises before approach, but a real Albany office address is listed.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Ross Holmes Lawyers (Ross Holmes Virtual Lawyers Ltd)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'RPL Accountants Ltd', 'Chartered accountants / taxation / business advisory', 'https://www.rplnz.com', 'Medium-sized firm', 'VTR House, Level 1, 24 Manukau Road, Epsom, Auckland 1023', 'Peter Woodhead', 'Principal', NULL, '09 529 9150', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active medium-sized accountancy firm in Epsom, current site live. Key principal listed as Peter Woodhead (no ''Tony'' found - old tony@ contact may have left), so old email likely stale. No general office inbox captured - did not guess. Real office premises, strong cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('RPL Accountants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Rush Security', 'Security - alarm monitoring, CCTV, guards, patrols', 'https://rushsecurity.co.nz', 'Established (since 2002)', '52 Remuera Road, Newmarket, Auckland 1050', NULL, NULL, 'info@rushsecurity.co.nz', '09 377 4858 (site) / 09 523 7500 (old record)', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active - integrated security firm since 2002, office at 52 Remuera Rd Newmarket. Current site lists info@rushsecurity.co.nz (office inbox) and phone 09 377 4858, both differing from old record. Old chris.harris@ may be stale - use info@. Real premises, good fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Rush Security'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'S.M. Chan & Partners Ltd', 'Chartered accountants / tax consultants', 'https://www.taxconsultant.co.nz/', 'Small firm', 'Level 1, 169 Manukau Road, Epsom, Auckland 1023', 'Sam Chan', 'Principal Partner', 'info@taxconsultant.co.nz', '09 963 8898', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, real office premises in Epsom (Level 1). Since old record: new email info@taxconsultant.co.nz (old sam@taxadvisor.co.nz not shown on site), new phone 09 963 8898 (old 09 358 0884). Good cleaning fit - level-1 office suite.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('S.M. Chan & Partners Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'SalesStar Ltd', 'B2B sales coaching & training', 'https://salesstar.com/nz/', '~71 globally; NZ HQ office', '72 Taharoto Road, Belmont, Auckland 0622', NULL, NULL, 'success@salesstar.com', '09 524 0999', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading; NZ HQ office at Belmont/Takapuna, North Shore. Founded 2005. Published inbox now success@salesstar.com; old paulo@salesstar.com (founder Paul O''Donohue) may still work but office inbox preferred. Real premises, good fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('SalesStar Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Salta Property Law Ltd', 'Conveyancing / property lawyers', 'https://www.salta.co.nz/', 'Small firm', '208 Ponsonby Road, Ponsonby, Auckland 1011', NULL, NULL, 'admin@salta.co.nz', '09 360 2419', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, real office on Ponsonby Road. Phone unchanged (09 360 2419). Published office inbox admin@salta.co.nz preferred over old brit@salta.co.nz. Good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Salta Property Law Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Stainton Chellew', 'General practice law firm (property, commercial, family, litigation)', 'https://www.staintonchellew.co.nz/', 'Established mid-size firm', 'Level 6, 2 Emily Place, Auckland Central 1010', NULL, 'Reception', 'reception@sclawyers.co.nz', '09 373 2447', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, CBD office (Level 6, 2 Emily Place). Firm roots to 1920s. Phone unchanged (09 373 2447). Email domain shifted to sclawyers.co.nz - current reception@sclawyers.co.nz; old don@staintonchellew.co.nz likely stale. Strong fit - multi-floor CBD office.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Stainton Chellew'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Swayne McDonald Lawyers', 'General practice law firm (conveyancing, family, commercial)', 'https://smlaw.co.nz/', '6 lawyers + 2 legal executives', '236a Great South Rd, Manukau, Auckland 2102 (also Botany Junction office)', 'Audrey', 'Admin/reception contact', 'audrey@smlaw.co.nz', '09 267 2700', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading 30+ years; South Auckland firm with Manukau + Botany Junction offices. Phone and email appear unchanged from old record (audrey@smlaw.co.nz, 09 267 2700). Real premises, good fit. Re-confirm email on first contact.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Swayne McDonald Lawyers'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Tarzan Design Ltd', 'Architectural design & drafting', 'https://www.tarzandesign.co.nz/', '~8 employees', '22 Applewood Dr, Henderson, Auckland 0612', 'Bobby', 'Director / Creative Designer', 'bobby@tarzandesign.co.nz', '09 836 0576', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, real West Auckland studio in Henderson, ~8 staff. Phone and email unchanged from old record. Good cleaning fit - genuine office/studio with a team. Verify bobby@ inbox on outreach (still published on site).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Tarzan Design Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Wojcik & Wilgermein', 'Accountants / auditors / tax consultants', NULL, 'Boutique firm', 'Level 2, 17 Albert Street, Auckland CBD 1010', 'Kazimierz Wojcik', 'Principal / partner', NULL, '09 358 3800', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Boutique CBD accounting firm, Level 2 17 Albert St, phone unchanged, Silver Xero partner, listed on Heart of the City business directory. Could not verify a current published email — old kaz@ domain not confirmed live, so email left blank rather than guessed. Good cleaning fit (dedicated office suite).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Wojcik & Wilgermein'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Y6 (formerly Yellow6)', 'Interior architecture & design studio', 'https://y6.co.nz', '11-50', '57 Customs Street East, Auckland', NULL, NULL, 'info@y6.co.nz', '09 379 2479', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading. Rebranded from Yellow6 to Y—6; domain moved yellow6.co.nz -> y6.co.nz (301 redirect). Central-city Auckland studio premises on Customs St East. Phone unchanged from old record (09 379 2479). New office inbox info@y6.co.nz replaces the dead reg@yellow6.co.nz. Commercial/hospitality/retail design firm with real office space - good cleaning fit. No named office/ops manager published; fo...'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Y6 (formerly Yellow6)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Yip Associates Limited', 'Chartered accountants / tax consultants', 'https://www.yipassociates.co.nz', NULL, 'Suite 7B, 169 Harris Road, East Tamaki, Auckland 2013', 'Simon Yip', 'Director', 'simonyip@yipassociates.co.nz', '09 273 3296', 'ex-bc-networking', 'A', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed registered and active (NZBN 9429040992006, since 2013). Real suite/office premises in East Tamaki (address in use since Dec 2020). Old email still current and valid - Simon Yip is the sole director/named contact. Mobile also listed as 027 823 2873. Note: website SSL cert has expired (site reachable but browser will warn). Small accounting practice with a genuine office - fits cleaning prospect.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Yip Associates Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'ABA Chartered Accountants', 'Chartered accountants / tax and business advisory', 'https://www.aba.org.nz', NULL, 'Level 1, 178 Hibiscus Coast Highway, Red Beach, Auckland 0932', NULL, NULL, 'info@aba.org.nz', '09 426 8488', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading, same phone. Now brands as ''ABA Chartered Accountants''. Real office premises (Level 1, Red Beach). B rather than A only because it''s up on the Hibiscus Coast (far north of Auckland), so geographically thinner for a central-Auckland cleaning run. Verified office inbox info@aba.org.nz on the live contact page; old james@ personal email dropped.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('ABA Chartered Accountants'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'ABC Business Solutions Limited', 'Accountants / Tax Consultants', 'https://www.abcsolutions.co.nz/', 'Small SME accounting practice', '185 Great South Road, Papatoetoe, Auckland 2025 (Hunters Corner)', 'Nitika (Neetika) Chand', 'Accountant / Principal', 'taxconsult@xtra.co.nz', '09 279 1234', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading from a Papatoetoe office (Hunters Corner Town Centre; phone unchanged). Nitika Chand still listed at the firm on LinkedIn. Old personal email nitika.abc@xtra.co.nz likely stale; current published office email is taxconsult@xtra.co.nz. Accounting office premises = fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('ABC Business Solutions Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Adstaff', 'Recruitment Agency (temp & permanent)', 'https://adstaff.co.nz/', 'Founded 1981 (44+ yrs); South Auckland recruitment office', 'Unit 4B / 23 Ash Road, Manukau, Auckland 2104', NULL, NULL, NULL, '09 277 1743', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Originally Advance Management & Personnel Consultants, now branded Adstaff. South Auckland/Manukau recruitment office premises. Old email teena@adstaff.co.nz is on the still-live adstaff.co.nz domain so may still work, but I could not confirm a current published office inbox — did not invent one. Office premises = decent fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Adstaff'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Alan K Tong & Associates Limited', 'Chartered Accountants / Tax', 'https://www.tong.co.nz/', 'Small-to-mid accounting practice', '4 Boston Road, Mount Eden, Auckland 1023', NULL, NULL, NULL, '09 307 2342', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading from a Mt Eden office (listing updated Dec 2025, phone unchanged from old record). Accounting practice with office premises = fit. Old email was a personal xtra.co.nz address; could not verify a current published office inbox on their site, so left email blank rather than guess — best contact is the phone or the site contact form at tong.co.nz.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Alan K Tong & Associates Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Albert van Vliet Architectural', 'Architecture & Architectural Drafting', 'http://www.avva.co.nz/', 'Small studio (a group of designers)', '151 King Street, Pukekohe, Auckland 2120', 'Albert van Vliet', 'Principal / Architectural Designer', 'albert@avva.co.nz', '09 238 4648', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading from a Pukekohe (South Auckland region) studio; email and phone unchanged from the old record and still current on avva.co.nz. Residential & commercial architectural design. Studio premises = fit, though it is a small design office (South Auckland edge). Old email confirmed still valid.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Albert van Vliet Architectural'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'ASL Industries Ltd', 'Saw & Blade Sales / Sharpening (industrial engineering supplies)', 'https://www.aslindustries.co.nz/', '40+ yrs; ~$2M revenue; industrial workshop', 'Silverdale, Auckland (workshop; also a Ruakaka, Northland branch)', NULL, NULL, 'sales@aslindustries.co.nz', '0800 425574', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading (over 40 years; largest saw/blade sharpening operation in Auckland). Main workshop is in Silverdale (northern Auckland region), plus a Ruakaka branch. Old personal email karen@ replaced with current published sales@aslindustries.co.nz; primary number is now the 0800 line (old 09 426 6617 was the local Silverdale line). Industrial workshop premises = good cleaning fit. Exact Silverdale...'
where not exists (select 1 from public.sales_leads where lower(company) = lower('ASL Industries Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Auckland Chartered Accountants', 'Accounting — chartered accountants, audit, tax & business advisory', 'https://aucklandca.co.nz', 'Small practice', 'Level 1, 10 Manukau Road, Epsom, Auckland 1023', 'Greg Mason', 'Principal / founder', NULL, '09 524 9802', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] REBRANDED: Palmas Ltd now trades as Auckland Chartered Accountants (aucklandca.co.nz) — same practice, founder Greg Mason, has traded under the new name for 10+ yrs. Old palmas@xtra.co.nz almost certainly dead — use the aucklandca.co.nz contact form. Real office in Epsom. Ranked B (small firm, email needs replacing).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Auckland Chartered Accountants'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Crown Capital (Crown Financial Services Ltd / CFS Nominees)', 'Funds management / private equity / corporate finance', 'https://crowncapital.nz', 'Small (boutique PE/funds firm)', 'Level 5, 17 Albert Street, Auckland Central 1010', 'Marvin Yee', 'Managing Partner / Principal', NULL, '09 973 5888', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] CFS Nominees is part of Marvin Yee''s Crown Financial Services, now rebranded Crown Capital (crowncapital.nz). Confirmed real CBD office at Level 5, 17 Albert St; phone 09 973 5888 unchanged from old record. Could not retrieve a current published email (contact page 403''d) so left blank rather than guess - old marvin.yee@crownfinancial.co.nz may still route. Small firm but genuine office premises.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Crown Capital (Crown Financial Services Ltd / CFS Nominees)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'DRK Chartered Accountants Ltd', 'Chartered accountants', 'https://www.drk.co.nz', 'Small firm', 'Bombay and Waiuku, Auckland (Franklin district)', 'Kirsten Taylor-Ruiterman', 'Principal', NULL, '09 236 0437', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Rebranded from ''Duthie Taylor-Ruiterman'' to DRK Chartered Accountants; confirmed still trading via active website. Offices now Bombay & Waiuku (semi-rural southern Auckland/Franklin), not Papakura. Could not confirm a current published office inbox - did not carry the named principal email forward as verified. Thinner cleaning fit given rural/small offices.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('DRK Chartered Accountants Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'EAP Services Ltd (now Habit Health)', 'Employee assistance / workplace wellbeing', 'https://www.eapservices.co.nz', 'Large - national provider (200+ practitioners)', '34 Shortland Street, Auckland Central (also Takapuna & Manukau offices)', NULL, NULL, 'nsc@eapservices.co.nz', '0800 327 669', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Still trading but rebranded / merged into the Habit Health family. Multiple Auckland offices (Auckland Central, Takapuna, Manukau). Old personal email replaced with published national service centre inbox nsc@eapservices.co.nz. Large org, procurement likely centralised - hence B.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('EAP Services Ltd (now Habit Health)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Eftpos2go', 'EFTPOS / payment terminals supplier', 'https://www.eftpos2go.co.nz', 'Small business', '28 Hugo Johnston Drive, Penrose, Auckland 1061', NULL, NULL, 'jason@eftpos2go.co.nz', '09 525 4272', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading with real premises in Penrose (Auckland). Phone unchanged. Old email brendan@ replaced with currently-listed jason@ (published contact). Reasonable cleaning fit - office/warehouse in Penrose.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Eftpos2go'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Henley-Smith Law', 'Legal — general practice law firm (property, family, trusts, commercial)', 'https://henleysmithlaw.co.nz', 'Small firm (principal + small team)', 'Glen Eden, West Auckland (PO Box 20067, Glen Eden 0641)', 'Mark Henley-Smith', 'Principal', 'mark@henleysmithlaw.co.nz', '09 818 6153', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — live site, current team page. Small friendly general practice in Glen Eden with staffed office. Old email still valid. Ranked B on size.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Henley-Smith Law'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Investment Research Group (IRG)', 'Finance / investment banking / research house (NZX sponsor)', 'https://irg.co.nz', '11-50', 'Level 8, 115 Queen Street, Auckland Central 1010', NULL, NULL, NULL, '09 304 0145', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] The original record was ''Barter Fund Ltd'' with a brent.king@irg.co.nz email - Barter Fund itself is not confirmable as a live trading entity, but the associated business IRG (Investment Research Group, subsidiary of General Capital Ltd) IS actively trading with a CBD office on Queen Street. Kept as IRG. Could not verify a current published office inbox (form-based / general reception), so email left blank. B: r...'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Investment Research Group (IRG)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Jay Accounting and Taxation Ltd', 'Accountants / taxation consultants, office premises', NULL, 'Small (likely sole practitioner / very small)', '620 Manukau Road, Epsom, Auckland 1023', NULL, NULL, NULL, '09 625 0035', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Listed as trading at 620 Manukau Road, Epsom; phone 09 625 0035 unchanged. Old rajamani@xtra.co.nz not re-verified and no current website found, so no confirmed current email. Small practice — possibly a lighter cleaning prospect. Ranked B on thin confirmation.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Jay Accounting and Taxation Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Jon Gaskell Valuers Ltd', 'Registered property valuers / real estate, Hibiscus Coast office', 'https://www.gaskell.co.nz', 'Small valuation practice', '180 Vipond Road, Stanmore Bay, Whangaparaoa, Auckland (PO Box 75, Red Beach 0945)', 'Jon Gaskell', 'Registered public valuer / principal', 'jon@gaskell.co.nz', '09 428 0608', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed via Property Institute / directory listings; phone 09 428 0608 and gaskell.co.nz unchanged. Covers Hibiscus Coast/Rodney. Small practice, possibly home-office-adjacent — ranked B. Old email domain still live so jon@gaskell.co.nz likely valid.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Jon Gaskell Valuers Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Kings Recruitment Ltd', 'Recruitment agency', 'https://www.kingsrecruitment.co.nz', 'small generalist recruiter (est. 2009)', 'Level 2, 19 Great South Road, Epsom, Auckland 1051', NULL, NULL, NULL, '09 815 8444', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed still trading from a real Epsom office. No public office/admin email found on current site (contact via phone / 0800 FOR JOBS / LinkedIn); no named contact published. Old ''lisa@'' email is unverified and likely stale - not carried forward as current. Office premises = good cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Kings Recruitment Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Kip McGrath Manurewa', 'Education / tutoring centre', 'https://www.kipmcgrath.co.nz', 'small franchise centre', '1st Floor, 25 Station Road, Manurewa, Auckland', NULL, NULL, NULL, '09 267 8392', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading with real premises at 25 Station Rd, Manurewa. Old ihug.co.nz email is a dead ISP domain - not carried forward. No current published centre email found; contact via phone or the national site. Small tuition centre.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Kip McGrath Manurewa'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Kip McGrath Tutoring Howick', 'Education / tutoring centre', 'https://www.kipmcgrath.co.nz', 'small franchise centre', 'Unit 9a, 219 Moore Street, Howick, Auckland', NULL, NULL, NULL, '027 271 1013', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading with real premises at 219 Moore St, Howick. Old landline (09 534 1620) is stale - current contact is a mobile (027 271 1013). Old personal email unverified; franchise may have changed hands - no current published centre email found. Small tuition centre = modest cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Kip McGrath Tutoring Howick'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'KiwiLawyers', 'Law firm (general/commercial, conveyancing, immigration)', 'https://www.kiwilawyers.co.nz', 'small suburban firm', 'Main Street, Otahuhu, Auckland', 'Taufil Omar', 'Principal', 'taufil@kiwilawyers.co.nz', '09 270 8595', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed still listed and trading; principal Taufil Omar, opened Otahuhu 2009. Small suburban law office - real premises, modest cleaning fit. Kept original email as it matches the firm domain and principal, but not independently re-verified as active.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('KiwiLawyers'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Mark Donovan Barrister', 'Legal — barrister (employment law / civil litigation)', 'https://markdonovan.co.nz', 'Small (sole barrister + support)', 'Ground Floor, 155 Fanshawe St, Auckland CBD (also cites 2 Chancery St chambers)', 'Mark Donovan', 'Barrister / Principal', 'mail@markdonovan.co.nz', '09 550 9854', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed actively trading, live website and current listings. Old email still valid. Sole practitioner barrister in city chambers — small footprint, so ranked B. CBD office premises.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Mark Donovan Barrister'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Murray Sharma & Associates Ltd', 'Accounting — accountants & business advisors', 'https://murraysharma.co.nz', 'Boutique firm (small team)', '5 Rata St, New Lynn, Auckland 0600', 'Navin Sharma', 'Founder / Principal', 'navin@murraysharma.co.nz', '09 827 6872', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — live site, New Lynn office, 25+ yrs. Old navin@ email appears still current (matches published contact). Boutique/small so ranked B, but a real staffed office premises. Good fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Murray Sharma & Associates Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Platinum IT Ltd', 'IT services — computer network support & managed IT (NOT childcare; original ''cat'' field was mislabelled)', 'http://platinumit.co.nz', 'Small IT firm', '766 Sandringham Road Ext, Mt Roskill, Auckland 1041', NULL, NULL, 'info@platinumit.co.nz', '09 620 2090', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading — live site, current listing with Mt Roskill office address. Replaced the old personal agibbons@ email with the published office inbox info@platinumit.co.nz. Real premises. Ranked B (small).'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Platinum IT Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Primesoft NZ Ltd', 'Software development / general IT services (BMS software)', 'https://primesoft.co.nz', 'Small', '63 Roberton Rd, Avondale, Auckland', 'Greg Stevenson', 'Owner', NULL, '09 820 8272', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active software/IT company in Avondale, Auckland (site + Yelp/Neighbourly current). Owner Greg Stevenson per about page - old greg@ email plausibly still valid but not re-confirmed, left email blank rather than guess. Small IT firm; modest cleaning fit.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Primesoft NZ Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Property Apprentice', 'Property investment education / coaching', 'https://www.propertyapprentice.co.nz', 'Small family-owned (Paul & Debbie Roberts + coaches)', 'Auckland (office - runs in-classroom courses at their Auckland office)', 'Paul Roberts', 'Founder & Managing Director', NULL, '09 575 7736', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active - family-owned property education firm running weekly in-person courses from an Auckland office. Domain moved from .com to .co.nz. Small owner-operated; has office premises so kept, but confirm exact address before approach. No current public office inbox found - did not guess.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Property Apprentice'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Prosperity Partners', 'Boutique investment advisory / financial planning (not accounting)', 'https://prosperitypartners.co.nz', 'Boutique', 'Takapuna, Auckland', NULL, NULL, 'client.team@prosperitypartners.co.nz', '09 488 9320', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Active boutique investment advisory firm in Takapuna. Note category correction: they are financial planners/investment advisors, NOT accountants as the old record said. Old client.team@ email still on current site. Exact street address not captured - confirm before approach.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Prosperity Partners'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Total Computers', 'IT support / computer network services', 'https://www.pchelp.co.nz', 'Small', '2/46 Sandgate Avenue, Botany Downs, Auckland', NULL, NULL, 'info@pchelp.co.nz', '09 533 7373', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading (site live, phone unchanged since original record). Current published inbox is info@pchelp.co.nz. Premises at 2/46 Sandgate Ave, Botany Downs — small commercial/suburban unit, so a modest but real office. Ranked B: real but small.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Total Computers'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Wentworth College & Primary', 'Independent school (Years 1-13)', 'https://wentworth.school.nz', 'Small independent school', '65 Gulf Harbour Drive, Gulf Harbour, Auckland', NULL, NULL, 'enquiries@wentworth.school.nz', '09 424 3273', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading. Independent school with real campus premises at Gulf Harbour (college 65, primary 95 Gulf Harbour Drive). Old enquiries@ email still valid. Ranked B rather than A because Gulf Harbour is far north Auckland and schools often have incumbent cleaning contracts; genuine premises though.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Wentworth College & Primary'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Working Capital Solutions', 'Invoice finance / business financier', 'https://working-capital.co.nz', 'Small', '13 Dockside Lane, Auckland Central 1010', NULL, NULL, NULL, '09 307 6609', 'ex-bc-networking', 'B', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading (listing updated 2025, phone unchanged). Note the old workingcapital.co.nz domain no longer resolves — site moved to working-capital.co.nz. Office at 13 Dockside Lane, Auckland Central (Viaduct area). No current public email found, so left blank rather than guessed; old edward@ address is on the dead domain and should not be relied on.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Working Capital Solutions'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Be Intent Limited', 'Employee wellbeing / team development software (SaaS); training & development', 'https://www.beintent.com', 'small', 'Auckland (no verified street premises found)', 'Suzanne Hall', 'CEO / Founder', 'suzanne@beintent.com', '09 368 7779', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Still exists (founded 2009, Suzanne Hall) but has pivoted from team-building consulting to cloud-based employee-wellbeing SaaS tools. Could not confirm a real staffed office/premises in Auckland - reads like a lean/founder-led software operation, which is a weak cleaning prospect. C, borderline. Old suzanne@ personal email is the only contact and its current validity is unverified. Flagging for Mike to judge - ...'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Be Intent Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Charter Financial Services Ltd', 'Accountants / cloud accounting for SMEs', 'http://www.companydoctors.com', 'Multi-city (Auckland/Hamilton/Wellington)', 'Auckland (no street address published)', 'Xin Qiu', 'Head of Client Manager - Auckland', 'charter@companydoctors.com', '09 358 3350', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed still trading; operates across Auckland/Hamilton/Wellington. BUT their model is cloud/Skype-based ''client managers who come to you'' with no published Auckland street office, so a real cleanable premises is unconfirmed. Old email still shown as live. Weak cleaning fit / uncertain premises - ranked C.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Charter Financial Services Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Eftpos Concepts (NZ) Limited', 'EFTPOS / cash register supplier', NULL, 'Small business', 'Unit 3A, 65 Paul Matthews Road, Rosedale, Auckland 0632', NULL, NULL, NULL, '09 269 6207', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Appears to still be trading - active Yellow listing and current OpenCorporates registration (registered 2007). Could not confirm a live website or currently-published office email, so did not carry old peter@ forward as verified. Thin/uncertain - ranked C. Old 09 268 0202 superseded by listed 09 269 6207.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Eftpos Concepts (NZ) Limited'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Eugene St John', 'Barrister (sole practitioner / chambers)', NULL, 'Sole barrister', 'O''Connell Chambers, Auckland City (PO Box 105270, Auckland City)', 'Eugene St John', 'Barrister', 'barrister@estjohn.co.nz', '09 358 1552', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed still practising - current NZLS practising certificate (issued 01/07/2025). But a sole barrister in shared chambers with only a PO box - one-person operation, weak cleaning fit / no dedicated office. Kept but ranked C; borderline prospect.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Eugene St John'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Property Tools (NZ) Ltd', 'Property consultants', NULL, 'Very small (2 directors: Garth & Cheryl Cutfield)', 'Suite 11, 630 Great South Road, Papatoetoe, Auckland 2025', 'Garth Cutfield', 'Director', NULL, '09 520 4636', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Company still registered/active on NZ register at Papatoetoe suite, directors Garth & Cheryl Cutfield since 2002. BUT propertytools.co.nz no longer resolves (DNS fail) - website dead, so old garth@ email is almost certainly dead too. Reads like a tiny 2-person consultancy. Kept as C on registration only; trading intensity uncertain.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Property Tools (NZ) Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Rutherford Legal Ltd', 'Lawyers / conveyancing (barrister & solicitor)', 'https://www.rutherfordlegal.co.nz', 'Very small / solo', 'Suite 507, Level 5, 350 Queen St, Auckland 1010', 'Geoff Levy', 'Barrister & Solicitor', 'geoff.levy@neumegenlaw.co.nz', '021 688 315', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Appears to still trade - Geoff Levy operates Rutherford Legal, associated with Neumegen & Co. Suite 507 on Queen St. Thin/uncertain: looks like a solo barrister-solicitor using a shared/serviced-office suite, so likely a light cleaning prospect. Old email still the only published one. Ranked C on fit + size uncertainty.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Rutherford Legal Ltd'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'University of Auckland Business School (Executive Education)', 'University / executive education', 'https://www.exec.auckland.ac.nz', 'Large institution', 'Sir Owen G Glenn Building, 12 Grafton Road, Auckland CBD', NULL, NULL, NULL, '09 373 7599', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Confirmed trading with real premises (Owen Glenn Building, 12 Grafton Rd). Old c.pimenta@ personal staff address not verified as still active; use the exec-ed contact page (exec.auckland.ac.nz/contact-us) instead. Ranked C on FIT, not existence: a university this size buys cleaning via large facilities-management tenders, so it''s a weak match for a networking-directory cold approach — but it is genuinely tradin...'
where not exists (select 1 from public.sales_leads where lower(company) = lower('University of Auckland Business School (Executive Education)'));

insert into public.sales_leads (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, source, quality_rank, status, notes)
select 'Wright Wiseman Law', 'Law firm / conveyancing / property law', NULL, 'Sole practitioner / very small', '79 Ranfurly Road, Epsom, Auckland', NULL, NULL, 'candowright@xtra.co.nz', '09 630 2768', 'ex-bc-networking', 'C', 'new', '[Ex-BC networking contact, re-verified still trading Aug 2026] Still listed and contactable at 79 Ranfurly Rd, Epsom, phone unchanged; old xtra.co.nz email still the published address. Ranked C: very small firm at what looks like a residential/home-office address in Epsom, so premises fit is uncertain. Kept because it still appears to be operating, but thin.'
where not exists (select 1 from public.sales_leads where lower(company) = lower('Wright Wiseman Law'));

commit;
