-- Sales leads seed #4 — Auckland golf clubs (focused batch), 2026-07-05.
-- 12 leads, all with named club managers: 7 A / 5 B. Golf clubs publish gm@
-- addresses as an industry norm; clubhouses = function rooms, bars, changing
-- rooms, pro shops, and several run wedding/conference venue operations.
-- Excluded after verification: Gulf Harbour (closed 2023), Auckland GC
-- (merged into RAGGC), Manukau GC (relocated to Windross Farm), Formosa
-- (Rydges hotel group - in-house housekeeping), Takapuna/Whitford/Peninsula/
-- Aviation (no named manager publishable). Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
('Royal Auckland & Grange Golf Club','other','https://raggc.com','50-100','57 Grange Road, Papatoetoe, Auckland 2025','Ed Chapman','Chief Executive Officer','admin@raggc.com','+64 9 975 6330','https://nz.linkedin.com/in/edchapmanclubindustryleader','Research 2026-07-05 r4 golf','B','new','NZ''s premier Royal club (Auckland GC + Grange merger), ~60 staff, 2000+ members, dedicated Functions & Events operation. CEO named via LinkedIn/CMAE; no direct email on club site.'),
('Remuera Golf Club','other','https://www.remueragolfclub.com','20-50','120 Abbotts Way, Remuera, Auckland','Chris Davies','General Manager','enquiries@remueragolfclub.com','+64 9 524 4288',NULL,'Research 2026-07-05 r4 golf','B','new','Dedicated hospitality/events centre for weddings + corporate (events@remueragolfclub.com). CAUTION: club has advertised a Chief Executive role via recruiters - confirm Davies still in seat before outreach.'),
('Titirangi Golf Club','other','https://www.titirangigolf.co.nz','20-50','11 Links Road, New Lynn, Auckland 0640','Richard Nauck','General Manager','golfoperations@titirangigolf.co.nz','+64 9 827 5749','https://nz.linkedin.com/in/nauck','Research 2026-07-05 r4 golf','B','new','NZ''s only Alister MacKenzie course; clubhouse bar/cafe + function rooms to ~180 guests. Directory listings suggest manager@titirangigolf.co.nz for the GM (not on club site - try alongside published address). West AKL cluster.'),
('North Shore Golf Club','other','https://northshoregolfclub.co.nz','20-50','51 Appleby Road, Albany, Auckland 0632','David Herbert','General Manager','david@nsgc.co.nz','+64 9 415 9924',NULL,'Research 2026-07-05 r4 golf','A','new','27 holes, ~1200 members, 75-85k rounds/yr - very high clubhouse traffic + functions. GM''s direct email published on club''s own contact page; one of NZ''s few CCM-qualified managers. Albany cluster.'),
('Pakuranga Golf Club','other','https://www.pakurangagolf.co.nz','20-50','199 Botany Road, Golflands, Auckland 2013','Sam Abela','General Manager','admin@pakurangagolf.co.nz','+64 9 534 3818',NULL,'Research 2026-07-05 r4 golf','B','new','On-site Bar & Function Centre marketed for weddings + corporate (functions: catering@pakurangagolf.co.nz). GM named on club''s own people page. East AKL cluster.'),
('Howick Golf Club','other','https://www.howickgolf.co.nz','20-50','32 Musick Point Road, Bucklands Beach, Auckland','Shandon Carter','General Manager','gm@howickgolf.co.nz','+64 9 535 1001',NULL,'Research 2026-07-05 r4 golf','A','new','Clifftop clubhouse at Musick Point; group bookings + corporate events, dedicated functions coordinator (Mark Gallagher, functions@howickgolf.co.nz) as second entry point. GM email published on own site.'),
('Akarana Golf Club','other','https://www.akaranagolf.co.nz','20-50','1388 Dominion Road, Mt Roskill, Auckland 1041','John McGregor','General Manager','gm@akaranagolf.co.nz','+64 9 621 0024',NULL,'Research 2026-07-05 r4 golf','A','new','Full staff directory published; Sprig Bar venue hire (Amit Kumar, bar@akaranagolf.co.nz) + corporate golf days. GM email published on own site.'),
('Maungakiekie Golf Club','other','https://www.maungakiekiegolf.co.nz','20-50','5 Anita Avenue, Mount Roskill, Auckland 1041','Rebecca Smith','Club Manager','gm@maungakiekiegolf.co.nz','+64 9 621 0090','https://nz.linkedin.com/in/rebecca-smith-422bb513a','Research 2026-07-05 r4 golf','A','new','Corporate golf, corporate functions + private events; on-site Tambo Eatery. gm@ published on own contact page; manager name via LinkedIn.'),
('Windross Farm Golf Course','other','https://www.windrossfarm.co.nz','20-50','237 Alfriston-Ardmore Road, Ardmore, Auckland 2582','Andrew Laird','General Manager','gm@windrossfarm.co.nz','+64 9 281 5414',NULL,'Research 2026-07-05 r4 golf','A','new','Championship course (2017 LPGA NZ Women''s Open); now home of relocated Manukau GC. Hospitality page, corporate golf days, TopTracer range. gm@ published on own site. South AKL cluster.'),
('Muriwai Golf Club','other','https://www.muriwaigolfclub.co.nz','20-50','101 Coast Road, Muriwai 0842, Auckland','Andrew Jackson','General Manager','gm@muriwaigolflinks.co.nz','+64 9 411 8454',NULL,'Research 2026-07-05 r4 golf','A','new','Links course + clubhouse venue hire (dedicated enquiry form). GM won Golf NZ club manager of the year (2022 press) - re-verify still in role at first contact. gm@ published on own site.'),
('Pupuke Golf Club','other','https://www.pupuke.co.nz','20-50','231 East Coast Road, Campbells Bay, Auckland 0630','Matthew Owen','General Manager','gm@pupukegolf.co.nz','+64 21 859 822',NULL,'Research 2026-07-05 r4 golf','A','new','BEST HOOK IN BATCH: newly renovated clubhouse hired to members AND non-members (bar, cafe, bistro, on-site caterer) - fresh fit-out worth protecting. GM''s direct mobile published on club''s own FAQ page. Alt: Daniele Lowe, Head of Golf & Commercial (golf@pupukegolf.co.nz). North Shore cluster.'),
('Waitemata Golf Club','other','https://www.waitematagolf.co.nz','10-30','15 Derby Street, Devonport, Auckland 0624','Jamie Palmer','General Manager','admin@waitematagolf.co.nz','+64 9 445 8716','https://www.linkedin.com/in/jamie-palmer-39b51a126/','Research 2026-07-05 r4 golf','B','new','GM appointed 2024 (ex-Gulf Harbour) - newer manager likely reviewing suppliers. Historic Devonport clubhouse. Devonport cluster.');
