-- Sales leads seed #2 — Auckland commercial research round 2, 2026-07-05.
-- 26 leads: 7 professional services (QS/planning/valuation/IP/PM), 3 construction
-- head offices, 2 developers/property, 2 surveying/land-development, 4 tech,
-- 3 media/production/creative, 4 financial boutiques, 2 real-estate head offices...
-- grouped below by research batch. Ranks: 5 A / 15 B / 6 C.
-- Same rules as seed #1: nothing invented; NULL where nothing is published.
-- No overlap with the 58 leads in 2026-07-05-sales-leads-seed.sql.
-- Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── PROFESSIONAL / CONSTRUCTION / PROPERTY (13) ─────────────────────────────
('Rider Levett Bucknall (Auckland)','professional','https://www.rlb.com/oceania/offices/auckland/','50-100','Level 16, Vero Centre, 48 Shortland Street, Auckland 1010','Steve Gracey','Managing Director, Auckland','steve.gracey@nz.rlb.com','+64 9 309 1074','https://www.linkedin.com/company/rider-levett-bucknall-3','Research 2026-07-05 r2','A','new','NZ''s largest quantity surveying business (their words); AKL MD''s direct email published on the firm''s own office page. Vero Centre L16 - same building as Delta Insurance (L22) and Northington Partners (L33): three targets, one tower.'),
('Prendos New Zealand','professional','https://prendos.co.nz','100-150','Level 8, PD Insurance House, 5-7 Byron Avenue, Takapuna, Auckland 0622','Mike Woods','Director & Auckland Regional Manager','mike.woods@prendos.co.nz','+64 9 970 7070','https://nz.linkedin.com/company/prendos','Research 2026-07-05 r2','A','new','RICS-regulated property/building consultancy, ~101 staff, Takapuna HQ. COO Steven Woodman also publishes direct email steven@prendos.co.nz + mobile 021 704 471 on own site. Takapuna cluster.'),
('Barnes Beagley Doherr','professional','https://bbd.co.nz','40-60','Level 8, Shortland Chambers, 70 Shortland Street, Auckland 1010','Scott Beagley','Director','scottb@bbdnz.co.nz','+64 9 379 6174','https://nz.linkedin.com/company/bbdnz','Research 2026-07-05 r2','A','new','Independent NZ-owned construction cost consultancy (est. 2013); every director publishes a direct email + mobile on the people page. Confirm Scott is AKL-based before sending (site does not split AKL/CHC).'),
('Barker & Associates','professional','https://barker.co.nz','50-100','Level 4, Old South British Building, 3-13 Shortland Street, Auckland CBD','Paige George','Team Administrator (Auckland office)','PaigeG@barker.co.nz','+64 27 217 7940','https://nz.linkedin.com/company/barkerandassociates','Research 2026-07-05 r2','A','new','One of NZ''s largest planning consultancies. The AKL office administrator - the person who would manage a cleaning contract - is the published office contact with direct email + mobile. Same building as Architectus (3-13 Shortland St). General: Admin@barker.co.nz / 09 375 0900.'),
('Kalmar Construction','construction','https://kalmar.co.nz','100-150','Level 2, 4 Fred Thomas Drive, Takapuna, Auckland 0622','Louise Shaw','Business Operations Manager','info@kalmar.co.nz','+64 9 489 3470','https://nz.linkedin.com/company/kalmar-construction-limited','Research 2026-07-05 r2','B','new','Award-winning AKL builder since 2001; head-office support team (Business Ops Manager, HR Manager, Office Administrator) all named on team page. Same building as Riley Consultants (4 Fred Thomas Dr).'),
('Haydn & Rollett','construction','https://haydnrollett.co.nz','50-150','1 The Warehouse Way, Northcote, Auckland','Frank Simons','Operations General Manager','info@haydnrollett.co.nz','+64 9 444 7379','https://nz.linkedin.com/company/haydnrollett','Research 2026-07-05 r2','B','new','75+ year AKL construction + property-services firm; multi-division Northcote head office. Property Services GM Craig McGuigan is a second internal buyer under one roof.'),
('NZ Strong Group','construction','https://www.nzstrong.co.nz','50-150','108 Mt Eden Road, Mt Eden, Auckland','Chris Hunter','Managing Director','info@nzstrong.co.nz','+64 9 630 7324','https://nz.linkedin.com/company/nz-strong-construction','Research 2026-07-05 r2','B','new','Design-and-build contractor founded 2004; corporate head office on Mt Eden Rd with in-house finance/design/admin teams.'),
('Safari Group','property','https://safarigroup.co.nz','40-60','3a Graham St, Auckland Central 1010','Robert Neil','Director & Co-founder','customercare@safarigroup.co.nz','+64 9 358 1735','https://nz.linkedin.com/company/safari-group-nz','Research 2026-07-05 r2','B','new','Family-owned developer-builder-hotel operator (~$500m pipeline per NZ Herald); CBD head office on Graham St.'),
('Woods (Wood & Partners Consultants)','engineering','https://woods.co.nz','100-150','Building B, Level 1, 8 Nugent St, Grafton, Auckland 1023','David Kidd','Chief Executive Officer','info@woods.co.nz','+64 9 308 9229','https://nz.linkedin.com/company/woods-engineering-consultant','Research 2026-07-05 r2','B','new','Surveying/engineering/planning consultancy est. 1970, AKL-founded and HQ''d in Grafton (200+ national incl. 100+ engineers).'),
('Cato Bolam Consultants','engineering','https://catobolam.co.nz','40-60','89 Central Park Drive, Henderson, Auckland','John Wisker','Director - manages Henderson office','catobolam@catobolam.co.nz','0800 222 862','https://nz.linkedin.com/company/cato-bolam-consultants-ltd','Research 2026-07-05 r2','B','new','Land development consultancy est. 1972; Henderson HQ + Orewa/Kumeu/Waiheke offices - multi-site angle. West Auckland cluster with UHY, Smith and Partners, ICIB Henderson.'),
('RCP','professional','https://rcp.co.nz','100-150','25 Hargreaves St, Freemans Bay, Auckland 1011','Rachel Orchard','Chief Operating Officer',NULL,'+64 9 379 9250','https://nz.linkedin.com/company/rcp','Research 2026-07-05 r2','B','new','100% locally owned project-management consultancy (170+ national, 8 offices); standalone Freemans Bay premises. No email published anywhere on their site - phone/form only.'),
('Seagars (Seagar & Partners)','professional','https://www.seagars.co.nz','20-30','Level 8, 66 Wyndham Street, Auckland 1010 + Botany Junction office','Ian Colcord','Director','info@seagars.co.nz','+64 9 309 2116','https://nz.linkedin.com/company/seagar-&-partners','Research 2026-07-05 r2','B','new','One of NZ''s largest private valuation practices (est. 1981); two AKL offices (CBD + Botany Junction) - tidy two-site contract. Same building as ICIB (66 Wyndham St).'),
('James & Wells','professional','https://www.jamesandwells.com/nz/','50-100','Level 2, 123 Carlton Gore Road, Newmarket, Auckland 1023','Jennifer Lucas','Partner, Auckland office','info@jamesandwells.com','+64 9 914 6740','https://nz.linkedin.com/company/james-&-wells-ip','Research 2026-07-05 r2','B','new','IP/patent attorney firm est. 1979; Newmarket tenancy next door to Moore Markhams (103 Carlton Gore Rd). No ops manager published.'),
-- ── TECH / MEDIA / FINANCE / REALTY HEAD OFFICES (13) ───────────────────────
('South Pacific Pictures','office','https://www.southpacificpictures.com','100-150','8 Tolich Place, Henderson, Auckland 0610','Melanie Jones','Studio Manager (facilities + H&S)','studiomanager@spp.co.nz',NULL,'https://nz.linkedin.com/company/south-pacific-pictures','Research 2026-07-05 r2','A','new','NZ''s biggest TV production company (Shortland Street); purpose-built Henderson studio complex occupied since 2000. Facilities + H&S sit with the named Studio Manager whose role inbox is published on their own contact page. General: connect@spp.co.nz. West Auckland cluster.'),
('Images & Sound','office','https://www.imagesandsound.co.nz','20-50','113 Grafton Road, Grafton, Auckland 1010','Catherine Burrell','Administration Manager','info@imagesandsound.co.nz','+64 9 309 8026','https://nz.linkedin.com/company/images-&-sound','Research 2026-07-05 r2','B','new','NZ''s most established post-production facility (40+ years); own Grafton building full of sensitive technical spaces (Dolby Atmos theatres, grading suites) - trustworthy careful cleaning is a genuine selling point. Near Woods (Grafton).'),
('Motion Sickness','office','https://motionsickness.company','20-40','Level 1, 13 Maidstone Street, Grey Lynn, Auckland 1021','Alex McManus','Co-founder & General Manager','contact@motionsickness.company','+64 9 523 0370','https://nz.linkedin.com/company/motion-sickness-studio','Research 2026-07-05 r2','B','new','TIMING: high-profile independent creative agency that moved into its own fitted-out Grey Lynn HQ late 2024 - new premises they are proud of. GM named in NZ Herald press (handles admin/financial side), not on own site.'),
('Serato','office','https://serato.com','50-100','Level 2, 8 Brown Street (Ponsonby Central), Ponsonby, Auckland 1021',NULL,NULL,'sales@serato.com',NULL,'https://nz.linkedin.com/company/serato-ltd','Research 2026-07-05 r2','C','new','NZ-founded DJ software company; 1,400 sqm office across two floors of Ponsonby Central incl. DJ stations, band room, music studio - specialist spaces where careful cleaning matters. Departmental emails only on contact page.'),
('Parkable','office','https://parkable.com/en-nz','20-50','Suite G.5, 317 New North Road, Kingsland, Auckland 1021','Josh Baker','Director of Operations',NULL,'+64 9 320 3418','https://nz.linkedin.com/company/parkable','Research 2026-07-05 r2','B','new','Parking-management SaaS (clients incl. Meta, KPMG, JLL); Kingsland ground-floor suite. THREE named ops/people decision-makers on own team page (also Steve Cooper CFOO, Kate Larmer Head of People). Form + phone only. Near Context Architects (Kingsland).'),
('Joyous','office','https://www.bejoyous.ai','30-50','Level 3, Dilworth Building, 22 Queen Street, Auckland CBD (third-party sourced - VERIFY tenancy)',NULL,NULL,NULL,NULL,'https://nz.linkedin.com/company/joyous','Research 2026-07-05 r2','C','new','Established NZ HR-tech company (~40 staff, offices AKL/AU/US). Own site publishes no address/phone/email (form only); address from ZoomInfo - confirm before visit.'),
('Fergus','office','https://fergus.com/nz','50-100','Level 1, 65 New North Road, Eden Terrace, Auckland 1021',NULL,NULL,NULL,'0800 461 219','https://nz.linkedin.com/company/fergus-software-limited','Research 2026-07-05 r2','C','new','NZ job-management software for trades (20,000+ tradie users); own floor in Eden Terrace. ANGLE: sells software to trades businesses - a well-run local trades supplier pitch lands naturally. Near eCubed (Eden Terrace).'),
('Squirrel','finance','https://www.squirrel.co.nz','50-100','29 Sale Street, Auckland CBD (head office)','Lauren De Witt','Chief Operating Officer',NULL,'+64 9 376 9688','https://nz.linkedin.com/company/squirrel-mortgage-brokers','Research 2026-07-05 r2','B','new','NZ''s largest independent mortgage broker + savings/investment platform; AKL head office at 29 Sale St. COO named on own leadership page; only complaints@/media@ emails published - phone is the entry point.'),
('Delta Insurance','finance','https://deltainsurance.co.nz','50-100','Level 22, 48 Shortland Street, Auckland 1010','Nathan Barrett','Group Chief Operating Officer','contactus@deltainsurance.co.nz','+64 9 300 0160','https://nz.linkedin.com/company/delta-insurance-new-zealand','Research 2026-07-05 r2','B','new','Locally owned specialist underwriting group (liability/cyber), HQ on Vero Centre L22 - same tower as RLB (L16) and Northington (L33). Group COO named in trade press with an ops-refinement mandate.'),
('NZ Funds Management','finance','https://www.nzfunds.co.nz','20-50','Level 16, Zurich House, 21 Queen Street, Auckland 1010',NULL,NULL,NULL,'+64 9 377 2277','https://nz.linkedin.com/company/nz-funds-management','Research 2026-07-05 r2','C','new','Established private wealth manager (KiwiSaver + portfolios); Zurich House L16 - same street number cluster as Generate + William Buck (21 Queen St). Contact page JS-rendered; email unverified.'),
('Northington Partners','finance','https://northington.co.nz','20-30','Level 33, Vero Centre, 48 Shortland Street, Auckland 1010',NULL,NULL,NULL,'+64 9 913 4600','https://nz.linkedin.com/company/northington-partners','Research 2026-07-05 r2','C','new','Independent investment bank / corporate advisory boutique (mid-market M&A) on a premium Vero Centre floor - exactly the client-facing office where presentation matters. Third target in the Vero Centre.'),
('Barfoot & Thompson (Support Centre)','property','https://www.barfoot.co.nz','100+','34 Shortland Street, Auckland 1010',NULL,NULL,NULL,'+64 9 307 6300','https://nz.linkedin.com/company/barfoot-&-thompson','Research 2026-07-05 r2','C','new','Family-owned AKL real estate group; target is the Support Centre floors (senior management, Training, Auctions, PM Support) at 34 Shortland St - not branch shopfronts. Phone reception is the entry point.'),
('Ray White New Zealand (Corporate Office)','property','https://www.raywhite.co.nz','20-50','Level 2, 12 Viaduct Harbour Avenue, Auckland 1010','Stephanie Watson','Head of Franchise Operations','corporate.nz@raywhite.com','+64 9 377 5069','https://www.linkedin.com/company/raywhitegroup','Research 2026-07-05 r2','B','new','NZ corporate HQ for the Ray White franchise network (head-office floor only; branches independently owned). Leadership page also lists an Executive Assistant (Mitch Kinney) who likely handles office suppliers.');
