-- Sales leads seed #3 — Auckland commercial research round 3 (quality pass), 2026-07-05.
-- 49 leads: 14 law (second sweep), 11 chambers/IP/legal-adjacent bodies,
-- 12 body corporate/property/associations, 12 boutique consultancies.
-- Ranks: 30 A / 17 B / 2 C — A-rank = named ops decision-maker with a direct
-- channel (their own email/DDI/mobile) published on the organisation's own site.
-- Property Council NZ was found by two researchers; merged into one row here.
-- Same rules as seeds #1/#2: nothing invented; NULL where nothing published.
-- No overlap with the 84 leads already loaded. Run once, after the schema file.

INSERT INTO public.sales_leads
  (company, industry, website, staff_size, address, contact_name, contact_role, email, phone, linkedin_url, source, quality_rank, status, notes)
VALUES
-- ── LAW, SECOND SWEEP (14) ───────────────────────────────────────────────────
('Kayes Fletcher Walker','law','https://www.kfw.co.nz','80-90','Level 4, MIT Building, cnr Davies Ave & Manukau Station Rd, Manukau 2104','Alana Podbielski','Practice Manager','alana@kfw.co.nz','+64 9 980 0336',NULL,'Research 2026-07-05 r3','A','new','Office of the Manukau Crown Solicitor - ~85 staff, single stable South AKL site. PM''s direct email + DDI on firm''s own people page. Also published: Finance Manager Malia Latu (malia@kfw.co.nz / 09 980 0310). General: 09 980 0300.'),
('Denham Bramwell Lawyers','law','https://www.denhambramwell.co.nz','30-50','Level 4, 3 Osterley Way, Manukau City Centre 2104 (also Albany + Whangaparaoa)','Devika Kumar','General Manager','devika.kumar@denhambramwell.co.nz','+64 9 985 6936','https://nz.linkedin.com/company/denham-bramwell','Research 2026-07-05 r3','A','new','GM with direct email + DDI on firm profile. Law Firm Leader of the Year 2025 (NZ Lawyer), active ALPMA member - exactly the ops buyer profile. THREE offices = multi-site potential.'),
('McElroys','law','https://mcelroys.co.nz','20-25','Level 9, GroupM House, 22 Fanshawe Street, Auckland 1140','Paul Sullivan','General Manager','paul.sullivan@mcelroys.co.nz','+64 9 887 4641','https://nz.linkedin.com/company/mcelroys-new-zealand','Research 2026-07-05 r3','A','new','Insurance/maritime litigation specialists. GM''s DDI + mobile (+64 204 0023 854) published on own bio; runs day-to-day operations. General: 09 307 2003.'),
('Thompson Blackie Biddles (TBB)','law','https://tbblegal.com','20-30','Level 36, PwC Tower, 15 Customs Street West, Auckland 1010','Kylie Robinson','Head of People, Premises & Culture','kylie.robinson@tbblegal.com','+64 21 930 770','https://nz.linkedin.com/company/tbblegal','Research 2026-07-05 r3','A','new','Commercial property law specialists, premium PwC Tower floor; contact title literally includes Premises - direct email + mobile published. Alt: Amanda Sagrillo, Practice Manager (amanda.sagrillo@tbblegal.com / 09 361 7050).'),
('Gilbert Walker','law','https://www.gilbertwalker.com','20-25','Level 35, Vero Centre, 48 Shortland Street, Auckland 1010','Arna Sluzenski','Practice Manager','arna.sluzenski@gilbertwalker.com','+64 9 951 2588','https://nz.linkedin.com/company/gilbert-walker-lawyers','Research 2026-07-05 r3','A','new','Top-tier litigation boutique, premium Vero Centre floor. PM''s DDI + mobile (+64 21 261 0178) + email all published. Vero Centre now holds FIVE targets (RLB L16, TLA L18, Delta L22, Northington L33, GW L35, Wynn Williams).'),
('K3 Legal (K3 Group)','law','https://www.k3.co.nz/legal','20-40','83 Albert Street, Auckland CBD 1010','Kanisya Sutharsan','Practice Manager','Kanisya@k3.co.nz','+64 21 900 974','https://nz.linkedin.com/company/k3-legal','Research 2026-07-05 r3','A','new','Multi-disciplinary group (legal + consulting + accounting) so the office is bigger than the legal headcount alone. PM''s direct email + mobile published on team page. General: 09 366 1366.'),
('Gaze Burt','law','https://www.gazeburt.co.nz','30-40','First Floor, 44 Corinthian Drive, Albany 0632 (also Symonds St CBD + Silverdale)','Erin Robson','Operations and Marketing Manager','erin.robson@gazeburt.co.nz','+64 9 414 9800','https://nz.linkedin.com/company/gaze-burt','Research 2026-07-05 r3','A','new','North Shore firm, THREE Auckland sites - multi-site potential. Direct email on her firm profile. Recently absorbed Wardill Pasley. Albany cluster with Davenports + Nexia Albany.'),
('Vallant Hooker & Partners','law','https://vallanthookerandpartners.co.nz','20-30','Upper Level, 19 Blake Street, Ponsonby, Auckland 1011','Amanda Anderson','Practice Manager (BCom ACA)','AAnderson@vhp.co.nz','+64 9 360 0321','https://nz.linkedin.com/company/vallant-hooker-partners','Research 2026-07-05 r3','A','new','Established Ponsonby firm (since 1990), 25 staff one office. PM is a chartered accountant with 30+ yrs ops experience; direct email published. Same street as Flow Transportation (Blake St).'),
('Daniel Overton & Goulding','law','https://www.doglaw.co.nz','30-40','33 Selwyn Street, Onehunga, Auckland (also Pukekohe office)','Alison Blom','Practice Manager','alison@doglaw.co.nz','+64 9 622 2222',NULL,'Research 2026-07-05 r3','A','new','Long-established Onehunga practice, 37 staff across 2 offices. PM''s direct email published. Past NZ Lawyer Employer of Choice.'),
('Wynn Williams (Auckland office)','law','https://wynnwilliams.co.nz','30-50','Vero Centre, 48 Shortland Street, Auckland CBD','Matthew Jones','Chief Operating Officer (Christchurch-based, owns ops firm-wide)','matthew.jones@wynnwilliams.co.nz','+64 21 556 777','https://www.linkedin.com/company/wynn-williams','Research 2026-07-05 r3','A','new','CAVEAT: COO sits in CHC but owns business support incl. the AKL office; direct email + mobile published on firm site. AKL general 09 300 2600. Sixth Vero Centre presence.'),
('Morrison Partners','law','https://www.morrisonpartners.co.nz','5-15','Level 12, 41 Shortland Street, Auckland 1010','Valerie Rey','Practice Manager (runs day-to-day office)','valerie.rey@morrisonpartners.co.nz','+64 9 320 3312',NULL,'Research 2026-07-05 r3','A','new','SIZE FLAG: ~9 staff boutique (post Morrison Mallett demerger) - kept for perfect contact quality (PM with DDI + mobile +64 21 924 668 + email, explicitly runs the office). Third target at 41 Shortland St (Jackson Russell L13, Haigh Lyon L19).'),
('Franklin Law','law','https://www.franklinlaw.co.nz','30-40','1 Wesley Street, Pukekohe, Auckland (also Papakura office)','Christel Hoy','Practice Manager',NULL,'0800 842 972','https://nz.linkedin.com/company/franklin-law-new-zealand-','Research 2026-07-05 r3','B','new','PM verified on firm''s own profile page (general management of the firm) but site blocks scrapers - direct email unverifiable, do not guess. Two offices (Pukekohe + Papakura).'),
('Inder Lynch Lawyers','law','https://www.inderlynch.co.nz','25-40','2 Wellington Street, Papakura 2244 (also Manukau + Pukekohe)','Joanna Goldfinch','Practice Manager','info@inderlynch.co.nz','+64 9 299 8550','https://nz.linkedin.com/company/inder-lynch-lawyers','Research 2026-07-05 r3','B','new','65+ years in South Auckland, THREE offices (Papakura/Manukau/Pukekohe) - multi-site potential. PM named, no direct contacts published.'),
('Tompkins Wake (Auckland office)','law','https://www.tompkinswake.com','30-50','Level 17, Shortland & Fort Building, 88 Shortland Street, Auckland 1010','Maree Haddon','Chief Operating Officer (Hamilton-based)',NULL,'+64 9 558 0699','https://nz.linkedin.com/company/tompkins-wake','Research 2026-07-05 r3','B','new','COO named on firm site (emails behind JS protection; Hamilton-based). Same building as Walker Wayland and Bankside Chambers (88 Shortland St).'),
-- ── CHAMBERS / IP / LEGAL-ADJACENT BODIES (11) ──────────────────────────────
('Shortland Chambers','law','https://www.shortlandchambers.co.nz','36-50','Level 13, 70 Shortland Street, Auckland 1010','Alison Van Wyk','Chambers Manager','avanwyk@shortlandchambers.co.nz','+64 9 307 9813','https://www.linkedin.com/company/shortland-chambers/','Research 2026-07-05 r3','A','new','One of NZ''s oldest/largest commercial chambers (36 barristers incl. 18 KCs), full floor. Chambers Manager is the published single point of contact for everything non-barrister - DDI + mobile (+64 21 701 473) on her own profile. Same building as BBD (70 Shortland).'),
('Bankside Chambers','law','https://www.bankside.co.nz','54-80','Level 22, Shortland & Fort, 88 Shortland Street, Auckland 1140','Eleni Balmer','Chambers Manager','eleni.balmer@bankside.co.nz','+64 9 379 0802','https://nz.linkedin.com/company/bankside-chambers','Research 2026-07-05 r3','A','new','Largest barristers'' set in NZ - TWO full floors of Shortland & Fort + Singapore annex. Chambers Manager already runs facilities-type procurement (visitor-management system per MRI case study). Third target in that building (Walker Wayland, Tompkins Wake).'),
('Mills Lane Chambers','law','https://www.millslane.co.nz','30-40','Level 27, QBE Building, 125 Queen Street, Auckland 1010','Nicole Brothers','Chambers Manager','admin@millslane.co.nz','+64 9 323 4556',NULL,'Research 2026-07-05 r3','B','new','Large modern set spanning two levels of the QBE Building. Manager named on site; published channel is the general admin@ inbox. Same building as RSM CBD (125 Queen St).'),
('Richmond Chambers','law','https://richmondchambers.co.nz','18-25','Level 6, General Buildings, 33 Shortland Street, Auckland 1140',NULL,NULL,'office@richmondchambers.co.nz','+64 9 600 5500','https://nz.linkedin.com/company/richmond-chambers','Research 2026-07-05 r3','C','new','Full floor of the heritage General Buildings in the legal precinct; enquiries route to an office manager but no ops person named publicly - phone call to get the name.'),
('AJ Park','law','https://www.ajpark.com','50-100','Level 14, Aon Centre, 29 Customs Street West, Auckland 1010','Grace Havill','Head of Operations',NULL,'+64 9 356 6996','https://www.linkedin.com/company/a-j-park','Research 2026-07-05 r3','B','new','NZ''s largest IP firm (IPH group). Named Head of Operations verified via LinkedIn + firm''s official announcements, but no direct contact published on ajpark.com - approach via LinkedIn or main line. Same street corner as TBB (Customs St West).'),
('ET Intellectual Property','law','https://etiplaw.com','10-30','Level 16, The Shortland Centre, 55 Shortland Street, Auckland 1010',NULL,NULL,'mail@etiplaw.com','+64 9 975 1073','https://nz.linkedin.com/company/ellis-terry','Research 2026-07-05 r3','C','new','IP law firm + patent attorneys (rebranded from Ellis Terry); verified AKL office. No non-attorney ops staff published. Same building as Oyster Property (55 Shortland).'),
('The Law Association of New Zealand','professional','https://thelawassociation.nz','15-25','Level 18, Vero Centre, 48 Shortland Street, Auckland 1010','Clayton Kimpton','Chief Executive Officer','clayton.kimpton@tlanz.nz','+64 9 303 5281','https://nz.linkedin.com/company/the-law-association-of-new-zealand','Research 2026-07-05 r3','A','new','Formerly ADLS; runs a busy CPD/events programme from Vero Centre offices. Staff page publishes EVERY senior manager''s DDI + email - alt ops contact: Andrew Simpson, Head of Finance (andrew.simpson@tlanz.nz / 09 303 5272). Vero Centre cluster.'),
('EMA (Employers and Manufacturers Association)','professional','https://ema.co.nz','50-150','145 Khyber Pass Road, Grafton, Auckland 1023','John Fraser-Mackenzie','Chief Executive',NULL,'+64 9 367 0900','https://nz.linkedin.com/company/ema-nz','Research 2026-07-05 r3','B','new','Big standalone Grafton premises with member training rooms + event spaces - a genuine multi-space cleaning contract. Leadership named, no direct contacts published; Head of People & Support Services (Omima Alsafwani per LinkedIn) likely owns facilities. Grafton cluster.'),
('Property Council New Zealand','professional','https://propertynz.co.nz','15-25','Level 4, 51 Shortland Street, Auckland 1140','Rona Miller','Head of Operations','rona@propertynz.co.nz',NULL,'https://nz.linkedin.com/company/propertycouncilnz','Research 2026-07-05 r3','A','new','Property-sector peak body, national office in AKL. EVERY staff email published on team page. Head of Operations oversees internal ops; alt: Tasch Dodson, AKL Regional Manager (tasch@propertynz.co.nz / 022 088 2724). STRATEGIC: members are commercial property owners - referral upside. General: 09 373 3086.'),
('New Zealand Dispute Resolution Centre (NZDRC)','professional','https://nzdrc.co.nz','15-40','Level 2, 129 Hurstmere Road, Takapuna, Auckland 0622','Catherine Green','Executive Director (NZDRC/NZIAC/BDT/FDR Centre)','registrar@nzdrc.co.nz','+64 9 486 7153','https://nz.linkedin.com/company/nzdrc','Research 2026-07-05 r3','B','new','Legal-adjacent with real Takapuna premises incl. client-facing hearing/mediation rooms (presentation matters). Executive Director named; general registry channel only. Takapuna cluster.'),
('Marketing Association','professional','https://marketing.org.nz','15-20','69 St Georges Bay Road, Parnell, Auckland 1052','John Miles','Chief Executive Officer','john@marketing.org.nz','+64 9 361 7760','https://nz.linkedin.com/company/marketing-association','Research 2026-07-05 r3','A','new','Membership body with own Parnell premises used for training courses + events (high foot traffic = recurring cleaning). CEO''s direct email published; Kirsty Jamieson, COO, is the named ops second. Same street as Mansons (St Georges Bay Rd).'),
-- ── BODY CORPORATE / PROPERTY / ASSOCIATIONS (11) ───────────────────────────
('Body Corporate Administration Ltd (BCA)','property','https://go.bca.co.nz','40-60','Level 3, 115 Queen Street, Auckland CBD 1010','Paula Beaton','General Manager','paula@bca.co.nz','021 612 336','https://nz.linkedin.com/company/body-corporate-administration','Research 2026-07-05 r3','A','new','DOUBLE VALUE: own Queen St office + administers 1000+ multi-unit properties NZ-wide - gateway to common-area cleaning across a large portfolio. GM''s direct mobile published on own site. General: 09 373 2336.'),
('Strata Title Administration Ltd','property','https://www.stratatitle.co.nz','40-60','Level 1, Dilworth Building, cnr Queen St & Customs St East, Auckland CBD','Nicola Bullock','General Manager','nicolabullock@stratatitle.co.nz','09 307 3721','https://nz.linkedin.com/company/strata-title-administration-ltd','Research 2026-07-05 r3','A','new','Est. 1996; manages bodies corporate up to 500+ apartment towers. EVERY staff member''s direct email published. Alt: Martin Caie, Acting AKL Head of BC Management (Martin@stratatitle.co.nz).'),
('Auckland Body Corporate (Bayleys group)','property','https://www.aucklandbodycorporate.co.nz','20-30','30 Gaunt Street, Wynyard Quarter, Auckland','Chris Newman','General Manager','chris@aucklandbodycorporate.co.nz','09 216 5050','https://nz.linkedin.com/company/auckland-body-corporate','Research 2026-07-05 r3','A','new','Bayleys-backed BC manager; employs own building managers (Hayden Spierings, Sachin Malik, Grant Marange - all with published direct mobiles/emails) who procure services for managed towers. Alt entry: Roger Shephard BDM (roger@ / 021 719 608).'),
('Boutique Body Corporates Ltd','property','https://www.bbcl.co.nz','30-40','Building B, Level 2, 8 Nugent Street, Grafton, Auckland 1023','Craig Leishman','Managing Director','Craig@bbcl.co.nz','09 523 6542',NULL,'Research 2026-07-05 r3','A','new','36-strong Grafton office; portfolio incl. Wynyard Central, Ascent, Hudson Brown, Botany Palms. Every staff member has published DDI + direct email. Same building as Woods (8 Nugent St).'),
('Goodwins','property','https://www.goodwins.co.nz','30-40','21A Wellesley Street West, Auckland CBD','Aleina Goodwin','Chief Operations Officer & HR','aleina@goodwins.co.nz','021 278 7763','https://nz.linkedin.com/company/goodwinsnz','Research 2026-07-05 r3','A','new','Independent AKL agency since 1991, NZ$1.5b+ managed; residential PM + executive rentals (turnover-clean demand) + commercial leasing. COO''s direct mobile published. General: 09 373 4400.'),
('Samson Corporation Ltd','property','https://www.samson.co.nz','10-20','Level 1, Suite 2, Geyser Building, 100 Parnell Road, Parnell, Auckland 1052','Bluey Inia','Facilities Manager',NULL,'09 524 1350','https://nz.linkedin.com/company/samsoncorporation','Research 2026-07-05 r3','A','new','Friedlander family character-commercial portfolio (~$2b per NZ Herald: Ironbank, Axis, Geyser + 8 more buildings). Also published DDIs: Elizabeth Joseph, Building & Compliance Mgr (09 524 1351); Bridget Pyc, Sustainability Mgr (09 524 1355). Small office, BIG portfolio upside.'),
('Impression Real Estate Ltd','property','https://impression.co.nz','10-20','14 Beaumont Street, Freemans Bay, Auckland 1011','Jacques Gouws','Chief Operating Officer',NULL,'09 300 5001','https://nz.linkedin.com/company/impression-real-estate','Research 2026-07-05 r3','B','new','CBD apartment specialist since 1999: 1,500+ managed properties (~90% BC apartments) + in-house Building Manager (Paul Challis) - strong common-area and turnover cleaning upside.'),
('Mansons TCLM Ltd','property','https://mansons.co.nz','50-100','74 St Georges Bay Road, Parnell, Auckland','Carlos McKee','Services Manager',NULL,'09 377 3660','https://nz.linkedin.com/company/mansons-tclm-limited','Research 2026-07-05 r3','B','new','Family-owned developer-landlord in own Parnell HQ; team page also names Braden King, HQ Maintenance Manager - in-house ops function that buys building services. Portfolio across Wynyard/CBD/Newmarket/Parnell.'),
('Argosy Property Ltd','property','https://www.argosy.co.nz','10-20','Level 1, 39 Market Place, Viaduct Harbour, Auckland 1010','Haley Jones','Manager Property Services',NULL,'09 304 3400','https://nz.linkedin.com/company/argosy-property-ltd','Research 2026-07-05 r3','B','new','NZX-listed diversified landlord; modest single-floor Viaduct head office, but Manager Property Services sits over property-level service procurement across the portfolio.'),
('New Zealand Green Building Council (NZGBC)','other','https://nzgbc.org.nz','25-50','Level 2, Tower 1, 205 Queen Street, Auckland CBD','Jill Solomon','Director of Operations','jill.solomon@nzgbc.org.nz','09 379 3996','https://nz.linkedin.com/company/new-zealand-green-building-council','Research 2026-07-05 r3','A','new','Occupies a 5 Green Star-rated CBD office - a cleaner with low-tox/sustainable practices fits their procurement values perfectly. Director of Operations published with direct email on own leadership page. Same building as Brookfields (205 Queen St).'),
('Restaurant Association of New Zealand','other','https://www.restaurantnz.co.nz','10-30','45 Normanby Road, Mt Eden, Auckland 1024','Marisa Bidois','Chief Executive','info@restaurantnz.co.nz','09 638 8403','https://nz.linkedin.com/company/restaurant-association-of-new-zealand','Research 2026-07-05 r3','B','new','Own Mt Eden building incl. the taste. function venue (venue manager Nata Tolooei, DDI 09 632 1408 published) - hospitality-grade recurring cleaning beyond a standard office. Same street as Origin Fire (Normanby Rd).'),
-- ── BOUTIQUE CONSULTANCIES (12) ─────────────────────────────────────────────
('Origin Fire Consultants','engineering','https://www.originfire.co.nz','15-20','Level 1, 18 Normanby Road, Mt Eden, Auckland 1024','Michael James','Managing Director & Principal Fire Engineer',NULL,'021 708 460','https://nz.linkedin.com/company/origin-fire-consultants-ltd','Research 2026-07-05 r3','A','new','Boutique fire engineering consultancy, own Mt Eden office; MD''s direct mobile published on his profile page. In-house office/finance admin (Emma Northcott) coordinates premises services. General 09 520 0439.'),
('Flow Transportation Specialists','engineering','https://www.flownz.com','20-25','Level 1, 11 Blake Street, Ponsonby, Auckland 1011','Michael Hall','Commercial & Operations Manager','info@flownz.com','021 115 4882','https://nz.linkedin.com/company/flow-transportation-specialists','Research 2026-07-05 r3','A','new','AKL-only traffic/transport consultancy in Ponsonby villa-office; EVERY team member''s direct number published. Michael Hall holds the exact Commercial & Ops remit that owns cleaning contracts (phone is his published mobile). Same street as Vallant Hooker (Blake St).'),
('Kwanto','professional','https://kwanto.co.nz','10-15','4 Minnie Street, Eden Terrace, Auckland 1021','Angela Adamski','Office Manager','angela@kwanto.co.nz','022 024 1956','https://nz.linkedin.com/company/kwanto','Research 2026-07-05 r3','A','new','QS + PM boutique (est. 2006), own Eden Terrace premises; publishes direct email + mobile for every person INCLUDING the Office Manager - the ideal contract contact. Below 20-staff band, kept for contact quality. Eden Terrace cluster with eCubed + Fergus.'),
('Oculus Building Science & Facades','engineering','https://www.obsf.co','10-15','515 Rosebank Road, Avondale, Auckland 1026','Shawn McIsaac','Managing Director','shawn@obsf.co','022 021 9960','https://www.linkedin.com/company/oculus-architectural-engineering','Research 2026-07-05 r3','A','new','Facade/building-enclosure consultancy with Avondale premises incl. a TESTING LAB (Lab Manager Mark Ashforth also published) - specialist-cleaning angle. Every team member''s direct email + mobile on site. Below band, kept for quality.'),
('Marshall Day Acoustics','engineering','https://marshallday.com','50-100','84 Symonds Street, Grafton, Auckland 1010','Christopher Day','Founding Partner (Auckland)','chris.day@marshallday.co.nz','+64 9 379 7822','https://nz.linkedin.com/company/marshall-day-acoustics','Research 2026-07-05 r3','A','new','NZ''s leading acoustics consultancy (founded AKL 1981), Symonds St HQ; staff profile pages carry direct emails. Acoustic test spaces = dust-controlled premises matter. Grafton cluster.'),
('The Building Intelligence Group (TBIG)','professional','https://tbig.co.nz','50-100','119 Wellesley Street West, Auckland CBD','Charles Brown','Business Manager Greater Auckland','c.brown@tbig.co.nz','+64 9 300 9980','https://nz.linkedin.com/company/the-building-intelligence-group','Research 2026-07-05 r3','A','new','Independent PM/advisory firm, 30+ years, 100% staff-owned; Business Manager Greater Auckland is precisely the regional ops-budget owner, direct email published on own people page.'),
('WT Partnership New Zealand','professional','https://wtpartnership.co.nz','50-70','Level 4, 18 Shortland Street, Auckland 1010','Scott McCondach','Managing Director, WT New Zealand',NULL,'+64 9 300 7800','https://nz.linkedin.com/company/wt-new-zealand','Research 2026-07-05 r3','B','new','Global QS/cost-management firm''s NZ arm, AKL CBD head office; MD named on own team page, direct contacts only in third-party DBs (not used).'),
('Maltbys','professional','https://maltbys.co.nz','20-30','Auckland office (street address not published on site)','Gary Townsend','Director (Auckland)',NULL,'+64 9 303 4394','https://www.linkedin.com/company/maltbys-ltd','Research 2026-07-05 r3','B','new','NZ''s oldest QS practice (since 1929), NZ-owned; two AKL directors named (also Phillip McCamish), no direct contacts published. Confirm street address by phone.'),
('Maynard Marks','professional','https://maynardmarks.co.nz','50-100','Level 8, 66 Wyndham Street, Auckland 1010','Daniel Kennett','Director, Chartered Structural Engineer','office@maynardmarks.co.nz','+64 9 912 2550','https://nz.linkedin.com/company/maynard-marks','Research 2026-07-05 r3','B','new','Property/building consultancy (surveying, remediation, asbestos, QS), B Corp certified, AKL CBD HQ. THIRD target at 66 Wyndham St (ICIB, Seagars).'),
('Fraser Thomas','engineering','https://fraserthomas.co.nz','50-100','Level G, 17 Sultan Street, Ellerslie, Auckland 1051','Greg Maddren','Managing Director','auckland@ftl.co.nz','+64 9 278 7078','https://nz.linkedin.com/company/fraser-thomas-ltd','Research 2026-07-05 r3','B','new','100% NZ-owned multi-disciplinary engineering + surveying consultancy (est. 1969); AKL head office in Ellerslie. MD + 12 directors named, no direct contacts.'),
('Isthmus Group','professional','https://isthmus.co.nz','50-100','Level 6, 246 Queen Street, Auckland 1010','Marko den Breems','Chief Executive Officer','studio@isthmus.co.nz','0800 478 468','https://nz.linkedin.com/company/isthmus-group-ltd','Research 2026-07-05 r3','B','new','Design-led landscape architecture/urban design studio (est. 1988), AKL HQ on Queen St; CEO is ex-Jasmax CEO (appointed 2024) - if Jasmax outreach lands well, natural cross-reference.'),
('Babbage Consultants','engineering','https://babbage.co.nz','150+','Level 4, Quay Park Health Building, 68 Beach Road, Auckland CBD 1010','Jerome Deperrois','Chief Executive Officer','contact-us@babbage.co.nz','+64 9 379 9980','https://nz.linkedin.com/company/babbage-consultants-limited','Research 2026-07-05 r3','B','new','Multi-disciplinary architecture/engineering/environmental consultancy HQ''d at Quay Park; slightly above band (~205) - stretch target. CEO named, no direct contacts.');
