'use server'

// Phase 6 — quote versioning server actions.
//
// createNewVersion(quoteId)         — used by "Save changes" on a sent/viewed
//                                     quote. Clones the latest into a new
//                                     draft (v_n+1), demotes the old latest.
// restoreFromVersion(versionId)     — used by "Restore from this version" on
//                                     the version-history panel. Same machinery
//                                     as createNewVersion, but the source is
//                                     the historical row rather than the
//                                     current latest.
//
// Both write a record_snapshots row + audit_log entry on every transition.
// Both clone associated rows: quote_items, commercial_quote_details (1:1),
// commercial_scope_items (1:N).

import { createClient } from '@/lib/supabase-server'
import { revalidatePath } from 'next/cache'

// Columns we DO NOT copy when cloning — they must be re-derived per version.
const NON_COPIED_COLUMNS = new Set<string>([
  'id',
  'created_at',
  'updated_at',
  'share_token',
  'version_number',
  'parent_quote_id',
  'is_latest_version',
  'version_note',
  // Lifecycle stamps — every new version starts fresh.
  'sent_at',
  'accepted_at',
  'declined_at',
  // Soft-delete columns — new version is active.
  'deleted_at',
  'deleted_by',
])

type QuoteRow = Record<string, unknown> & {
  id: string
  quote_number: string
  status: string | null
  version_number: number
  parent_quote_id: string | null
  is_latest_version: boolean
}

interface CreateVersionResult {
  ok?: true
  new_quote_id?: string
  error?: string
}

/**
 * Internal cloner. Given a source quote row, creates a new version that
 * either (a) descends from the current latest of this chain (createNewVersion)
 * or (b) restores from a specific historical row (restoreFromVersion). The
 * caller resolves which "source" row to clone before calling here.
 *
 * The new row:
 *   - status = 'draft'
 *   - version_number = max(version_number) of chain + 1
 *   - parent_quote_id = the chain root id (v1)
 *   - is_latest_version = true (and we demote the prior latest in the same op)
 *   - share_token = generated by DB default (matches existing `quotes` table)
 */
async function cloneAsNewVersion(
  source: QuoteRow,
  versionNote: string | null,
  reason: 'quote.version-created' | 'quote.version-restored',
  audit_after: Record<string, unknown>,
): Promise<CreateVersionResult> {
  const supabase = createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  // Resolve the chain root id (v1 of this chain).
  const chainRootId = source.parent_quote_id ?? source.id

  // Find the current latest of this chain so we can demote it after cloning.
  const { data: currentLatest, error: latestErr } = await supabase
    .from('quotes')
    .select('id, version_number')
    .or(`id.eq.${chainRootId},parent_quote_id.eq.${chainRootId}`)
    .eq('is_latest_version', true)
    .is('deleted_at', null)
    .maybeSingle()

  if (latestErr) {
    return { error: `Failed to resolve chain latest: ${latestErr.message}` }
  }

  // Find the highest version_number in this chain to assign the next one.
  // (Uses .order + .limit so we don't depend on the row count being small.)
  const { data: highest, error: highestErr } = await supabase
    .from('quotes')
    .select('version_number')
    .or(`id.eq.${chainRootId},parent_quote_id.eq.${chainRootId}`)
    .order('version_number', { ascending: false })
    .limit(1)
    .single()

  if (highestErr) {
    return { error: `Failed to find next version number: ${highestErr.message}` }
  }
  const nextVersionNumber = (highest?.version_number ?? 1) + 1

  // Build the insert payload by copying source minus non-copied columns.
  const insertPayload: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(source)) {
    if (NON_COPIED_COLUMNS.has(k)) continue
    insertPayload[k] = v
  }
  insertPayload.status = 'draft'
  insertPayload.version_number = nextVersionNumber
  insertPayload.parent_quote_id = chainRootId
  insertPayload.is_latest_version = true
  insertPayload.version_note = versionNote

  // Snapshot the prior latest BEFORE we demote it, so the audit trail is
  // self-contained.
  if (currentLatest) {
    const { data: priorRow } = await supabase
      .from('quotes')
      .select('*')
      .eq('id', currentLatest.id)
      .single()

    if (priorRow) {
      await supabase.from('record_snapshots').insert({
        entity_table: 'quotes',
        entity_id: currentLatest.id,
        reason,
        snapshot: priorRow as unknown as Record<string, unknown>,
        created_by: user.id,
      })
    }

    // Demote prior latest. Race guard: only flip if it's still latest.
    const { error: demoteErr } = await supabase
      .from('quotes')
      .update({ is_latest_version: false })
      .eq('id', currentLatest.id)
      .eq('is_latest_version', true)
    if (demoteErr) {
      return { error: `Failed to demote prior version: ${demoteErr.message}` }
    }
  }

  // Insert the new version row.
  const { data: inserted, error: insertErr } = await supabase
    .from('quotes')
    .insert(insertPayload)
    .select('id')
    .single()

  if (insertErr || !inserted) {
    // Best effort: re-promote the prior latest so the chain isn't left
    // headless. (Safe — we know it WAS latest a moment ago.)
    if (currentLatest) {
      await supabase
        .from('quotes')
        .update({ is_latest_version: true })
        .eq('id', currentLatest.id)
    }
    return { error: `Failed to create new version: ${insertErr?.message ?? 'unknown'}` }
  }

  // Clone associated child rows into the new version.
  const newId = inserted.id as string

  // quote_items (1:N — every quote)
  const { data: items } = await supabase
    .from('quote_items')
    .select('label, price, sort_order')
    .eq('quote_id', source.id)
  if (items && items.length > 0) {
    await supabase
      .from('quote_items')
      .insert(items.map((it) => ({ ...it, quote_id: newId })))
  }

  // commercial_quote_details (1:1 — commercial only)
  const { data: cqd } = await supabase
    .from('commercial_quote_details')
    .select('*')
    .eq('quote_id', source.id)
    .maybeSingle()
  if (cqd) {
    const cqdInsert: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(cqd as Record<string, unknown>)) {
      if (k === 'id' || k === 'created_at' || k === 'updated_at') continue
      cqdInsert[k] = v
    }
    cqdInsert.quote_id = newId
    await supabase.from('commercial_quote_details').insert(cqdInsert)
  }

  // commercial_scope_items (1:N — commercial only)
  const { data: scope } = await supabase
    .from('commercial_scope_items')
    .select('*')
    .eq('quote_id', source.id)
    .order('display_order')
  if (scope && scope.length > 0) {
    const scopeInsert = scope.map((row) => {
      const r = { ...(row as Record<string, unknown>) }
      delete r.id
      delete r.created_at
      r.quote_id = newId
      return r
    })
    await supabase.from('commercial_scope_items').insert(scopeInsert)
  }

  // Audit row.
  await supabase.from('audit_log').insert({
    actor_id: user.id,
    actor_role: 'staff',
    action: reason,
    entity_table: 'quotes',
    entity_id: newId,
    before: { from_version_id: source.id, from_version_number: source.version_number },
    after: { ...audit_after, new_version_number: nextVersionNumber },
  })

  // Revalidate caches that show this chain.
  revalidatePath('/portal/quotes')
  revalidatePath(`/portal/quotes/${source.id}`)
  revalidatePath(`/portal/quotes/${newId}`)

  return { ok: true, new_quote_id: newId }
}

/**
 * Bump the current latest of this chain into a new draft version.
 * Used when "Save changes" is invoked on a sent/viewed quote.
 */
export async function createNewVersion(
  quoteId: string,
  opts: { version_note?: string | null } = {},
): Promise<CreateVersionResult> {
  const supabase = createClient()

  const { data: source, error: sourceErr } = await supabase
    .from('quotes')
    .select('*')
    .eq('id', quoteId)
    .single()

  if (sourceErr || !source) {
    return { error: `Quote not found: ${sourceErr?.message ?? 'unknown'}` }
  }
  if (!(source as QuoteRow).is_latest_version) {
    return { error: 'A new version can only be created from the latest version of a quote.' }
  }

  return cloneAsNewVersion(
    source as QuoteRow,
    opts.version_note ?? 'Edit while sent',
    'quote.version-created',
    { source: 'edit_while_sent' },
  )
}

/**
 * Restore an older version by cloning it into a new latest draft.
 * Does not overwrite history — original rows stay read-only.
 */
export async function restoreFromVersion(
  versionId: string,
  opts: { version_note?: string | null } = {},
): Promise<CreateVersionResult> {
  const supabase = createClient()

  const { data: source, error: sourceErr } = await supabase
    .from('quotes')
    .select('*')
    .eq('id', versionId)
    .single()

  if (sourceErr || !source) {
    return { error: `Source version not found: ${sourceErr?.message ?? 'unknown'}` }
  }

  return cloneAsNewVersion(
    source as QuoteRow,
    opts.version_note ?? `Restored from v${(source as QuoteRow).version_number}`,
    'quote.version-restored',
    {
      source: 'restore_from_prior',
      restored_from_version: (source as QuoteRow).version_number,
    },
  )
}

/**
 * Read the full version chain for a quote, ordered v1 → vN.
 * Returns the rows including non-latest and latest, excluding deleted.
 */
export async function loadVersionChain(quoteId: string) {
  const supabase = createClient()

  const { data: row } = await supabase
    .from('quotes')
    .select('id, parent_quote_id')
    .eq('id', quoteId)
    .single()

  if (!row) return []
  const chainRootId = row.parent_quote_id ?? row.id

  const { data: chain } = await supabase
    .from('quotes')
    .select('id, quote_number, status, version_number, version_note, is_latest_version, created_at, base_price, discount, contact_name, contact_email, accounts_email, client_reference, service_address')
    .or(`id.eq.${chainRootId},parent_quote_id.eq.${chainRootId}`)
    .is('deleted_at', null)
    .order('version_number', { ascending: true })

  return chain ?? []
}
